-- YouTube provider topics, mapped onto our concepts.
--
-- Generated by `tools/youtube_topics.py --emit`. Do not hand-edit: change the
-- tool and regenerate, or the file and the rules it came from stop agreeing.
--
-- 20 topics carried, 20 with a Wikidata QID, 5 refused.
--
-- **This is `provider_topic` and needs no approval.** The topics arrive as
-- Wikipedia URLs on `topicDetails.topicCategories` — YouTube states them — so
-- mapping one onto a concept is reading a supplied label. `written_title_tag`,
-- which is the inferring kind, is gated behind `allow_title_tags` and is not
-- here.
--
-- Measured before it was written: 639 real rows carry 28 distinct topics, five
-- of which cover 80% of them. The gain is depth on a small vocabulary, not
-- coverage of a long tail.
--
-- A published ontology version is immutable, so this mints 0.4.0 from
-- 0.3.0, copies it forward wholesale, adds the below, and publishes
-- last — publishing is also retiring, since only one version may be published.

begin;

insert into ontology.versions (id, version, parent_version_id, status, description, published_at)
select gen_random_uuid(), '0.4.0', v.id, 'draft',
       'YouTube provider topics mapped onto concepts.', null
from ontology.versions v where v.version = '0.3.0'
on conflict (version) do nothing;

insert into ontology.concept_revisions (ontology_version_id, concept_id, preferred_label, concept_kind, definition, sensitivity, inference_policy, status, metadata)
select new_v.id, r.concept_id, r.preferred_label, r.concept_kind, r.definition, r.sensitivity, r.inference_policy, r.status, r.metadata
from ontology.concept_revisions r
join ontology.versions old_v on old_v.id = r.ontology_version_id and old_v.version = '0.3.0'
cross join (select id from ontology.versions where version = '0.4.0') new_v
on conflict do nothing;

insert into ontology.concept_labels (ontology_version_id, concept_id, label, normalized_label, locale, label_type, provenance_type, confidence, status, external_ref)
select new_v.id, l.concept_id, l.label, l.normalized_label, l.locale, l.label_type, l.provenance_type, l.confidence, l.status, l.external_ref
from ontology.concept_labels l
join ontology.versions old_v on old_v.id = l.ontology_version_id and old_v.version = '0.3.0'
cross join (select id from ontology.versions where version = '0.4.0') new_v
on conflict do nothing;

insert into ontology.concept_edges (ontology_version_id, subject_concept_id, predicate_key, object_concept_id, confidence, provenance_type, provenance, status)
select new_v.id, e.subject_concept_id, e.predicate_key, e.object_concept_id, e.confidence, e.provenance_type, e.provenance, e.status
from ontology.concept_edges e
join ontology.versions old_v on old_v.id = e.ontology_version_id and old_v.version = '0.3.0'
cross join (select id from ontology.versions where version = '0.4.0') new_v
on conflict do nothing;

insert into ontology.motif_rules (
  id, ontology_version_id, rule_key, evidence_target_concept_id, output_concept_id,
  evidence_predicate_key, output_predicate_key, rule_kind,
  minimum_independence_groups, minimum_strength, configuration, status)
select gen_random_uuid(), new_v.id, m.rule_key, m.evidence_target_concept_id,
       m.output_concept_id, m.evidence_predicate_key, m.output_predicate_key,
       m.rule_kind, m.minimum_independence_groups, m.minimum_strength,
       m.configuration, m.status
from ontology.motif_rules m
join ontology.versions old_v on old_v.id = m.ontology_version_id and old_v.version = '0.3.0'
cross join (select id from ontology.versions where version = '0.4.0') new_v
on conflict do nothing;

create temporary table seed_concept (concept_key text primary key, preferred_label text not null, concept_kind text not null) on commit drop;
insert into seed_concept values
  ('genre:action_adventure_game', 'Action-adventure games', 'genre'),
  ('genre:action_game', 'Action games', 'genre'),
  ('concept:fashion', 'Fashion', 'topic'),
  ('concept:humour', 'Comedy', 'topic'),
  ('genre:indie', 'Indie', 'genre'),
  ('genre:asian_music', 'Asian music', 'genre'),
  ('genre:role_playing_game', 'Role-playing games', 'genre'),
  ('genre:strategy_game', 'Strategy games', 'genre'),
  ('concept:technology', 'Technology', 'topic'),
  ('medium:television', 'Television', 'medium'),
  ('concept:tourism', 'Travel', 'topic');

create temporary table seed_label (concept_key text, label text, normalized_label text, external_ref jsonb) on commit drop;
insert into seed_label values
  ('genre:action_adventure_game', 'Action-adventure_game', 'action-adventure game', '{"provider": "youtube", "wikidata": "Q343568", "wikipedia": "Action-adventure_game"}'::jsonb),
  ('genre:action_game', 'Action_game', 'action game', '{"provider": "youtube", "wikidata": "Q270948", "wikipedia": "Action_game"}'::jsonb),
  ('genre:classical', 'Classical_music', 'classical music', '{"provider": "youtube", "wikidata": "Q9730", "wikipedia": "Classical_music"}'::jsonb),
  ('genre:electronic', 'Electronic_music', 'electronic music', '{"provider": "youtube", "wikidata": "Q9778", "wikipedia": "Electronic_music"}'::jsonb),
  ('concept:fashion', 'Fashion', 'fashion', '{"provider": "youtube", "wikidata": "Q12684", "wikipedia": "Fashion"}'::jsonb),
  ('hub:film_video', 'Film', 'film', '{"provider": "youtube", "wikidata": "Q11424", "wikipedia": "Film"}'::jsonb),
  ('hub:food_drink', 'Food', 'food', '{"provider": "youtube", "wikidata": "Q2095", "wikipedia": "Food"}'::jsonb),
  ('genre:hip_hop', 'Hip_hop_music', 'hip hop music', '{"provider": "youtube", "wikidata": "Q11401", "wikipedia": "Hip_hop_music"}'::jsonb),
  ('concept:humour', 'Humour', 'humour', '{"provider": "youtube", "wikidata": "Q35874", "wikipedia": "Humour"}'::jsonb),
  ('genre:indie', 'Independent_music', 'independent music', '{"provider": "youtube", "wikidata": "Q42201", "wikipedia": "Independent_music"}'::jsonb),
  ('hub:ideas_learning', 'Knowledge', 'knowledge', '{"provider": "youtube", "wikidata": "Q9081", "wikipedia": "Knowledge"}'::jsonb),
  ('hub:music', 'Music', 'music', '{"provider": "youtube", "wikidata": "Q638", "wikipedia": "Music"}'::jsonb),
  ('genre:asian_music', 'Music_of_Asia', 'music of asia', '{"provider": "youtube", "wikidata": "Q525073", "wikipedia": "Music_of_Asia"}'::jsonb),
  ('genre:pop', 'Pop_music', 'pop music', '{"provider": "youtube", "wikidata": "Q37073", "wikipedia": "Pop_music"}'::jsonb),
  ('genre:role_playing_game', 'Role-playing_video_game', 'role-playing video game', '{"provider": "youtube", "wikidata": "Q744038", "wikipedia": "Role-playing_video_game"}'::jsonb),
  ('genre:strategy_game', 'Strategy_video_game', 'strategy video game', '{"provider": "youtube", "wikidata": "Q472055", "wikipedia": "Strategy_video_game"}'::jsonb),
  ('concept:technology', 'Technology', 'technology', '{"provider": "youtube", "wikidata": "Q11016", "wikipedia": "Technology"}'::jsonb),
  ('medium:television', 'Television_program', 'television program', '{"provider": "youtube", "wikidata": "Q15416", "wikipedia": "Television_program"}'::jsonb),
  ('concept:tourism', 'Tourism', 'tourism', '{"provider": "youtube", "wikidata": "Q49389", "wikipedia": "Tourism"}'::jsonb),
  ('hub:games_play', 'Video_game_culture', 'video game culture', '{"provider": "youtube", "wikidata": "Q7927912", "wikipedia": "Video_game_culture"}'::jsonb);

create temporary table seed_edge (subject_key text, object_key text) on commit drop;
insert into seed_edge values
  ('concept:humour', 'hub:arts_live'),
  ('concept:technology', 'hub:ideas_learning'),
  ('concept:tourism', 'hub:places_cultures'),
  ('genre:action_adventure_game', 'hub:games_play'),
  ('genre:action_game', 'hub:games_play'),
  ('genre:asian_music', 'hub:music'),
  ('genre:cantopop', 'genre:asian_music'),
  ('genre:indie', 'hub:music'),
  ('genre:j_pop', 'genre:asian_music'),
  ('genre:k_pop', 'genre:asian_music'),
  ('genre:mandopop', 'genre:asian_music'),
  ('genre:role_playing_game', 'hub:games_play'),
  ('genre:strategy_game', 'hub:games_play'),
  ('medium:television', 'hub:film_video');

insert into ontology.concepts (id, concept_key)
select gen_random_uuid(), s.concept_key from seed_concept s
on conflict (concept_key) do nothing;

-- `inference_policy = 'inferable'`: every one of these is a topic YouTube
-- *stated* on the video. Reading is not inferring — the same distinction that
-- keeps `Ontology.classify` away from YouTube entirely.
insert into ontology.concept_revisions (
  ontology_version_id, concept_id, preferred_label, concept_kind,
  definition, sensitivity, inference_policy, status, metadata)
select v.id, c.id, s.preferred_label, s.concept_kind,
       'A topic YouTube stated on a video; never inferred from a title.',
       'ordinary', 'inferable', 'active', '{}'::jsonb
from seed_concept s
join ontology.concepts c on c.concept_key = s.concept_key
cross join (select id from ontology.versions where version = '0.4.0') v
on conflict (ontology_version_id, concept_id) do nothing;

-- **`source_term`, because that is exactly what these are.** The provider's own
-- string, kept so the resolver can look it up, and never shown to anybody.
insert into ontology.concept_labels (
  ontology_version_id, concept_id, label, normalized_label, locale,
  label_type, provenance_type, confidence, status, external_ref)
select v.id, c.id, l.label, l.normalized_label, 'und',
       'source_term', 'provider', 1.0, 'active', l.external_ref
from seed_label l
join ontology.concepts c on c.concept_key = l.concept_key
cross join (select id from ontology.versions where version = '0.4.0') v
on conflict (ontology_version_id, concept_id, locale, normalized_label, label_type)
  do nothing;

-- `broader` is hierarchical, assertion-safe and one hop: a K-pop listener
-- reaches Asian music, and nothing reaches back down to claim they listen to
-- Mandopop.
insert into ontology.concept_edges (
  ontology_version_id, subject_concept_id, predicate_key, object_concept_id,
  confidence, provenance_type, provenance, status)
select v.id, subject.id, 'broader', object.id, 1.0, 'external',
       '{"source": "youtube_topics", "basis": "wikidata"}'::jsonb, 'active'
from seed_edge e
join ontology.concepts subject on subject.concept_key = e.subject_key
join ontology.concepts object on object.concept_key = e.object_key
cross join (select id from ontology.versions where version = '0.4.0') v
on conflict do nothing;

update ontology.versions set status = 'retired'
 where version = '0.3.0' and status = 'published';

update ontology.versions set status = 'published', published_at = now()
 where version = '0.4.0';

commit;
