-- 0189 — Apple's genre tree, as it answered on 2026-08-15.
--
-- The data half of `0188`. Fifty-six genres, unioned across all 167 storefronts
-- and asked in English, each carrying Apple's own id and the parent Apple
-- states. Generated by `tools/apple_genres.py` and pasted verbatim rather than
-- fetched at migration time: a migration that reaches the network cannot be
-- replayed, and CI has no developer token.
--
-- **The normalised form is Python's**, computed by `normalize_text` before the
-- rows were written here. SQL cannot reproduce that fold, and `0184` is what it
-- costs when the stored form and the computed one differ.
--
-- Twenty-six parent to `hub:music` because Apple files them directly under
-- Music; eleven more because Apple names a parent (`1262` Indian, `1122`
-- Brazilian) that it exposes nowhere; nineteen carry a real parent from the
-- tree — `K-Pop -> Pop`, `Afrobeats -> African`, `Metal -> Rock`.

begin;

do $$
declare
  receipt  jsonb;
  minted   integer;
  linked   integer;
  floating integer;
  missing  integer;
begin
  receipt := semantic_private.mint_genres_from_catalogue($genres$
[
 {
  "external_id": "2",
  "payload_hash": "27756e4587543210d87dd2591e48a309db211470290d789c7f5f96bba15f872d",
  "name": "Blues",
  "normalized": "blues",
  "parent_id": "34"
 },
 {
  "external_id": "4",
  "payload_hash": "fcf6ac54ca6e67b8aa08d0bc27787d3e30f87a8e38d9ccc5c81ce1d32dd6bf9b",
  "name": "Children’s Music",
  "normalized": "children s music",
  "parent_id": "34"
 },
 {
  "external_id": "5",
  "payload_hash": "a4eb68de4131d1cd1fd523ea9017edd781ad7db725875cdedb57c769c67d31b9",
  "name": "Classical",
  "normalized": "classical",
  "parent_id": "34"
 },
 {
  "external_id": "6",
  "payload_hash": "402fbf951066e272dc1786cc979e4f8a8ec07ed755cce3e2324730ed77a3b658",
  "name": "Country",
  "normalized": "country",
  "parent_id": "34"
 },
 {
  "external_id": "7",
  "payload_hash": "eb2af3f29988d74ab1c5beb33ab6793d5006c6e8fe6dd7e5da88c3f3c2b81d3f",
  "name": "Electronic",
  "normalized": "electronic",
  "parent_id": "34"
 },
 {
  "external_id": "8",
  "payload_hash": "da2d89b97fee9a2dc226c02807dfc1d61c9d0d999202f6a16b296f9837da2a00",
  "name": "Christmas",
  "normalized": "christmas",
  "parent_id": "34"
 },
 {
  "external_id": "10",
  "payload_hash": "8d151fdd602de8b78b7fd27731270198efcd4ac8159e41e894f715c6c759eb1b",
  "name": "Singer/Songwriter",
  "normalized": "singer songwriter",
  "parent_id": "34"
 },
 {
  "external_id": "11",
  "payload_hash": "27921b793de6ea7955b23f703c4fa32346462245264652a42a2a2ef6bf5528d1",
  "name": "Jazz",
  "normalized": "jazz",
  "parent_id": "34"
 },
 {
  "external_id": "12",
  "payload_hash": "a052544268bd17e21d863292a3ff75fd08b503a2ebef53b9764406fb32293f98",
  "name": "Latin",
  "normalized": "latin",
  "parent_id": "34"
 },
 {
  "external_id": "14",
  "payload_hash": "637eaea0faf7eb2d0f8e75781614731b5bdab22de36004fa8df049319e7c7318",
  "name": "Pop",
  "normalized": "pop",
  "parent_id": "34"
 },
 {
  "external_id": "15",
  "payload_hash": "7bb536f13289e0603a2a9cd56f6abcd3c1241be1eb567ea581ce7c33372cbb4a",
  "name": "R&B/Soul",
  "normalized": "r b soul",
  "parent_id": "34"
 },
 {
  "external_id": "16",
  "payload_hash": "96d6045c1b6525fa48ef2bb667b937996510066429839a499905795c8229a75b",
  "name": "Soundtrack",
  "normalized": "soundtrack",
  "parent_id": "34"
 },
 {
  "external_id": "17",
  "payload_hash": "5fad77bbffb6ed036d176144e7131c71725b62bf598f14cde84840d22125e84f",
  "name": "Dance",
  "normalized": "dance",
  "parent_id": "34"
 },
 {
  "external_id": "18",
  "payload_hash": "e8afe1f71b546e50ad27d10acf37d4cac88298997470143eb17a85e7b2e9ad26",
  "name": "Hip-Hop/Rap",
  "normalized": "hip hop rap",
  "parent_id": "34"
 },
 {
  "external_id": "19",
  "payload_hash": "734cd5e7680e9f12c76601fd8b931ab08eab30a5dda2b4d193785266efb5c7ac",
  "name": "Worldwide",
  "normalized": "worldwide",
  "parent_id": "34"
 },
 {
  "external_id": "20",
  "payload_hash": "8cca2685add5bdc419ba55227960cf2a5a0c32948ca4d8ef42636f69758d518e",
  "name": "Alternative",
  "normalized": "alternative",
  "parent_id": "34"
 },
 {
  "external_id": "21",
  "payload_hash": "def1a1bfe88cb4ec9253522d349f3e5aa516ccd4163532198fa3b0c2d33e1209",
  "name": "Rock",
  "normalized": "rock",
  "parent_id": "34"
 },
 {
  "external_id": "22",
  "payload_hash": "8553efcbc9e7337f10c255893c22b6354dc00601a9b216ea87abec0ee059d7c6",
  "name": "Christian",
  "normalized": "christian",
  "parent_id": "34"
 },
 {
  "external_id": "24",
  "payload_hash": "1ad99a905b29e4ced19adcda48504fd44d1942002959c4a2c7828cf6b411f740",
  "name": "Reggae",
  "normalized": "reggae",
  "parent_id": "34"
 },
 {
  "external_id": "27",
  "payload_hash": "8b3e058a1eb1684b9cfabf5160b42215a6ea1aed70933e507f4ed888777dac58",
  "name": "J-Pop",
  "normalized": "j pop",
  "parent_id": "34"
 },
 {
  "external_id": "28",
  "payload_hash": "8a52c104dd2af38d469737daff7ead9ce352b56d8ba02c2bee7b231066f65c2b",
  "name": "Enka",
  "normalized": "enka",
  "parent_id": "34"
 },
 {
  "external_id": "29",
  "payload_hash": "bc1cc06d6cc20e9c712b17344d751e4956ead0b01e76bfc4e9b2fc4b03ee81ba",
  "name": "Anime",
  "normalized": "anime",
  "parent_id": "34"
 },
 {
  "external_id": "30",
  "payload_hash": "8aff258df80eff5c4a3458bbd7245199e2efcee86443df49502b868abee696d7",
  "name": "Kayokyoku",
  "normalized": "kayokyoku",
  "parent_id": "34"
 },
 {
  "external_id": "42",
  "payload_hash": "756e2e75b82b2fae59ceeb394eb7a3c71b96c1e2934343334e837a230d0308b5",
  "name": "Amapiano",
  "normalized": "amapiano",
  "parent_id": "1203"
 },
 {
  "external_id": "51",
  "payload_hash": "1288a8627d745c0ac2134fbc3e5ee66f1b434dc033243b5f942af8c45507e0ea",
  "name": "K-Pop",
  "normalized": "k pop",
  "parent_id": "14"
 },
 {
  "external_id": "1004",
  "payload_hash": "e12d9401ad3f4e8bf20f802619d9170ab48996b80b658536652a65e281d9c78f",
  "name": "Indie Rock",
  "normalized": "indie rock",
  "parent_id": "20"
 },
 {
  "external_id": "1006",
  "payload_hash": "f062bfb29875800211b431efe862d7c52a3016999c2e9caa280bfaa39aa2dbb8",
  "name": "Punk",
  "normalized": "punk",
  "parent_id": "20"
 },
 {
  "external_id": "1034",
  "payload_hash": "b965af15e6bd95575ffb6a045aa99efedf04714430a6813dbb1a4f4dc46d73e3",
  "name": "Americana",
  "normalized": "americana",
  "parent_id": "6"
 },
 {
  "external_id": "1101",
  "payload_hash": "03f1bd515ddfda35899f284251399b5601c6d1b2b4eb66237a2a550364b7f98c",
  "name": "Gospel",
  "normalized": "gospel",
  "parent_id": "22"
 },
 {
  "external_id": "1119",
  "payload_hash": "eda48b53cfb386b88c7c0c635c6f4ba7adb6a8fb1698ed8dcb6d139ea261bcb1",
  "name": "Latin Urban",
  "normalized": "latin urban",
  "parent_id": "12"
 },
 {
  "external_id": "1121",
  "payload_hash": "5908bbcdf9a9023aa89184b0bde5429f2094904439cecae4b14920d0bc0794db",
  "name": "Alternative and Latin Rock",
  "normalized": "alternative and latin rock",
  "parent_id": "12"
 },
 {
  "external_id": "1123",
  "payload_hash": "69689c797387a5c5f8beda1217c41632d0a6318acdddc3b21ff5c355a5d6ed21",
  "name": "Regional Mexican",
  "normalized": "regional mexican",
  "parent_id": "12"
 },
 {
  "external_id": "1143",
  "payload_hash": "ca2b826a935bd9e0b2a5892f9a1f597a6c71e4c43f2357cfbcd190727799e775",
  "name": "Soul",
  "normalized": "soul",
  "parent_id": "15"
 },
 {
  "external_id": "1152",
  "payload_hash": "b0f514f7b8e5f06a448b68ae81d8669cce225509d3472e3cd52a72821a2c227f",
  "name": "Hard Rock",
  "normalized": "hard rock",
  "parent_id": "21"
 },
 {
  "external_id": "1153",
  "payload_hash": "4127ba3b9b025f381c32f4bed870968015cda230c43be4f95ba000e5aea6853b",
  "name": "Metal",
  "normalized": "metal",
  "parent_id": "21"
 },
 {
  "external_id": "1185",
  "payload_hash": "16eab3c2f0fec0cd2f97ff8a37891f3f84aa14107c816acdfe16ade4ef8ac07a",
  "name": "Indian Pop",
  "normalized": "indian pop",
  "parent_id": "1262"
 },
 {
  "external_id": "1203",
  "payload_hash": "a3a0a330345d7dd19b7823a521c4a0a7ef561f3c7482b8d317efa17448a22135",
  "name": "African",
  "normalized": "african",
  "parent_id": "34"
 },
 {
  "external_id": "1221",
  "payload_hash": "52266e711b99f1ca286fbd72e01991f039374d7954e09ddd26463cd4dea7988b",
  "name": "Bossa Nova",
  "normalized": "bossa nova",
  "parent_id": "1122"
 },
 {
  "external_id": "1223",
  "payload_hash": "547260280eac38caafbb5302db9efb27a4dec2dc080dbb20e89409e691095ab4",
  "name": "Forró",
  "normalized": "forró",
  "parent_id": "1122"
 },
 {
  "external_id": "1225",
  "payload_hash": "09598cbba9c16b9cdeba09b46c8d86ca321d23627be42906662c239b0f3b5ac5",
  "name": "MPB",
  "normalized": "mpb",
  "parent_id": "1122"
 },
 {
  "external_id": "1227",
  "payload_hash": "f6afc5e5a01ed618ba5cb53d10341cf0afd399e1c5f14b891c0dc6ef2d71dd52",
  "name": "Samba",
  "normalized": "samba",
  "parent_id": "1122"
 },
 {
  "external_id": "1228",
  "payload_hash": "5665e2feb7b6b8207b19afb17774d8c791cd45e348d63a9fef449aceeb1e32c6",
  "name": "Sertanejo",
  "normalized": "sertanejo",
  "parent_id": "1122"
 },
 {
  "external_id": "1229",
  "payload_hash": "d7d22d00f051f976a55caafd2a4a3558602d2bad4a6239443cc3add03391c701",
  "name": "Baile Funk",
  "normalized": "baile funk",
  "parent_id": "1122"
 },
 {
  "external_id": "1250",
  "payload_hash": "93b3d7f65dea5344bf7cb2fd475b09af107c008a9cc1b41883507b35b3b7e53f",
  "name": "C-Pop",
  "normalized": "c pop",
  "parent_id": "14"
 },
 {
  "external_id": "1251",
  "payload_hash": "3bf9e229464a7a4d31637981091f5562504d56167d4be7dd6d991d18f693cba7",
  "name": "Cantopop",
  "normalized": "cantopop",
  "parent_id": "14"
 },
 {
  "external_id": "1253",
  "payload_hash": "7cf211f6c5dea2d1af69c9f83a52fd54358a595312273bc14cdf630f4096e6fd",
  "name": "Mandopop",
  "normalized": "mandopop",
  "parent_id": "14"
 },
 {
  "external_id": "1263",
  "payload_hash": "336bd1444eaf2192fffdf1642f06e00efdbea6271dbb2232be9e43a86eb344c5",
  "name": "Bollywood",
  "normalized": "bollywood",
  "parent_id": "1262"
 },
 {
  "external_id": "1264",
  "payload_hash": "db779d087dbbaa7dce9bd16212432888c128a708f6f46141a437d7853eb824d1",
  "name": "Tamil",
  "normalized": "tamil",
  "parent_id": "1266"
 },
 {
  "external_id": "1265",
  "payload_hash": "3b501f124653890191cbf6dfa39475a4d4ac5305e2120b2d55aa71754c9746db",
  "name": "Telugu",
  "normalized": "telugu",
  "parent_id": "1266"
 },
 {
  "external_id": "1266",
  "payload_hash": "6c8328c7af927abc63fbadfed8ce83f94dd22e0fe7f4f3ff3480d395baef11d5",
  "name": "Regional Indian",
  "normalized": "regional indian",
  "parent_id": "1262"
 },
 {
  "external_id": "1267",
  "payload_hash": "563cad984708c354ebcb082806c073c290573345ecf0a16fa4f4e6f65b78d274",
  "name": "Devotional & Spiritual",
  "normalized": "devotional spiritual",
  "parent_id": "1262"
 },
 {
  "external_id": "1269",
  "payload_hash": "0cc1fbe6ec4444acf036f6f58a09fc7001c567262ed6a25cbf389e3377ecd9b8",
  "name": "Indian Classical",
  "normalized": "indian classical",
  "parent_id": "1262"
 },
 {
  "external_id": "1281",
  "payload_hash": "fff6ab22b443ee642a99365e5d7d096219fffda808581d850a7643ca9889035e",
  "name": "Afrikaans",
  "normalized": "afrikaans",
  "parent_id": "1203"
 },
 {
  "external_id": "100051",
  "payload_hash": "449c807d0eead3aa1cdc43a9beb70a7f012e2b22d4fe2a9616f22d7fa73db3ec",
  "name": "Afrobeats",
  "normalized": "afrobeats",
  "parent_id": "1203"
 },
 {
  "external_id": "50000064",
  "payload_hash": "165fa7b4e7ebd8bc8f9a37a21acf098ba28f51a810e601bcddff90b0efbc17a0",
  "name": "Musique francophone",
  "normalized": "musique francophone",
  "parent_id": "34"
 },
 {
  "external_id": "50000066",
  "payload_hash": "b1761e7e36b6e6d92fba51b2c3c9b023d823e490484f3ed85d95929dc8ef4a5a",
  "name": "German Pop",
  "normalized": "german pop",
  "parent_id": "34"
 }
]
$genres$::jsonb);

  raise notice '0189: %', receipt;

  if coalesce(receipt ->> 'published', 'false') <> 'true' then
    raise exception '0189: nothing was published — receipt %', receipt;
  end if;

  minted := (receipt ->> 'minted')::integer;
  linked := (receipt ->> 'linked')::integer;
  if minted + linked <> 56 then
    raise exception '0189: expected 56 genres accounted for, got % minted + % linked',
      minted, linked;
  end if;

  -- **No floating nodes.** A minted genre with no `broader` edge blocks as null
  -- and its children land under "Other", which is the defect this exists to
  -- remove rather than to relocate.
  select count(*) into floating
    from ontology.concepts c
    join ontology.versions v on v.status = 'published'
    join ontology.concept_revisions r
      on r.concept_id = c.id and r.ontology_version_id = v.id and r.status = 'active'
   where c.concept_key like 'genre:apple_%'
     and not exists (
       select 1 from ontology.concept_edges e
        where e.subject_concept_id = c.id
          and e.ontology_version_id = v.id
          and e.predicate_key = 'broader'
          and e.status = 'active');
  if floating <> 0 then
    raise exception '0189: % minted genre(s) have no parent', floating;
  end if;

  -- The four the owner asked about, and the two that were the whole point:
  -- every one must now be reachable from a stated genre string.
  select count(*) into missing
    from (values ('afrobeats'), ('bollywood'), ('indian pop'), ('j pop'),
                 ('mandopop'), ('k pop'), ('latin'), ('indie rock')) as wanted(normalized)
   where not exists (
     select 1
       from ontology.concept_labels l
       join ontology.versions v on v.id = l.ontology_version_id and v.status = 'published'
       join ontology.concept_revisions r
         on r.ontology_version_id = v.id and r.concept_id = l.concept_id
      where l.normalized_label = wanted.normalized
        and l.status = 'active' and r.status = 'active'
        and r.concept_kind = 'genre');
  if missing <> 0 then
    raise exception '0189: % of the named genres still resolve to nothing', missing;
  end if;
end;
$$;

commit;
