-- 0323 — a private diary is not vocabulary.
--
-- **The RIS lane sent every calendar row to the model.** The AWS path runs
-- `written_ontology.calendar_semantics` and excludes an event unless
-- positively recognised — the allowlist is the design, and it promotes 5 of
-- 101. The testing lane was licensed to bypass the privacy *projection* on the
-- owner's own data; it bypassed the *allowlist* too, which was never the
-- intent.
--
-- The result: 799 terms whose only evidence is a private
-- calendar entered `presumed_terms`, a table with **no `user_id`** and
-- therefore shared across every account. 165 of them are typed as a
-- person, a group or an organization — colleagues, doctors, classmates — and
-- fifteen are email addresses. Those people are not users of this app.
--
-- **Redacted, not hidden, and not deleted.** Leaving the label and refusing the
-- card keeps the copy nobody can see while removing the one they could, which
-- this project already names as the worse of the two arrangements. And
-- `presumed_terms_no_delete` stays: the vault's own erasure redacts, and a row
-- that vanished would take with it the record that it was ever here.
--
-- **Scoped by lane, never by pattern.** Which source attested a term is a fact;
-- a regex over names would be guessing which strings look like people. A term a
-- music or video lane also saw is untouched — this is about evidence, not
-- spelling.

alter table semantic_private.presumed_terms
  add column if not exists excluded_reason text
    check (excluded_reason is null or excluded_reason in (
      -- A closed vocabulary from the start. A reason nobody can name is a
      -- reason nobody can lift, and this column decides what is never shown.
      'private_calendar'));

comment on column semantic_private.presumed_terms.excluded_reason is
  'Why this term may never become a card. Null is the normal case. Set by '
  '0323 for terms attested only by a private calendar; a term that later '
  'earns evidence from another lane may have it lifted, per term, by hand.';

do $$
declare
  redacted integer := 0;
  hidden integer := 0;
  n integer;
begin

  update semantic_private.presumed_terms pt
     set normalized_label = 'redacted:' || pt.id::text, canonical_label = 'redacted', english_label = null, original_label = null, excluded_reason = 'private_calendar'
    from (values
    ('(corq) smith college', 'person'),
    ('1499712573ztm@gmail.com', 'person'),
    ('abdulfatai abdulkareem', 'person'),
    ('agatha eleojo onuche', 'person'),
    ('alexander mike', 'person'),
    ('amanda', 'person'),
    ('amanjot', 'person'),
    ('annamaria scizmadia', 'person'),
    ('antonia caba', 'person'),
    ('apple inc.', 'organization'),
    ('aspen woods', 'group'),
    ('assuaged foundation', 'organization'),
    ('asutin peterson', 'person'),
    ('atsuko takahashi', 'person'),
    ('axs', 'organization'),
    ('axs', 'person'),
    ('bank of america', 'organization'),
    ('becky von trapp', 'person'),
    ('bi xinran', 'person'),
    ('boa', 'person'),
    ('caesar mitchell', 'person'),
    ('calendar', 'organization'),
    ('calendar', 'person'),
    ('camille', 'person'),
    ('caroline', 'person'),
    ('charlotte-san', 'person'),
    ('chen lan', 'person'),
    ('chioma', 'person'),
    ('chizzy', 'person'),
    ('cinemark', 'organization'),
    ('cinemark buckland hills', 'organization'),
    ('cirt-info@smith.edu', 'person'),
    ('claire seely', 'person'),
    ('dan jonson', 'person'),
    ('david', 'person'),
    ('david lincoln', 'person'),
    ('david mok', 'person'),
    ('davidmok1998@gmail.com', 'person'),
    ('davio''s', 'organization'),
    ('deborah', 'person'),
    ('doshisha university', 'organization'),
    ('enterprise rent-a-car', 'organization'),
    ('eva lefkowitz', 'person'),
    ('filling in liang lu', 'person'),
    ('gao le yi', 'person'),
    ('glendale express hotel los angeles', 'organization'),
    ('gmail', 'organization'),
    ('gmail', 'person'),
    ('gongzuo', 'person'),
    ('grace borne', 'person'),
    ('gre', 'group'),
    ('gre', 'organization'),
    ('gre', 'person'),
    ('greg', 'person'),
    ('gtdouub d', 'person'),
    ('hannah james', 'person'),
    ('herzog', 'person'),
    ('hesi', 'person'),
    ('hilton miami downtown', 'organization'),
    ('icloud', 'organization'),
    ('icloud', 'person'),
    ('individual', 'person'),
    ('isac tromp', 'person'),
    ('ivanova, miglena yordanova', 'person'),
    ('j.c. elizabeth', 'person'),
    ('jalschech@smith.edu', 'person'),
    ('james miller', 'person'),
    ('james voyage and tianmei zhu', 'person'),
    ('jc leo smith', 'person'),
    ('jc peter', 'person'),
    ('jc sara eddy', 'person'),
    ('jchen.therapy@gmail.com', 'person'),
    ('jeonghwa', 'person'),
    ('jetblue', 'organization'),
    ('jingyi san', 'person'),
    ('jonathan', 'person'),
    ('jonathan pruett', 'person'),
    ('kang, yi', 'person'),
    ('kari', 'person'),
    ('kelsey hammerman', 'person'),
    ('kian', 'person'),
    ('kimberly kono', 'person'),
    ('kmasimbi@smith.edu', 'person'),
    ('kong fu liang lu', 'person'),
    ('krasi', 'organization'),
    ('laura money', 'person'),
    ('lazarus center for career development', 'organization'),
    ('lei laoshi', 'person'),
    ('lexi larkin', 'person'),
    ('li yuyang', 'person'),
    ('liang lu', 'person'),
    ('liberal arts', 'group'),
    ('madison mas', 'person'),
    ('mahmed@smith.edu', 'person'),
    ('margaret lamb', 'person'),
    ('marsha', 'person'),
    ('marsha house', 'person'),
    ('marsha pruett', 'person'),
    ('maxwell paul', 'person'),
    ('mcdonnell prep', 'organization'),
    ('meeting', 'group'),
    ('meeting', 'person'),
    ('melissa mavers', 'person'),
    ('meredith', 'person'),
    ('millman', 'person'),
    ('musiek', 'person'),
    ('mxgbuleke', 'person'),
    ('myssie', 'person'),
    ('naila writing', 'person'),
    ('nancy pelosi', 'person'),
    ('nayoung', 'person'),
    ('nicholas james', 'person'),
    ('nxarrh bssykw', 'person'),
    ('onuche agatha eleojo', 'person'),
    ('other', 'person'),
    ('outlook', 'person'),
    ('patricia dibartolo', 'person'),
    ('peiyang liu', 'person'),
    ('personal', 'person'),
    ('prof oh', 'person'),
    ('prof. pruett', 'person'),
    ('professor', 'person'),
    ('psy', 'person'),
    ('quest diagnostics', 'organization'),
    ('rachael', 'person'),
    ('raven chapin', 'person'),
    ('raven-san', 'person'),
    ('regency b', 'organization'),
    ('rita robert', 'person'),
    ('roisin advising', 'person'),
    ('sabin reed', 'person'),
    ('saint louis university', 'organization'),
    ('salvo', 'person'),
    ('salvo dominguez', 'person'),
    ('sarah klein', 'person'),
    ('schneider electric', 'organization'),
    ('shannon audley', 'person'),
    ('shemo and tianmei zhu', 'person'),
    ('shen tailai', 'person'),
    ('shinran-san', 'person'),
    ('sigma xi', 'organization'),
    ('spinelli@smith.edu', 'person'),
    ('subscribed calendars', 'group'),
    ('suburban subaru', 'organization'),
    ('szhu', 'person'),
    ('szhu smith', 'person'),
    ('szhu@smith.edu', 'person'),
    ('tianmei', 'person'),
    ('tianmei and megi', 'person'),
    ('tianmei-san', 'person'),
    ('trader joe', 'person'),
    ('tt beauty salon', 'organization'),
    ('united nations visitors centre', 'organization'),
    ('university of georgia center for continuing education & hotel, 1197 s lumpkin st, athens, ga 30602, usa', 'organization'),
    ('university of massachusetts amherst', 'organization'),
    ('unknown organizer', 'person'),
    ('vldoz mtedt', 'person'),
    ('wang xiying', 'person'),
    ('xbi@smith.edu', 'person'),
    ('ysfev wjmwu', 'person'),
    ('zhang', 'person'),
    ('zoe and tianmei zhu', 'person'),
    ('个人', 'person'),
    ('日曆', 'person'),
    ('玫鹏裘', 'person')
  ) as excluded_term(normalized_label, family)
   where pt.normalized_label = excluded_term.normalized_label
     and pt.family = excluded_term.family
     and pt.excluded_reason is distinct from 'private_calendar';
  get diagnostics n = row_count;
  redacted := redacted + n;
  update semantic_private.presumed_terms pt
     set excluded_reason = 'private_calendar'
    from (values
    ('08/11 aou pa meeting', 'event'),
    ('1 week post op', 'event'),
    ('1 week post-op check in', 'event'),
    ('100 elm st, northampton, ma 01063, united states', 'work'),
    ('101c - level 1- minneapolis convention center', 'franchise'),
    ('101fg - level 1- minneapolis convention center', 'event'),
    ('10863307306582', 'work'),
    ('10f lab meeting', 'event'),
    ('124: newcomers welcome at grand ballroom e/f/g/h/i/j/k', 'event'),
    ('127b: coparenting (poster session 1)', 'event'),
    ('127h: dating (poster session 1)', 'event'),
    ('15 east 31st street, new york, ny 10016', 'event'),
    ('15 east 31st street, new york, ny 10016', 'work'),
    ('2 weeks post-op check in', 'event'),
    ('209ab - level 2 - minneapolis convention center', 'event'),
    ('210ab - level 2 - minneapolis convention center', 'event'),
    ('211b - level 2 - minneapolis convention center', 'event'),
    ('211c - level 2 - minneapolis convention center', 'event'),
    ('247 862 4376', 'work'),
    ('295 e dougherty st, athens, ga 30601, usa', 'work'),
    ('2d', 'franchise'),
    ('3565 u.s. 1, princeton, nj 08540, usa', 'work'),
    ('358 learning conferences', 'event'),
    ('39 buckland street', 'album'),
    ('40 trumbull rd', 'work'),
    ('440 memorial drive, chicopee, ma 01020, united states of america', 'work'),
    ('5959 west century boulevard, los angeles, ca 90045, usa', 'work'),
    ('5f c', 'album'),
    ('5f denver&houston', 'album'),
    ('5f e', 'album'),
    ('5f kansas city', 'franchise'),
    ('5f scottdale', 'album'),
    ('5th floor a&b', 'album'),
    ('6 in 1 combo tour: voodoo, witches, ghosts, murder, pirates, & vampires with tour orleans', 'event'),
    ('714 646 8798', 'work'),
    ('7f salon i', 'album'),
    ('7f salon i', 'work'),
    ('7f salon i and ii', 'franchise'),
    ('7f salon i&ii', 'franchise'),
    ('7th floor, salon i', 'event'),
    ('986 5707 8736', 'event'),
    ('abby meeting', 'event'),
    ('abstract ddl', 'work'),
    ('account servicing', 'work'),
    ('acculturation and psychosocial outcomes: importance of methods & context', 'work'),
    ('advanced genetics weekly discussion', 'event'),
    ('all of us meeting 03/10', 'event'),
    ('alumnae gymnasium 307', 'work'),
    ('amanda meeting', 'event'),
    ('amc plainville 20', 'event'),
    ('amc plainville 20, 220 new britain avenue, plainville, ct 06062', 'work'),
    ('anna meeting', 'event'),
    ('anna ps', 'work'),
    ('apex 91', 'work'),
    ('applications of epigenetic aging clocks and methylation risk scores using whole genome methylation profiling', 'work'),
    ('appointment @ studs', 'event'),
    ('appointment at suburban subaru', 'event'),
    ('appointment at tt beauty salon', 'event'),
    ('appointment with jan', 'event'),
    ('appointment with jan', 'work'),
    ('appointment with sika berger', 'work'),
    ('appointment with suburban subaru', 'work'),
    ('appoitntment with suburban subaru', 'event'),
    ('artificial intelligence chatbots and assistants in family life, love, and parenting at regency b', 'event'),
    ('assuaged foundation pre-internship meeting q&as', 'event'),
    ('atlanta atl', 'album'),
    ('atlanta atl', 'franchise'),
    ('atlanta atl', 'work'),
    ('augh birthday', 'event'),
    ('austin aus', 'event'),
    ('austin aus', 'work'),
    ('back bay - 91 newbury st, boston, ma 02116', 'event'),
    ('baltimore', 'franchise'),
    ('baltimore md', 'work'),
    ('bank of america appointment', 'event'),
    ('banking', 'event'),
    ('banking', 'work'),
    ('banquet & auction', 'event'),
    ('bass 103', 'album'),
    ('bass 103', 'franchise'),
    ('bass 204', 'album'),
    ('bass 306', 'work'),
    ('bass 307', 'album'),
    ('bass 307', 'work'),
    ('bass 308', 'franchise'),
    ('bass 308', 'work'),
    ('bass 414', 'album'),
    ('bass 414', 'work'),
    ('bass hall 407', 'album'),
    ('birthday', 'event'),
    ('birthdays', 'franchise'),
    ('biweekly all-community meeting', 'event'),
    ('black lamb', 'work'),
    ('blades of the guardians', 'work'),
    ('boch center wang theatre', 'work'),
    ('boch center wang theatre, boston, ma', 'franchise'),
    ('bombay royale', 'franchise'),
    ('bos', 'franchise'),
    ('boston', 'franchise'),
    ('boston bos', 'franchise'),
    ('botanic garden by the lannin fountain', 'work'),
    ('break', 'work'),
    ('breakfast', 'event'),
    ('broadleaf boulevard apartments', 'album'),
    ('broadleaf boulevard apartments', 'work'),
    ('broadloaf', 'work'),
    ('buddha''s birthday', 'event'),
    ('bus 120', 'work'),
    ('bus to boston', 'event'),
    ('bus to boston', 'work'),
    ('bus to boston (south station)', 'event'),
    ('bus to boston (south station)', 'work'),
    ('bus to hartford', 'work'),
    ('bus to new york', 'work'),
    ('business, finance, engineering & technology', 'work'),
    ('calendar', 'event'),
    ('calendar', 'franchise'),
    ('calendar', 'work'),
    ('campus center café', 'work'),
    ('campus tour', 'event'),
    ('caring for succulents', 'activity'),
    ('carlie meeting', 'event'),
    ('caroline econ ta meeting', 'event'),
    ('caroline meeting', 'event'),
    ('caroline ps', 'work'),
    ('carroll room of the campus center', 'work'),
    ('casa tortugas boutique hotel', 'franchise'),
    ('cc 205', 'event'),
    ('cc psy meeting', 'event'),
    ('cd', 'album'),
    ('cenote xunáan', 'franchise'),
    ('charlie meeting', 'event'),
    ('charlotte clt', 'event'),
    ('charlotte''s birthday', 'event'),
    ('chase house meeting', 'event'),
    ('chase meeting', 'event'),
    ('chase sub-free ddl', 'work'),
    ('chase zoom meeting', 'event'),
    ('check out shuttle pick up', 'event'),
    ('chi guo', 'work'),
    ('chicago hotel collection', 'franchise'),
    ('chicago ord', 'franchise'),
    ('chichén itzá', 'franchise'),
    ('chongliang meeting', 'event'),
    ('christmas day', 'event'),
    ('chuckett wedding + reception', 'event'),
    ('chung yeung festival', 'event'),
    ('cinemark buckland hills 18 xd and imax', 'franchise'),
    ('cinemark buckland hills 18 xd and imax, 99 redstone rd manchester, ct 06042', 'event'),
    ('circadian rhythm bi-weekly zoom meeting', 'event'),
    ('circadian rhythm meeting', 'event'),
    ('clark hall', 'franchise'),
    ('clemens oh', 'work'),
    ('cog midterm', 'event'),
    ('cog oh', 'work'),
    ('cog wikicog outline due', 'work'),
    ('comfort inn & suites zion park area', 'work'),
    ('computational genetics last day', 'event'),
    ('confocal training', 'event'),
    ('confocal training', 'work'),
    ('connect the dots: showcasing your experience & skills in any interview', 'event'),
    ('connect the dots: showcasing your experience & skills in any interview', 'work'),
    ('consulate visa', 'work'),
    ('consultation with jan', 'event'),
    ('copaf', 'event'),
    ('copaf', 'franchise'),
    ('copaf', 'work'),
    ('copaf meeting', 'event'),
    ('copaf virtual check in', 'event'),
    ('copafs', 'event'),
    ('copafs', 'work'),
    ('copafs data', 'work'),
    ('copafs mtg', 'event'),
    ('couch pickup', 'event'),
    ('course milestones, funding, and expectations', 'work'),
    ('courtyard by marriott los angeles monterey park', 'franchise'),
    ('covid-19 testing', 'event'),
    ('cpt info session', 'event'),
    ('cpt q&a session', 'event'),
    ('csc major presentation', 'event'),
    ('ctexcel recharge restore dual number', 'work'),
    ('cutchins on site', 'event'),
    ('cv & research statement', 'work'),
    ('cvi.che 105 downtown', 'event'),
    ('cz survey', 'work'),
    ('dads matter', 'event'),
    ('dalian dlc', 'franchise'),
    ('data blitz', 'event'),
    ('david and dr. salvo', 'franchise'),
    ('davio''s - seaport', 'event'),
    ('davis ballroom', 'franchise'),
    ('davis ballroom', 'work'),
    ('davis lawn/tent', 'work'),
    ('day 3 - spatial biomarkers for translational research', 'event'),
    ('day after mid-autumn festival', 'event'),
    ('day following buddha''s birthday', 'event'),
    ('ddf55.com', 'work'),
    ('ddf55.com禁可‍♀/? dfcg019 7', 'album'),
    ('demon slayer: kimetsu no yaiba', 'franchise'),
    ('departing chicago, il (ord)', 'event'),
    ('departing hartford, ct (bdl)', 'event'),
    ('dibartolo lab', 'franchise'),
    ('dibartolo lab meetings', 'event'),
    ('dibartolo lab meetings', 'work'),
    ('dinner', 'event'),
    ('dl 552', 'franchise'),
    ('dl 5836', 'event'),
    ('dl 812', 'event'),
    ('dl 812', 'work'),
    ('dor exam', 'event'),
    ('doubletree by hilton hotel boston - downtown', 'event'),
    ('doubletree by hilton hotel boston - downtown, boston', 'event'),
    ('dr. cao''s office', 'event'),
    ('draft back', 'work'),
    ('dragon boat festival', 'event'),
    ('driving', 'activity'),
    ('driving practice', 'activity'),
    ('drop-in with claire seely', 'event'),
    ('due', 'work'),
    ('dwc', 'event'),
    ('dwc&smith', 'franchise'),
    ('dwc&smith contract class session 1', 'event'),
    ('eal 244', 'work'),
    ('eal 244 museum', 'work'),
    ('eal 244 去做纸', 'work'),
    ('eal 253', 'work'),
    ('eal 253 pre', 'work'),
    ('eal 253 screening', 'event'),
    ('eal 253 team working', 'event'),
    ('eal 253 zoom', 'work'),
    ('eal dq', 'work'),
    ('easter monday', 'event'),
    ('easter sunday', 'work'),
    ('eat medicine start', 'work'),
    ('eco', 'work'),
    ('eco 203', 'work'),
    ('eco 203+presentation', 'work'),
    ('eco 253', 'work'),
    ('eco 263', 'work'),
    ('eco 265', 'work'),
    ('eco 265 bring ps3', 'work'),
    ('eco 265 exam', 'event'),
    ('eco240', 'work'),
    ('econ ta hours', 'event'),
    ('economics commencement', 'event'),
    ('economics major presentation', 'event'),
    ('edu lab', 'work'),
    ('ejh lab meeting', 'event'),
    ('end of cohort', 'event'),
    ('engineering career fair', 'event'),
    ('evergreen ballroom', 'work'),
    ('exam 2', 'event'),
    ('exam 3', 'event'),
    ('fall 2021', 'event'),
    ('father''s day', 'event'),
    ('filling in liang lu', 'work'),
    ('filling the blank: liang lu', 'work'),
    ('final destination bloodlines', 'franchise'),
    ('final fantasy vii rebirth orchestra world tour', 'event'),
    ('final fantasy vii rebirth orchestra world tour', 'franchise'),
    ('first week massage night', 'work'),
    ('first weekday after christmas day', 'event'),
    ('flight', 'work'),
    ('flight b6 254', 'event'),
    ('flight b6187', 'event'),
    ('flight to atlanta', 'work'),
    ('flight to atlanta (dl 2697)', 'event'),
    ('flight to atlanta (nk 452)', 'event'),
    ('flight to atlanta (nk 452)', 'work'),
    ('flight to boston (aa 1457)', 'event'),
    ('flight to boston (b6 254)', 'event'),
    ('flight to boston (b6 498)', 'event'),
    ('flight to boston (ba 239)', 'event'),
    ('flight to boston (dl 552)', 'event'),
    ('flight to boston (dl 5781)', 'event'),
    ('flight to boston (jl 8)', 'event'),
    ('flight to boston (jl 8)', 'work'),
    ('flight to charlotte', 'event'),
    ('flight to charlotte', 'work'),
    ('flight to chicago (ua 1410)', 'work'),
    ('flight to chicago o''hare (aa 3042)', 'event'),
    ('flight to doha (qr 706)', 'event'),
    ('flight to frankfurt (lh 235)', 'work'),
    ('flight to hartford', 'work'),
    ('flight to hartford (b6 2086)', 'work'),
    ('flight to hartford (dl 2757)', 'event'),
    ('flight to hartford (mx 527)', 'event'),
    ('flight to hartford (mx 527)', 'work'),
    ('flight to hartford (ua 1811)', 'event'),
    ('flight to hong kong (cx 883)', 'event'),
    ('flight to hong kong (cx 883)', 'work'),
    ('flight to istanbul (tk 281)', 'event'),
    ('flight to las vegas', 'work'),
    ('flight to london (ba 168)', 'event'),
    ('flight to los angeles (aa 453)', 'event'),
    ('flight to los angeles (aa 453)', 'work'),
    ('flight to los angeles (cx 880)', 'event'),
    ('flight to los angeles (cx 880)', 'work'),
    ('flight to los angeles (dl 473)', 'event'),
    ('flight to los angeles (dl 473)', 'work'),
    ('flight to los angeles (ua 2403)', 'event'),
    ('flight to miami', 'work'),
    ('flight to nashville (ua 483)', 'event'),
    ('flight to new orleans', 'work'),
    ('flight to new york (dl 185)', 'work'),
    ('flight to newark (dl 5836)', 'event'),
    ('flight to newark (ua 334)', 'work'),
    ('flight to rome', 'work'),
    ('flight to seattle', 'work'),
    ('flight to shanghai (lx 188)', 'work'),
    ('flight to st. louis', 'work'),
    ('flight to tokyo', 'work'),
    ('flight to tokyo (jl 820)', 'work'),
    ('flight to zürich (lx 53)', 'work'),
    ('flight ua 334', 'event'),
    ('flight ua 483', 'event'),
    ('flight ua1410', 'event'),
    ('flight ua1811', 'event'),
    ('ford atrium', 'franchise'),
    ('fourth day of lunar new year', 'event'),
    ('frsc', 'event'),
    ('frsc', 'work'),
    ('frsc meeting', 'event'),
    ('fsb 106a', 'album'),
    ('fsb 111', 'album'),
    ('fsb 111/120/dean''s lounge', 'album'),
    ('fsb 307', 'album'),
    ('gift', 'work'),
    ('glendale express hotel los angeles, glendale', 'franchise'),
    ('gmail', 'franchise'),
    ('gochujang', 'culture'),
    ('good friday', 'event'),
    ('google', 'franchise'),
    ('google meet', 'event'),
    ('google meet', 'franchise'),
    ('graduate record examinations', 'work'),
    ('gre', 'franchise'),
    ('gre', 'work'),
    ('groome', 'work'),
    ('group meeting', 'event'),
    ('grove', 'work'),
    ('growing up in science panel discussion', 'event'),
    ('guang ge birthday', 'event'),
    ('guided tour - english with united nations visitors centre', 'event'),
    ('gun', 'work'),
    ('gyro''s birthday', 'event'),
    ('hampton inn boston seaport district', 'work'),
    ('hanoi house', 'franchise'),
    ('happy birthday', 'work'),
    ('happy birthday!', 'work'),
    ('harm reduction last day', 'event'),
    ('hartford bdl', 'event'),
    ('hartford bdl', 'franchise'),
    ('hartford bdl', 'work'),
    ('hartford ct', 'franchise'),
    ('hartford ct', 'work'),
    ('hartsfield-jackson atlanta international airport', 'franchise'),
    ('hatfield 205', 'album'),
    ('he xi meeting', 'event'),
    ('hello-ooyq', 'work'),
    ('hidden curriculum', 'event'),
    ('hillyer graham', 'franchise'),
    ('hils zoom', 'event'),
    ('hilton', 'franchise'),
    ('holidays in the united states', 'work'),
    ('holy saturday', 'work'),
    ('home', 'work'),
    ('hong kong', 'franchise'),
    ('hong kong holidays', 'event'),
    ('hong kong special administrative region establishment day', 'event'),
    ('hotel check-in', 'event'),
    ('hotel milano castello', 'work'),
    ('house meeting', 'event'),
    ('hpv vaccine', 'work'),
    ('ht meeting', 'event'),
    ('ht meeting with patty', 'event'),
    ('https://psu.zoom.us/j/98045300484', 'event'),
    ('https://smith.zoom.us/j/7123389797', 'event'),
    ('https://smith.zoom.us/j/95584102830', 'event'),
    ('https://smith.zoom.us/my/rosulliv', 'event'),
    ('hungry ghost festival', 'event'),
    ('hyatt house lax / century blvd', 'work'),
    ('hyatt place boston / seaport district', 'franchise'),
    ('hyatt place boston / seaport district, boston', 'franchise'),
    ('hyatt place princeton', 'event'),
    ('hyatt place princeton', 'franchise'),
    ('hyatt place princeton', 'work'),
    ('hyatt regency bellevue on seattle''s eastside', 'event'),
    ('hyatt regency bellevue on seattle''s eastside', 'work'),
    ('hyatt regency bellevue on seattle''s eastside, bellevue', 'work'),
    ('hyponatremia meeting', 'event'),
    ('i4 with kion', 'work'),
    ('icloud', 'franchise'),
    ('imax', 'franchise'),
    ('infinity castle arc', 'work'),
    ('interview', 'event'),
    ('interview', 'work'),
    ('invitation', 'work'),
    ('jacobson center', 'work'),
    ('january meeting', 'event'),
    ('jeonghwa ssn denial', 'event'),
    ('jeonghwa table pickup', 'event'),
    ('jetblue', 'franchise'),
    ('jm meeting', 'event'),
    ('jonathan and marsha', 'work'),
    ('jonathan and tianmei', 'work'),
    ('jonathan meeting', 'event'),
    ('jpn grader meeting', 'event'),
    ('jpn research', 'event'),
    ('jpn301', 'franchise'),
    ('jpn301 oral check', 'event'),
    ('juliana meeting', 'event'),
    ('kari meeting', 'event'),
    ('kc meeting', 'event'),
    ('kgsa event', 'event'),
    ('kono paper#1 meeting', 'event'),
    ('kono zoom', 'work'),
    ('korea meeting', 'event'),
    ('lab meeting', 'event'),
    ('labor economics idea pitches', 'work'),
    ('labour day', 'event'),
    ('larazus center', 'event'),
    ('las vegas las', 'franchise'),
    ('las vegas las', 'work'),
    ('laura money psy chi', 'work'),
    ('learning common', 'album'),
    ('learning conference', 'event'),
    ('learning to drive', 'activity'),
    ('lei laoshi xuanxiao', 'event'),
    ('lgbtq research', 'event'),
    ('lh 7061', 'event'),
    ('liga', 'franchise'),
    ('lobby of hotel', 'work'),
    ('london lhr', 'event'),
    ('los angeles lax', 'event'),
    ('los angeles lax', 'franchise'),
    ('los angeles lax', 'work'),
    ('lucie oh', 'work'),
    ('lunar new year''s day', 'event'),
    ('lunch by liberal arts', 'work'),
    ('lunch on your own', 'work'),
    ('luncheon', 'event'),
    ('m social hotel times square new york', 'work'),
    ('ma dinner', 'event'),
    ('madame vo', 'franchise'),
    ('madame vo nyc', 'franchise'),
    ('manchester parkade financial center at 354 middle tpke w manchester, ct', 'work'),
    ('mandarin', 'culture'),
    ('mandarin english comparison', 'work'),
    ('mandatory house closing meeting', 'event'),
    ('mandatory house meeting', 'event'),
    ('marco''s last meeting', 'work'),
    ('marsha meeting', 'event'),
    ('mathematics', 'work'),
    ('mcconnell 403', 'work'),
    ('mcconnell foyer', 'work'),
    ('mcconnell-1st floor-mcconnell 103 (30)', 'work'),
    ('measuring parenting beliefs, attitudes, and practices in the majority world', 'work'),
    ('meeting', 'event'),
    ('meeting', 'work'),
    ('meeting bass', 'work'),
    ('meeting seye doll', 'work'),
    ('meeting with albert kim', 'event'),
    ('meeting with herzog', 'event'),
    ('meeting with mac', 'event'),
    ('meeting with melissa mavers', 'event'),
    ('meeting with millman', 'event'),
    ('meeting with musiek', 'event'),
    ('meeting with ombus and david', 'event'),
    ('meeting with prof. pruett and jonathan', 'event'),
    ('meeting with professor fritz', 'event'),
    ('meeting with professor fritz', 'work'),
    ('meeting with skeath', 'event'),
    ('meeting with tianmei', 'event'),
    ('meeting with zhang', 'event'),
    ('megi', 'work'),
    ('meredith san birthday', 'event'),
    ('meta-analysis last day', 'event'),
    ('miami mia', 'album'),
    ('miami mia', 'franchise'),
    ('microsoft teams meeting', 'event'),
    ('mid-autumn festival', 'event'),
    ('milan castle hotel', 'work'),
    ('milan mxp', 'franchise'),
    ('milan mxp', 'work'),
    ('mini presentation', 'event'),
    ('minneapolis msp', 'event'),
    ('minneapolis msp', 'work'),
    ('mj exam meeting', 'event'),
    ('mock exam', 'event'),
    ('mock exam liang lu', 'event'),
    ('mock exam verbal review: liang lu', 'event'),
    ('morgan hall 204', 'album'),
    ('morgan hall 204', 'work'),
    ('mother''s day', 'event'),
    ('my jetblue trip to baltimore, md', 'event'),
    ('naila writing', 'work'),
    ('nashville bna', 'album'),
    ('nashville bna', 'franchise'),
    ('nashville international airport', 'work'),
    ('national day of the people''s republic of china', 'event'),
    ('ne zha 2', 'franchise'),
    ('neilson 108f', 'event'),
    ('neilson 108f', 'work'),
    ('new event', 'event'),
    ('new haven ct', 'event'),
    ('new haven ct', 'work'),
    ('new orleans msy', 'event'),
    ('new orleans msy', 'franchise'),
    ('new year''s day', 'event'),
    ('new year''s eve', 'event'),
    ('new york jfk', 'event'),
    ('new york jfk', 'work'),
    ('new york lga', 'franchise'),
    ('newark ewr', 'event'),
    ('newark ewr', 'franchise'),
    ('newark liberty international airport', 'franchise'),
    ('nicole''s birthday', 'event'),
    ('nk1220', 'work'),
    ('no class', 'work'),
    ('noon evacuation', 'work'),
    ('npsp mentorship', 'work'),
    ('oak hall 408', 'album'),
    ('office hours (tianmei zhu)', 'franchise'),
    ('office hours (tianmei zhu)', 'work'),
    ('one hour zoom consultation for eb1/niw/o1', 'event'),
    ('oral check', 'event'),
    ('oral check', 'work'),
    ('outline', 'work'),
    ('parenting and psychosocial adjustment in diverse sociocultural contexts', 'work'),
    ('park terrace hotel', 'work'),
    ('patricia oh with lily', 'work'),
    ('patty and camille', 'work'),
    ('patty ht meeting', 'event'),
    ('patty learning conference +问lab', 'event'),
    ('patty meeting', 'event'),
    ('patty oh', 'work'),
    ('pay-it-forward', 'event'),
    ('pcr test', 'work'),
    ('personal statements for graduate & professional school', 'work'),
    ('pet pet day', 'event'),
    ('peter pan', 'work'),
    ('pfizer second dose', 'event'),
    ('picerce 103', 'album'),
    ('pick-up: northampton; return: northampton', 'event'),
    ('pierce hall 103', 'event'),
    ('playstation 5', 'franchise'),
    ('playstation plus', 'franchise'),
    ('pole ht meeting', 'event'),
    ('pole oh', 'work'),
    ('poster', 'work'),
    ('prof. pruett meeting', 'event'),
    ('professor check', 'work'),
    ('ps workshop', 'event'),
    ('psu hdfs greg meeting', 'event'),
    ('psy 358', 'work'),
    ('psy 358 proposal due', 'event'),
    ('psy 360', 'work'),
    ('psy chi induction ceremony', 'event'),
    ('psy ddl nooish', 'work'),
    ('psy group meeting', 'event'),
    ('psy218', 'work'),
    ('psy218 discussion sheet', 'work'),
    ('psy218 no class', 'event'),
    ('psych commencement', 'event'),
    ('psychological meeting', 'event'),
    ('psychology major presentation', 'event'),
    ('pu dong pvg', 'event'),
    ('quest diagnostics - manchester 224 no main', 'event'),
    ('quest diagnostics, 224 north main street, manchester, ct', 'event'),
    ('racket 431 west 16th street, new york, ny 10011', 'work'),
    ('regalia', 'work'),
    ('regency b', 'franchise'),
    ('registration', 'event'),
    ('relax/recharge room at birch', 'event'),
    ('rent payment reminder', 'event'),
    ('reservation at bombay royale', 'event'),
    ('reservation at hanoi house', 'event'),
    ('reservation at krasi', 'event'),
    ('reservation at madame vo nyc', 'event'),
    ('reservation at take 31', 'event'),
    ('reservation at take31', 'event'),
    ('respect and rigor: strategies for culturally aware cross-cultural research', 'work'),
    ('return two books', 'event'),
    ('returning books', 'event'),
    ('road test', 'work'),
    ('road test practice', 'event'),
    ('roisin meeting', 'event'),
    ('rome fco', 'franchise'),
    ('rome fco', 'work'),
    ('room draw', 'work'),
    ('room inspection', 'work'),
    ('sabin reed 220', 'album'),
    ('sabin reed 220', 'work'),
    ('saint louis stl', 'work'),
    ('salon i', 'album'),
    ('salon i', 'franchise'),
    ('seattle sea', 'franchise'),
    ('second day of lunar new year', 'event'),
    ('second weekday after christmas day', 'event'),
    ('seelye 101', 'album'),
    ('seelye 101', 'franchise'),
    ('seelye 101', 'work'),
    ('seelye 106', 'album'),
    ('seelye 106', 'work'),
    ('seelye 109', 'franchise'),
    ('seelye 201', 'work'),
    ('seelye 301', 'work'),
    ('seelye 307', 'album'),
    ('seelye 307', 'work'),
    ('self-scheduled exam', 'event'),
    ('senior portrait', 'work'),
    ('senior spring soirée', 'event'),
    ('shanghai pudong international airport', 'franchise'),
    ('shanghai pvg', 'event'),
    ('shanghai pvg', 'franchise'),
    ('shuttle back-break', 'work'),
    ('shuttle pick up', 'work'),
    ('social event - shuttle back', 'event'),
    ('special interest draw starts', 'event'),
    ('special studies form draft', 'work'),
    ('special study form ddl', 'work'),
    ('spinelli center training', 'event'),
    ('spreadsheet meeting', 'event'),
    ('st. louis stl', 'franchise'),
    ('st. louis stl', 'work'),
    ('stay at glendale express hotel los angeles', 'event'),
    ('stay at hilton miami downtown', 'event'),
    ('stay at the chicago hotel collection magnificent mile', 'event'),
    ('stay at the chicago hotel collection magnificent mile hotel & suites', 'event'),
    ('stay: courtyard by marriott los angeles monterey park', 'event'),
    ('stay: hampton inn boston seaport district', 'work'),
    ('stay: hyatt place princeton', 'event'),
    ('stay: hyatt regency bellevue on seattle''s eastside', 'event'),
    ('stay: m social hotel times square new york', 'work'),
    ('stay: park terrace hotel', 'work'),
    ('stay: tru by hilton chicopee springfield', 'event'),
    ('stl > tp', 'work'),
    ('stop amazon prime!', 'event'),
    ('student office hour (tianmei zhu)', 'event'),
    ('student office hours', 'event'),
    ('su ddl', 'work'),
    ('suburban subaru', 'franchise'),
    ('suburban subaru', 'work'),
    ('summer surf meeting', 'event'),
    ('take 31', 'franchise'),
    ('tcrm business meeting and reception at regency b', 'event'),
    ('team meeting', 'event'),
    ('team tenure conversation', 'work'),
    ('the chicago hotel collection magnificent mile, chicago', 'franchise'),
    ('the chicago hotel collection magnificent mile, chicago', 'work'),
    ('the role of coparenting in family dynamics and infant outcomes', 'work'),
    ('thesis', 'work'),
    ('third day of lunar new year', 'event'),
    ('this day after taking medicine ends', 'work'),
    ('thompson central park new york', 'franchise'),
    ('tianmei', 'work'),
    ('tianmei & megi', 'work'),
    ('tianmei / jonathan', 'work'),
    ('tianmei and jonathan', 'franchise'),
    ('tianmei and jonathan', 'work'),
    ('tianmei jon zoom', 'event'),
    ('ticket grabbing', 'activity'),
    ('ticket scramble', 'event'),
    ('toefl ibt test', 'event'),
    ('tokyo nrt', 'event'),
    ('tokyo nrt', 'work'),
    ('tomb sweeping day', 'event'),
    ('toro indoor', 'event'),
    ('toro indoor', 'work'),
    ('tour orleans', 'franchise'),
    ('tp > stl', 'work'),
    ('train to baltimore md', 'event'),
    ('train to baltimore md', 'work'),
    ('train to hartford ct', 'work'),
    ('train to new haven ct', 'event'),
    ('train to new haven ct', 'work'),
    ('travel documents', 'work'),
    ('tru by hilton chicopee springfield', 'franchise'),
    ('tru by hilton chicopee springfield', 'work'),
    ('trunk', 'work'),
    ('trunk drop off', 'event'),
    ('trunk room stickers pick up', 'work'),
    ('tutor interview', 'work'),
    ('tutor interview (with myssie) (tianmei zhu)', 'work'),
    ('united airlines flight 1410', 'event'),
    ('united airlines flight 1811', 'event'),
    ('update na zhang', 'work'),
    ('us holidays', 'franchise'),
    ('vaha birthday', 'event'),
    ('valentine''s day', 'event'),
    ('valerie', 'work'),
    ('valladolid', 'franchise'),
    ('via san tomaso, 2, 20121 milan, milan province, italy', 'work'),
    ('vietnamese coffee workshop', 'event'),
    ('virtual check-in', 'event'),
    ('virtual event', 'event'),
    ('volunteer meeting', 'event'),
    ('voodoo', 'franchise'),
    ('washington dca', 'event'),
    ('washington dca', 'franchise'),
    ('wechat call', 'work'),
    ('welcome', 'work'),
    ('welcome reception', 'event'),
    ('wikicog', 'work'),
    ('winter break house meeting', 'event'),
    ('winter break meeting', 'event'),
    ('workshop 19', 'event'),
    ('workshop 31', 'event'),
    ('workshop 48', 'event'),
    ('workshop 5', 'event'),
    ('workshop 54 with tont packets', 'event'),
    ('workshop 67 with kian', 'event'),
    ('workshop 74 with chioma & amanjot', 'event'),
    ('wright hall 125', 'franchise'),
    ('wright hall, lewis global studies center', 'work'),
    ('writing', 'activity'),
    ('writing', 'work'),
    ('writing by xu zhiqi', 'work'),
    ('written app-interview', 'event'),
    ('yanzhen kuang', 'work'),
    ('zhonghuan outbound', 'event'),
    ('zjy birthday', 'event'),
    ('zoom', 'franchise'),
    ('zoom meeting', 'event'),
    ('zootopia 2', 'franchise'),
    ('zürich zrh', 'franchise'),
    ('先去看海报', 'work'),
    ('前往莫尔登中心站', 'event'),
    ('拿weee+带鸭舌鸡翅', 'event'),
    ('香港 hkg', 'work')
  ) as excluded_term(normalized_label, family)
   where pt.normalized_label = excluded_term.normalized_label
     and pt.family = excluded_term.family
     and pt.excluded_reason is distinct from 'private_calendar';
  get diagnostics n = row_count;
  hidden := hidden + n;

  -- Anything email- or URL-shaped, in any family and from any lane. These are
  -- contact details rather than terms whatever attested them, and the shape is
  -- not a guess about meaning — it is the thing itself.
  update semantic_private.presumed_terms
     set normalized_label = 'redacted:' || id::text,
         canonical_label = 'redacted', english_label = null,
         original_label = null, excluded_reason = 'private_calendar'
   -- **No `excluded_reason` guard here, and that is the point.** The
   -- lane-scoped blocks above mark some rows without redacting them — an
   -- event title is not personal data — so a contact-shaped label that fell
   -- in that set would already carry a reason and be skipped. Five did. This
   -- sweep is about the shape of the string, never about what has already
   -- been decided for the row.
   where normalized_label ~ '@' or normalized_label ~ '^https?://';
  get diagnostics n = row_count;
  redacted := redacted + n;

  raise notice '0323: % terms redacted, % more hidden', redacted, hidden;

  -- **Assert the state, not the count.** A replay has no dictionary, so zero is
  -- right there; what must never be true afterwards is a readable label on a
  -- term this migration excluded.
  select count(*) into n
    from semantic_private.presumed_terms
   where normalized_label ~ '@' or normalized_label ~ '^https?://';
  if n > 0 then
    raise exception
      '0323: % contact-shaped labels are still readable in the key', n;
  end if;
end;
$$;

