-- 0351 — the re-placed headings overwrite their hub-level proposals.
--
-- The within-hub re-place (ris_v19): the placement pass's bare-hub answers
-- asked again over the full authored inventory — the one `0346`/`0348`/`0349`
-- built — and 1008 terms took a specific heading. 184 refused
-- (`none`, honest), 24 routed to the proposal lane. A specific answer
-- to the same question from the same lane overwrites the hub proposal it
-- replaces; proposals from any other source are untouched.
--
-- Headings resolve best-effort with misses counted (`0344`'s inherited rule):
-- the inventories were read off the live tree, which holds runtime-minted
-- concepts a clean replay does not.

do $$
declare
  n integer;
  missing text;
begin
  create temporary table _replacement
    (normalized_label text, family text, parent_key text, confidence numeric)
    on commit drop;
  insert into _replacement values
    ('100 greatest classical songs', 'album', 'genre:classical_music', 0.95),
    ('105 downtown', 'work', 'genre:apple_100051', 0.95),
    ('1989 (deluxe)', 'album', 'genre:pop', 0.95),
    ('24k magic', 'franchise', 'genre:pop', 0.95),
    ('5 seconds of summer', 'franchise', 'genre:pop', 0.95),
    ('5 seconds of summer', 'group', 'genre:pop', 0.95),
    ('5:20am', 'music_work', 'genre:pop', 0.95),
    ('904site', 'work', 'genre:tokusatsu', 0.95),
    ('a matter of time', 'album', 'genre:pop', 0.95),
    ('a sentimental man', 'music_work', 'genre:film_score', 0.95),
    ('a si', 'person', 'genre:mandopop', 0.95),
    ('a-mei chang', 'person', 'genre:mandopop', 0.95),
    ('a.i. artificial intelligence', 'franchise', 'genre:science_fiction_film', 0.95),
    ('a.i. no.12', 'franchise', 'genre:mandopop', 0.95),
    ('aashiqui 2', 'franchise', 'genre:musical_film', 0.95),
    ('academy of st martin in the fields chorus, sir neville marriner & academy of st martin in the fields', 'group', 'genre:classical_music', 0.95),
    ('acoustic version', 'work', 'genre:pop', 0.95),
    ('actually pt.2', 'music_work', 'genre:pop', 0.95),
    ('actually pt.2', 'work', 'genre:pop', 0.95),
    ('adrian thesen', 'person', 'genre:world', 0.95),
    ('after hours', 'franchise', 'genre:pop', 0.95),
    ('afu', 'group', 'genre:mandopop', 0.95),
    ('afu', 'person', 'genre:mandopop', 0.95),
    ('afü', 'franchise', 'genre:mandopop', 0.95),
    ('agnus dei', 'work', 'genre:classical_music', 0.95),
    ('agonie', 'music_work', 'genre:anime', 0.95),
    ('ai guo ni', 'music_work', 'genre:anime', 0.95),
    ('ai xing ren', 'person', 'genre:mandopop', 0.95),
    ('airplay', 'person', 'genre:hip_hop', 0.95),
    ('aj michalka', 'person', 'genre:pop', 0.95),
    ('ajab prem ki ghazab kahani', 'franchise', 'genre:romance_film', 0.95),
    ('ajab si', 'music_work', 'genre:apple_1263', 0.95),
    ('akmu', 'franchise', 'genre:k_pop', 0.95),
    ('alexa', 'person', 'subject:language_learning', 0.95),
    ('ali tamposi', 'person', 'genre:pop', 0.95),
    ('aliez', 'music_work', 'genre:anime', 0.95),
    ('all in', 'music_work', 'genre:pop', 0.95),
    ('all my demons greeting me as a friend', 'album', 'genre:alternative_rock', 0.95),
    ('amatsuki monogatari', 'work', 'genre:monogatari', 0.95),
    ('ambition', 'work', 'genre:wisdom_literature', 0.95),
    ('anarchy rainbow', 'music_work', 'genre:anime', 0.95),
    ('animal crossing', 'franchise', 'genre:life_simulation_game', 0.95),
    ('anime music collection piano solo vol.2', 'album', 'genre:anime', 0.95),
    ('another me', 'music_work', 'genre:mandopop', 0.95),
    ('another me in the world', 'work', 'genre:mandopop', 0.95),
    ('another paradise', 'music_work', 'genre:mandopop', 0.95),
    ('apple music edition', 'work', 'genre:pop', 0.95),
    ('ari band', 'group', 'genre:pop', 0.95),
    ('aria', 'work', 'genre:art_song', 0.95),
    ('aria: gebt mir meinen jesum wieder', 'work', 'genre:art_song', 0.95),
    ('asmr', 'activity', 'activity:flute', 0.0),
    ('asuka okura', 'person', 'genre:anime', 0.95),
    ('asuna', 'person', 'genre:role_playing_game', 0.95),
    ('atlus game music', 'organization', 'genre:anime', 0.95),
    ('atlus kozuka remix', 'music_work', 'genre:anime', 0.95),
    ('august rush', 'franchise', 'genre:musical_film', 0.95),
    ('august stradal', 'person', 'genre:classical_music', 0.95),
    ('awaken the world - the 1st album', 'album', 'genre:pop', 0.95),
    ('away from here', 'album', 'genre:pop', 0.85),
    ('away from here', 'music_work', 'genre:pop', 0.85),
    ('away from here', 'work', 'genre:pop', 0.85),
    ('babymonster', 'franchise', 'genre:k_pop', 0.95),
    ('bach', 'franchise', 'genre:baroque', 0.95),
    ('bach''s violin concertos', 'franchise', 'genre:baroque', 0.95),
    ('bach: sonatas & partitas', 'album', 'genre:classical_music', 0.95),
    ('bach: violin partitas', 'franchise', 'genre:baroque', 0.95),
    ('bach: violin sonatas nos. 1 & 2; partita no. 1', 'franchise', 'genre:sonata', 0.95),
    ('bad mode', 'franchise', 'genre:pop', 0.95),
    ('badbadnotgood', 'group', 'genre:indie', 0.95),
    ('badlands (deluxe)', 'album', 'genre:indie', 0.95),
    ('bai wuyou', 'franchise', 'genre:mandopop', 0.95),
    ('bai wuyou (xiao yin mi man first personal album)', 'album', 'genre:mandopop', 0.95),
    ('bang bang bur!...n?', 'work', 'genre:tokusatsu', 0.95),
    ('baocang shan', 'person', 'genre:hip_hop', 0.95),
    ('barbie', 'franchise', 'genre:children_s_film', 0.95),
    ('barcelona night', 'franchise', 'subject:travel', 0.9),
    ('begin to hope (special edition)', 'album', 'genre:pop', 0.95),
    ('ben samama', 'person', 'genre:pop', 0.95),
    ('beneath the mask', 'music_work', 'genre:anime', 0.95),
    ('berlin philharmonic & ferenc fricsay', 'group', 'genre:classical_music', 0.95),
    ('bestie', 'group', 'genre:k_pop', 0.95),
    ('beth fowler', 'person', 'genre:film_score', 0.95),
    ('bi shui xi', 'music_work', 'genre:mandopop', 0.95),
    ('bi shui xia', 'music_work', 'genre:mandopop', 0.95),
    ('binglue', 'person', 'genre:pop', 0.85),
    ('bioinformagician', 'person', 'activity:quantitative_research', 0.85),
    ('blackpink', 'franchise', 'genre:k_pop', 0.95),
    ('blazing heart', 'music_work', 'genre:anime', 0.95),
    ('blind, blind', 'franchise', 'genre:mandopop', 0.95),
    ('blue', 'music_work', 'genre:pop', 0.95),
    ('blue fireworks', 'music_work', 'genre:pop', 0.85),
    ('bo yuan', 'person', 'genre:mandopop', 0.95),
    ('boku wa kuma (i''m a bear)', 'work', 'genre:anime', 0.95),
    ('boqueria', 'franchise', 'cuisine:spanish_cuisine', 0.95),
    ('boqueria', 'organization', 'subject:travel', 0.9),
    ('boss baby', 'work', 'genre:children_s_film', 0.95),
    ('box of stones (acoustic version)', 'work', 'genre:pop', 0.95),
    ('boys over flowers', 'franchise', 'genre:teen_drama_television', 0.95),
    ('brat', 'franchise', 'genre:pop', 0.95),
    ('bryan adams', 'person', 'genre:pop', 0.95),
    ('bu lian ai tan hua', 'work', 'genre:mandopop', 0.95),
    ('bu nong lei', 'work', 'genre:mandopop', 0.95),
    ('bu ru hui jia he zi lai shui', 'music_work', 'genre:mandopop', 0.95),
    ('buckles laboratories presents: the intermission', 'album', 'genre:indie', 0.95),
    ('burn! phoenix', 'franchise', 'genre:romance_film', 0.95),
    ('burn! phoenix', 'work', 'genre:romance_film', 0.95),
    ('bwv 21', 'work', 'genre:cantata', 0.95),
    ('bwv 245', 'work', 'genre:baroque', 0.95),
    ('c-low', 'person', 'genre:hip_hop', 0.95),
    ('caffeine', 'music_work', 'genre:k_pop', 0.95),
    ('canzonetta (andante)', 'work', 'genre:art_song', 0.95),
    ('car crash', 'work', 'genre:road_movie', 0.95),
    ('carlos gardel', 'person', 'genre:latin_pop', 0.95),
    ('carol & tuesday', 'franchise', 'genre:children_s_film', 0.95),
    ('carol & tuesday', 'group', 'genre:pop', 0.95),
    ('carplay', 'work', 'activity:maker_culture', 0.85),
    ('casey lee williams', 'person', 'genre:anime', 0.95),
    ('cello adagios', 'album', 'genre:classical_music', 0.95),
    ('central park', 'place', 'subject:travel', 0.9),
    ('chae won', 'person', 'genre:k_pop', 0.95),
    ('chao chi lan', 'person', 'genre:mandopop', 0.95),
    ('chen chusheng', 'person', 'genre:mandopop', 0.95),
    ('chen mozhi', 'person', 'genre:mandopop', 0.95),
    ('chen xinzhe', 'person', 'genre:rock', 0.95),
    ('chen zhou band', 'group', 'genre:mandopop', 0.95),
    ('cheng he ti tong', 'franchise', 'genre:chinese_television_drama', 0.95),
    ('cheng he ti tong season 2', 'work', 'genre:chinese_television_drama', 0.95),
    ('china blue', 'group', 'genre:rock', 0.95),
    ('china-rain', 'work', 'genre:mandopop', 0.95),
    ('chinese opera collection', 'work', 'genre:opera', 0.95),
    ('chiyeon', 'person', 'genre:k_pop', 0.95),
    ('choom', 'activity', 'genre:pop', 0.95),
    ('choral', 'work', 'genre:choral', 0.95),
    ('chungking express', 'franchise', 'genre:romance_film', 0.95),
    ('ci sheng bu huan', 'music_work', 'genre:mandopop', 0.95),
    ('cinderella & four knights', 'franchise', 'genre:romance_film', 0.95),
    ('cinderella & four knights, pt. 2', 'franchise', 'genre:romance_film', 0.95),
    ('cinema serenade', 'album', 'genre:serenade', 0.95),
    ('city pop', 'culture', 'genre:pop', 0.95),
    ('city pop', 'franchise', 'genre:pop', 0.95),
    ('classical', 'franchise', 'genre:classical', 0.95),
    ('clever prisoner', 'game', 'genre:video_game', 0.95),
    ('cloud atlas', 'franchise', 'genre:anthology_film', 0.95),
    ('cloud bossa', 'album', 'genre:apple_1221', 0.95),
    ('cloud bossa', 'music_work', 'genre:apple_1221', 0.95),
    ('cody tarpley', 'person', 'genre:apple_1101', 0.95),
    ('colors', 'music_work', 'genre:pop', 0.95),
    ('crazy', 'music_work', 'genre:pop', 0.95),
    ('crazy about you', 'franchise', 'genre:pop', 0.95),
    ('csa', 'person', 'genre:world', 0.95),
    ('cvi.che 105', 'work', 'activity:maker_culture', 0.95),
    ('cyberpunk 2077: radio, vol. 2 (original soundtrack)', 'album', 'genre:soundtrack', 0.95),
    ('cyndi with u', 'album', 'genre:mandopop', 0.95),
    ('cécile corbel', 'person', 'genre:celtic_music', 0.95),
    ('d smoke', 'person', 'genre:hip_hop', 0.95),
    ('da dongbei wo de jia xiang', 'music_work', 'genre:mandopop', 0.95),
    ('da dongbei wo de jiaxiang (dj he peng ban)', 'work', 'genre:mandopop', 0.95),
    ('da vinci', 'person', 'movement:renaissance', 0.95),
    ('dance of the blessed spirits', 'work', 'genre:opera', 0.95),
    ('daniel harding & berlin philharmonic', 'group', 'genre:classical_music', 0.95),
    ('dao jiang', 'person', 'genre:pop', 0.95),
    ('dao tong xing hang', 'music_work', 'genre:mandopop', 0.95),
    ('defying gravity', 'music_work', 'genre:pop', 0.95),
    ('della', 'person', 'genre:mandopop', 0.95),
    ('deng fu-ru', 'person', 'genre:mandopop', 0.95),
    ('deng jiudiao', 'franchise', 'genre:reality_television', 0.95),
    ('deng jiudiao', 'person', 'genre:mandopop', 0.95),
    ('deng jiudiao jiahui', 'person', 'genre:mandopop', 0.95),
    ('deuspro', 'work', 'genre:tokusatsu', 0.95),
    ('devilman crybaby', 'franchise', 'genre:horror_film', 0.95),
    ('die for you', 'music_work', 'genre:pop', 0.95),
    ('different pages', 'album', 'genre:pop', 0.95),
    ('ding yuxi', 'person', 'genre:mandopop', 0.95),
    ('dirty pretty things', 'album', 'genre:indie', 0.95),
    ('dislike dream of the red chamber', 'music_work', 'genre:mandopop', 0.95),
    ('distance', 'work', 'genre:world', 0.95),
    ('divinely uninspired to a hellish extent (extended edition)', 'album', 'genre:pop', 0.95),
    ('dj j.l.p', 'person', 'genre:world', 0.85),
    ('dmitri shostakovich', 'person', 'genre:classical_music', 0.95),
    ('doja cat', 'person', 'genre:pop', 0.95),
    ('don''t ask me what disco is', 'music_work', 'genre:disco', 0.95),
    ('don''t call me da vinci', 'work', 'genre:pop_punk', 0.95),
    ('don''t call me da vinci (punk version)', 'album', 'genre:pop_punk', 0.95),
    ('donald voorhees & bell telephone orchestra', 'group', 'genre:orchestral', 0.95),
    ('dong jiji', 'person', 'genre:mandopop', 0.95),
    ('dorohedoro', 'franchise', 'genre:tokusatsu', 0.95),
    ('dream of the red chamber', 'franchise', 'genre:fiction_literature', 0.95),
    ('dream of the red chamber', 'work', 'genre:fiction_literature', 0.95),
    ('dried flower', 'album', 'genre:pop', 0.95),
    ('drrr!!', 'franchise', 'genre:reality_television', 0.95),
    ('dry flowers', 'work', 'genre:pop', 0.95),
    ('dui wang', 'work', 'genre:mandopop', 0.95),
    ('duniyaa', 'music_work', 'genre:apple_1266', 0.95),
    ('earfquake', 'franchise', 'genre:pop', 0.95),
    ('earth escape plan', 'work', 'genre:science_fiction_film', 0.95),
    ('easy crazy hot', 'franchise', 'genre:k_pop', 0.95),
    ('ejae', 'person', 'genre:pop', 0.95),
    ('emptiso', 'group', 'genre:apple_1250', 0.95),
    ('emptiso', 'person', 'genre:pop', 0.95),
    ('empty love', 'album', 'genre:pop', 0.95),
    ('endless love', 'music_work', 'genre:mandopop', 0.95),
    ('english baroque soloists, monteverdi choir & john eliot gardiner', 'group', 'genre:baroque', 0.95),
    ('episode 25', 'franchise', 'genre:k_pop', 0.95),
    ('episode 25', 'work', 'genre:anime', 0.95),
    ('escapism', 'music_work', 'genre:anime', 0.95),
    ('essentials', 'album', 'genre:pop', 0.95),
    ('extended awake', 'album', 'genre:pop', 0.95),
    ('extended awake road trip vibes', 'franchise', 'genre:pop', 0.95),
    ('exy', 'person', 'genre:pop', 0.95),
    ('f1 the album', 'album', 'genre:film_score', 0.95),
    ('f1 the album', 'franchise', 'genre:film_score', 0.95),
    ('f1 the movie', 'franchise', 'genre:action_film', 0.85),
    ('fame is a gun', 'work', 'genre:pop', 0.95),
    ('fan hua meng', 'music_work', 'genre:mandopop', 0.95),
    ('fanfarepizza', 'music_work', 'genre:tokusatsu', 0.95),
    ('fantastic four', 'franchise', 'genre:superhero_film', 0.95),
    ('farewell for now!', 'franchise', 'genre:k_pop', 0.95),
    ('felix', 'person', 'genre:k_pop', 0.95),
    ('feng peilin', 'person', 'genre:mandopop', 0.95),
    ('feng qi zhi shi', 'album', 'genre:soundtrack', 0.95),
    ('fight for my way', 'franchise', 'genre:action_film', 0.85),
    ('final fantasy vii rebirth', 'franchise', 'genre:role_playing_game', 0.95),
    ('final fantasy vii rebirth', 'game', 'genre:role_playing_game', 0.95),
    ('final fantasy vii remake', 'game', 'genre:role_playing_game', 0.95),
    ('final fantasy vii remake', 'work', 'genre:role_playing_game', 0.95),
    ('final fantasy vii: advent children', 'franchise', 'genre:science_fiction_film', 0.95),
    ('finale', 'work', 'genre:electronic', 0.95),
    ('fingertip', 'franchise', 'genre:video_game', 0.95),
    ('fire-yo!hito', 'music_work', 'genre:anime', 0.95),
    ('first love', 'franchise', 'genre:pop', 0.95),
    ('first love', 'music_work', 'genre:pop', 0.95),
    ('fivestar', 'group', 'genre:pop', 0.95),
    ('flute version', 'music_work', 'genre:film_score', 0.95),
    ('for ya', 'album', 'genre:mandopop', 0.95),
    ('forever beautiful', 'music_work', 'genre:mandopop', 0.95),
    ('forever love', 'music_work', 'genre:pop', 0.95),
    ('formula one', 'franchise', 'activity:motorsport', 0.95),
    ('friday night plans', 'group', 'genre:pop', 0.95),
    ('fu sichao', 'person', 'genre:mandopop', 0.95),
    ('full length edition', 'album', 'genre:pop', 0.95),
    ('furong', 'person', 'genre:mandopop', 0.95),
    ('fushigix', 'group', 'genre:anime', 0.95),
    ('fuyao', 'franchise', 'genre:chinese_television_drama', 0.95),
    ('g-idle', 'group', 'genre:k_pop', 0.95),
    ('gaeko', 'person', 'genre:hip_hop', 0.95),
    ('gal-othy-mos', 'work', 'genre:anime', 0.95),
    ('galantis', 'group', 'genre:electronic_dance_music', 0.95),
    ('gallant ones', 'music_work', 'genre:anime', 0.95),
    ('ge dongqi', 'person', 'genre:mandopop', 0.95),
    ('get a life (live)', 'album', 'genre:pop', 0.95),
    ('ghost', 'person', 'genre:pop', 0.95),
    ('ghost pop', 'album', 'genre:pop', 0.95),
    ('girl', 'franchise', 'genre:mandopop', 0.95),
    ('girl just dance', 'album', 'genre:pop', 0.95),
    ('girl just dance', 'music_work', 'genre:pop', 0.95),
    ('girl just dance', 'work', 'genre:pop', 0.95),
    ('girls'' generation', 'group', 'genre:k_pop', 0.95),
    ('glass heart', 'music_work', 'genre:mandopop', 0.95),
    ('gmmtv', 'organization', 'activity:translation', 0.9),
    ('golden hour', 'music_work', 'genre:pop', 0.95),
    ('gosick', 'franchise', 'genre:mystery_film', 0.95),
    ('grace rolek', 'person', 'genre:pop', 0.95),
    ('growls and purrs', 'music_work', 'genre:pop', 0.95),
    ('growls and purrs', 'work', 'genre:documentary_film', 0.95),
    ('guan shan jiu', 'music_work', 'genre:opera', 0.95),
    ('gui bian', 'person', 'genre:mandopop', 0.95),
    ('gumi', 'person', 'genre:anime', 0.95),
    ('györgy ligeti', 'person', 'genre:classical_music', 0.95),
    ('h.i.n.p', 'group', 'genre:k_pop', 0.95),
    ('habitual love', 'music_work', 'genre:mandopop', 0.95),
    ('hair tie', 'album', 'activity:hair_spray', 0.8),
    ('hair tie', 'work', 'activity:hair_spray', 0.8),
    ('hands up to the sky', 'music_work', 'genre:pop', 0.95),
    ('hao xuan peking opera', 'group', 'genre:opera', 0.95),
    ('he lu', 'person', 'genre:mandopop', 0.95),
    ('he yu', 'person', 'genre:mandopop', 0.95),
    ('heartbeat proof', 'music_work', 'genre:mandopop', 0.95),
    ('heartbeat proof (movie ''i kiss you'' heartbeat version theme song)', 'album', 'genre:mandopop', 0.95),
    ('heartbeat proof (movie ''i kissed the girl'' heartbeat version theme song)', 'album', 'genre:anime', 0.95),
    ('heinrich schiff & samuel sanders', 'group', 'genre:classical_music', 0.95),
    ('hello my loneliness', 'music_work', 'genre:pop', 0.95),
    ('hey, about love', 'music_work', 'genre:mandopop', 0.95),
    ('hikari', 'person', 'genre:j_pop', 0.95),
    ('hikaru utada', 'franchise', 'genre:j_pop', 0.95),
    ('hnrna', 'work', 'subject:biology', 0.95),
    ('homeland', 'work', 'genre:thriller_film', 0.95),
    ('honkai academy', 'work', 'genre:gacha_game', 0.95),
    ('honkai impact 3rd', 'franchise', 'genre:gacha_game', 0.95),
    ('honkai: star rail', 'franchise', 'genre:gacha_game', 0.95),
    ('honor to us all', 'music_work', 'genre:film_score', 0.95),
    ('hounds of love', 'album', 'genre:pop', 0.95),
    ('hsin kuang han', 'person', 'genre:mandopop', 0.95),
    ('hsinchu girls'' high school', 'organization', 'activity:translation', 0.1),
    ('hsinchu girls'' high school 70th graduation song', 'work', 'genre:pop', 0.95),
    ('hsu kuang-han', 'person', 'genre:mandopop', 0.95),
    ('huang ling', 'person', 'genre:mandopop', 0.95),
    ('huangmei opera', 'work', 'genre:opera', 0.95),
    ('huh yunjin', 'person', 'genre:k_pop', 0.95),
    ('hui mou', 'work', 'genre:mandopop', 0.95),
    ('hungarian dances', 'franchise', 'genre:classical_music', 0.95),
    ('hunter', 'music_work', 'genre:electronic', 0.95),
    ('hyatt regency bellevue', 'organization', 'subject:travel', 0.95),
    ('i am the i', 'album', 'genre:anime', 0.95),
    ('i kiss you', 'franchise', 'genre:romance_film', 0.95),
    ('i kissed the girl', 'franchise', 'genre:anime', 0.95),
    ('i love him', 'music_work', 'genre:pop', 0.95),
    ('i need to know', 'work', 'genre:pop', 0.95),
    ('i really want to stay at your house', 'music_work', 'genre:film_score', 0.95),
    ('i wrote you a song', 'music_work', 'genre:pop', 0.85),
    ('i''m o.k.', 'album', 'genre:pop', 0.95),
    ('i''mdifficult', 'person', 'genre:pop', 0.95),
    ('i''mdifficult ver.', 'work', 'genre:pop', 0.95),
    ('i-dle', 'franchise', 'genre:k_pop', 0.95),
    ('ian', 'person', 'genre:k_pop', 0.95),
    ('ich bin''s, ich sollte büssen', 'work', 'genre:choral', 0.95),
    ('ich hatte viel bekummernis', 'work', 'genre:art_song', 0.95),
    ('ich will dir mein herze schenken', 'work', 'genre:art_song', 0.95),
    ('ich will hier bei dir stehen', 'work', 'genre:choral', 0.95),
    ('idle', 'franchise', 'genre:video_game', 0.95),
    ('idle', 'game', 'genre:incremental_game', 0.95),
    ('if the world was ending', 'work', 'genre:pop', 0.95),
    ('iii. allegro', 'work', 'genre:concerto', 0.95),
    ('iiic. sequentia. rex tremendae', 'work', 'genre:classical_music', 0.95),
    ('illjun', 'person', 'genre:hip_hop', 0.95),
    ('illusion', 'music_work', 'genre:pop', 0.85),
    ('in his eyes', 'music_work', 'genre:pop', 0.95),
    ('in our planet tears do not exceed three seconds', 'music_work', 'genre:pop', 0.95),
    ('in your eyes', 'music_work', 'genre:pop', 0.95),
    ('inryou', 'person', 'genre:j_pop', 0.95),
    ('interstellar', 'franchise', 'genre:science_fiction_film', 0.95),
    ('invu', 'franchise', 'genre:video_game', 0.95),
    ('it''s live', 'franchise', 'genre:k_pop', 0.95),
    ('iu', 'franchise', 'genre:k_pop', 0.95),
    ('izone', 'group', 'genre:k_pop', 0.95),
    ('j. lloyd', 'person', 'genre:pop', 0.95),
    ('j.s. bach', 'person', 'genre:classical', 0.95),
    ('jacob''s piano', 'work', 'genre:pop', 0.95),
    ('jaideep sahni', 'person', 'genre:comedy_film', 0.95),
    ('jaira burns', 'person', 'genre:pop', 0.95),
    ('jane zhang', 'person', 'genre:mandopop', 0.95),
    ('japanese zen music', 'activity', 'genre:asian_music', 0.95),
    ('jason hahs', 'person', 'genre:pop', 0.95),
    ('jazz suites nos. 1 - 2', 'album', 'genre:jazz', 0.95),
    ('jeffree star', 'person', 'genre:pop', 0.95),
    ('jekyll & hyde', 'franchise', 'genre:musicals', 0.95),
    ('jekyll & hyde (musical)', 'franchise', 'genre:musicals', 0.95),
    ('jer', 'person', 'genre:action_film', 0.95),
    ('jerry c', 'person', 'genre:film_score', 0.95),
    ('jess glynne', 'person', 'genre:pop', 0.95),
    ('jess lee', 'person', 'genre:mandopop', 0.95),
    ('ji nian', 'work', 'genre:mandopop', 0.95),
    ('jian hun', 'music_work', 'genre:mandopop', 0.95),
    ('jiangnan 100 scenes', 'franchise', 'genre:video_game', 0.95),
    ('jiangnan 100 scenes', 'game', 'genre:video_game', 0.95),
    ('jiangnan baijing tu', 'game', 'genre:city_building_game', 0.95),
    ('jing nan zhen', 'work', 'genre:mandopop', 0.95),
    ('jiu xing', 'music_work', 'genre:mandopop', 0.95),
    ('jiu zai jiang hu zhi shang', 'music_work', 'genre:mandopop', 0.95),
    ('joanna wang', 'person', 'genre:mandopop', 0.95),
    ('jodi milliner', 'person', 'genre:pop', 0.95),
    ('johann wolfgang von goethe', 'person', 'movement:romanticism', 0.95),
    ('john powell', 'person', 'genre:film_score', 0.95),
    ('john shanks', 'person', 'genre:pop', 0.95),
    ('joker', 'franchise', 'genre:superhero_film', 0.95),
    ('jon bon jovi', 'person', 'genre:rock', 0.95),
    ('jp saxe', 'person', 'genre:pop', 0.95),
    ('julia michaels', 'person', 'genre:pop', 0.95),
    ('junko ohashi', 'person', 'genre:j_pop', 0.95),
    ('junpei fujita', 'person', 'genre:j_pop', 0.95),
    ('just go', 'franchise', 'genre:apple_1250', 0.95),
    ('just go', 'music_work', 'genre:pop', 0.85),
    ('kan beer', 'work', 'cuisine:japanese_cuisine', 0.95),
    ('kate micucci', 'person', 'genre:pop', 0.95),
    ('kazekoi', 'franchise', 'genre:visual_novel', 0.95),
    ('kazekoi', 'work', 'genre:anime', 0.95),
    ('keep your head up princess', 'music_work', 'genre:pop', 0.95),
    ('kehlani', 'person', 'genre:apple_1143', 0.95),
    ('kemu voxx', 'group', 'genre:anime', 0.95),
    ('kenzie', 'person', 'genre:pop', 0.95),
    ('kenzie smith', 'person', 'genre:anime', 0.95),
    ('kid princess', 'person', 'genre:pop', 0.95),
    ('kiiikiii', 'group', 'genre:k_pop', 0.95),
    ('kim min-ju', 'person', 'genre:k_pop', 0.95),
    ('kim minju', 'person', 'genre:k_pop', 0.95),
    ('kirito', 'person', 'genre:role_playing_game', 0.95),
    ('kiroro', 'franchise', 'genre:pop', 0.95),
    ('kiss goodbye', 'work', 'genre:mandopop', 0.95),
    ('kiss of death', 'franchise', 'genre:crime_film', 0.95),
    ('knock yourself out xd', 'music_work', 'genre:anime', 0.95),
    ('koharanamu', 'group', 'genre:pop', 0.95),
    ('koharanamu', 'person', 'genre:pop', 0.95),
    ('koisiteru jibun sura aiserun da', 'music_work', 'genre:j_pop', 0.95),
    ('koisiteru jibun sura aiserun da', 'work', 'genre:j_pop', 0.95),
    ('kong di', 'work', 'genre:mandopop', 0.95),
    ('kosuga taichi', 'person', 'genre:j_pop', 0.95),
    ('kosuga tsuyoshi', 'person', 'genre:j_pop', 0.95),
    ('krystal chan', 'person', 'genre:mandopop', 0.95),
    ('kunaal vermaa', 'person', 'genre:reality_show', 0.9),
    ('kwda', 'organization', 'genre:k_pop', 0.95),
    ('kyoto', 'place', 'subject:travel', 0.8),
    ('kyrie', 'work', 'genre:choral', 0.95),
    ('la la land', 'franchise', 'genre:musical_film', 0.95),
    ('la la lost you', 'music_work', 'genre:pop', 0.95),
    ('la la lost you', 'work', 'genre:k_pop', 0.95),
    ('laco', 'person', 'genre:pop', 0.95),
    ('lai qu da gong', 'work', 'genre:mandopop', 0.95),
    ('lamar abrams', 'person', 'genre:anime', 0.95),
    ('lamp volcano', 'work', 'movement:land_art', 0.95),
    ('last fantasy', 'franchise', 'genre:video_game', 0.95),
    ('last smoke before the snowstorm', 'album', 'genre:indie', 0.95),
    ('last smoke before the snowstorm (10th anniversary edition)', 'album', 'genre:indie', 0.95),
    ('lata dwudzieste z kawałkiem', 'album', 'genre:apple_1185', 0.95),
    ('lee ji-eun', 'person', 'genre:k_pop', 0.95),
    ('lee si-an', 'person', 'genre:k_pop', 0.95),
    ('leehom wang', 'person', 'genre:mandopop', 0.95),
    ('lei yuxin', 'person', 'genre:mandopop', 0.95),
    ('leng ye', 'music_work', 'genre:mandopop', 0.95),
    ('leng ye', 'work', 'genre:mandopop', 0.95),
    ('let romance be the master', 'music_work', 'genre:mandopop', 0.95),
    ('li runqi', 'person', 'genre:mandopop', 0.95),
    ('li wei', 'person', 'genre:mandopop', 0.95),
    ('lian qingkuang', 'person', 'genre:mandopop', 0.95),
    ('lian qingkuang', 'work', 'genre:anime', 0.95),
    ('lighter', 'work', 'activity:maker_culture', 0.85),
    ('lightsum', 'group', 'genre:k_pop', 0.95),
    ('lilac', 'franchise', 'genre:k_pop', 0.95),
    ('lilu xiu', 'person', 'genre:pop', 0.95),
    ('lin chia-ling', 'person', 'genre:mandopop', 0.95),
    ('lin mo', 'person', 'genre:mandopop', 0.95),
    ('lin xing', 'person', 'genre:mandopop', 0.95),
    ('line gøttsche', 'person', 'genre:pop', 0.95),
    ('liu renyu', 'person', 'genre:mandopop', 0.95),
    ('liu sijian', 'person', 'genre:mandopop', 0.95),
    ('liu xiao', 'person', 'genre:mandopop', 0.95),
    ('liu yuning', 'person', 'genre:mandopop', 0.95),
    ('live version', 'activity', 'genre:pop', 0.95),
    ('live version', 'album', 'genre:world', 0.85),
    ('llano', 'person', 'genre:world', 0.95),
    ('lofthestar', 'franchise', 'genre:reality_television', 0.95),
    ('loki', 'person', 'genre:science_fiction_television_program', 0.95),
    ('lose my mind (feat. doja cat) [from f1® the movie]', 'music_work', 'genre:soundtrack', 0.95),
    ('lotus lantern', 'franchise', 'genre:chinese_television_drama', 0.95),
    ('lotus tower', 'franchise', 'genre:chinese_television_drama', 0.95),
    ('love emergency', 'music_work', 'genre:mandopop', 0.95),
    ('love is gone', 'franchise', 'genre:pop', 0.95),
    ('love is gone', 'music_work', 'genre:pop', 0.95),
    ('love is science', 'franchise', 'genre:romance_film', 0.95),
    ('love live! school idol festival', 'franchise', 'genre:video_game', 0.95),
    ('love me not', 'franchise', 'genre:romance_film', 0.95),
    ('love me not', 'music_work', 'genre:anime', 0.95),
    ('love me wild', 'album', 'genre:pop', 0.95),
    ('love me wild', 'music_work', 'genre:pop', 0.95),
    ('love options', 'work', 'genre:k_pop', 0.95),
    ('love story', 'franchise', 'genre:j_pop', 0.95),
    ('love story', 'music_work', 'genre:k_pop', 0.95),
    ('love story', 'work', 'genre:j_pop', 0.95),
    ('love team', 'work', 'genre:j_pop', 0.95),
    ('love yourself', 'franchise', 'genre:k_pop', 0.95),
    ('loveshhhlovegun', 'work', 'genre:girls_with_guns', 0.95),
    ('lucifer', 'person', 'genre:horror_film', 0.95),
    ('luka chuppi', 'franchise', 'genre:romance_film', 0.95),
    ('luke', 'person', 'genre:mandopop', 0.95),
    ('luo hua qing', 'music_work', 'genre:mandopop', 0.95),
    ('lydia kitto', 'person', 'genre:pop', 0.95),
    ('m countdown', 'event', 'genre:k_pop', 0.95),
    ('ma vie, mes rêves', 'music_work', 'genre:french_pop', 0.95),
    ('ma yin yin', 'person', 'genre:mandopop', 0.95),
    ('madeon', 'person', 'genre:electronic', 0.95),
    ('maggie valley', 'album', 'genre:country', 0.95),
    ('mahiru koda', 'person', 'genre:j_pop', 0.95),
    ('mahler: symphonien 1–10', 'album', 'genre:classical_music', 0.95),
    ('maltose', 'work', 'cuisine:chinese_cuisine', 0.95),
    ('mama awards', 'event', 'genre:k_pop', 0.95),
    ('mang', 'work', 'genre:mandopop', 0.95),
    ('mao buyi', 'person', 'genre:mandopop', 0.95),
    ('mariya takeuchi', 'person', 'genre:apple_28', 0.95),
    ('marni nixon', 'person', 'genre:opera', 0.95),
    ('marty', 'franchise', 'genre:comedy_film', 0.95),
    ('marty', 'person', 'genre:biographical_film', 0.95),
    ('marvel cinematic universe', 'franchise', 'genre:superhero_film', 0.95),
    ('matilda', 'work', 'genre:anime', 0.95),
    ('matthäus-passion', 'music_work', 'genre:baroque', 0.95),
    ('matthäus-passion, bwv 244', 'album', 'genre:baroque', 0.95),
    ('matthäus-passion, bwv 244', 'music_work', 'genre:baroque', 0.95),
    ('mayday', 'franchise', 'genre:mandopop', 0.95),
    ('maze', 'work', 'genre:mandopop', 0.95),
    ('mc 張天賦', 'person', 'genre:mandopop', 0.95),
    ('mdr rundfunkchor', 'group', 'genre:choral', 0.95),
    ('me & u', 'music_work', 'genre:pop', 0.95),
    ('mein herz, in dem die ganze welt', 'work', 'genre:art_song', 0.95),
    ('mellow', 'music_work', 'genre:adult_contemporary', 0.95),
    ('melow', 'music_work', 'genre:pop', 0.95),
    ('memories of the alhambra, pt. 1 (original television soundtrack)', 'album', 'genre:soundtrack', 0.95),
    ('memory cotton', 'work', 'genre:mandopop', 0.95),
    ('meng weilai', 'person', 'genre:mandopop', 0.95),
    ('meovv', 'franchise', 'genre:k_pop', 0.95),
    ('michael', 'person', 'genre:horror_film', 0.9),
    ('michael mccorry rose', 'person', 'genre:pop', 0.85),
    ('michelle williams', 'person', 'genre:pop', 0.95),
    ('michelle yeoh', 'person', 'genre:martial_arts_film', 0.85),
    ('michi', 'work', 'genre:j_pop', 0.95),
    ('midnight door', 'music_work', 'genre:j_pop', 0.95),
    ('mika', 'person', 'genre:pop', 0.95),
    ('mikoto mukai', 'person', 'genre:j_pop', 0.95),
    ('ming yue', 'person', 'genre:mandopop', 0.95),
    ('mirror mirror', 'music_work', 'genre:anime', 0.95),
    ('mist valley chronicles', 'franchise', 'genre:mystery_film', 0.95),
    ('miyuki nakajima', 'person', 'genre:j_pop', 0.95),
    ('mizukami rimika', 'person', 'genre:j_pop', 0.95),
    ('mizuki', 'person', 'genre:pop', 0.95),
    ('mnet', 'organization', 'genre:k_pop', 0.95),
    ('montgomery ricky', 'album', 'genre:indie', 0.95),
    ('moonlight', 'music_work', 'genre:pop', 0.95),
    ('mozart requiem', 'franchise', 'genre:classical_music', 0.95),
    ('mrna', 'work', 'subject:biology', 0.95),
    ('mul naengmyeon', 'work', 'cuisine:korean_cuisine', 0.95),
    ('mulan', 'franchise', 'genre:children_s_film', 0.95),
    ('musa keys', 'person', 'genre:afrobeat', 0.95),
    ('music bank', 'event', 'genre:k_pop', 0.95),
    ('musical jekyll & hyde 2021 female ensemble', 'group', 'genre:pop', 0.95),
    ('my hero academia', 'franchise', 'genre:superhero_film', 0.95),
    ('my hero academia season 2', 'work', 'genre:superhero_film', 0.95),
    ('my love from the star', 'franchise', 'genre:science_fiction_television_program', 0.95),
    ('my love from the star', 'work', 'genre:science_fiction_television_program', 0.95),
    ('my romeo', 'music_work', 'genre:anime', 0.95),
    ('naina', 'work', 'genre:action_film', 0.95),
    ('nakka', 'person', 'genre:k_pop', 0.95),
    ('namaste england', 'franchise', 'subject:travel', 0.8),
    ('nayina', 'person', 'genre:mandopop', 0.95),
    ('nct', 'franchise', 'genre:k_pop', 0.95),
    ('nct wish', 'group', 'genre:k_pop', 0.95),
    ('negaigoto', 'music_work', 'genre:j_pop', 0.95),
    ('neon genesis evangelion', 'franchise', 'genre:science_fiction_television_program', 0.95),
    ('neon trees', 'group', 'genre:alternative_rock', 0.95),
    ('nerdie', 'person', 'genre:k_pop', 0.95),
    ('neuro traveler', 'person', 'genre:mandopop', 0.95),
    ('never enough', 'album', 'genre:pop', 0.95),
    ('neverstop', 'franchise', 'genre:pop', 0.95),
    ('new eyes', 'album', 'genre:pop', 0.95),
    ('new york', 'place', 'subject:travel', 0.9),
    ('new york city', 'work', 'subject:travel', 0.8),
    ('new zealand symphony orchestra & christopher lyndon-gee', 'group', 'genre:classical_music', 0.95),
    ('nexus', 'music_work', 'genre:anime', 0.95),
    ('nezw', 'person', 'genre:mandopop', 0.95),
    ('niki acoustic sessions: head in the clouds ii', 'album', 'genre:pop', 0.95),
    ('nikki flores', 'person', 'genre:latin_pop', 0.95),
    ('nine stories', 'album', 'genre:pop', 0.95),
    ('nine thousand characters', 'work', 'genre:wisdom_literature', 0.95),
    ('nine thousand words', 'work', 'movement:epic_poem', 0.95),
    ('ning mou', 'music_work', 'genre:mandopop', 0.95),
    ('ning mou', 'work', 'genre:mandopop', 0.95),
    ('no reason', 'music_work', 'genre:pop', 0.95),
    ('none', 'work', 'genre:anime', 0.95),
    ('nv er xin ru shui', 'music_work', 'genre:mandopop', 0.95),
    ('nv er xin ru shui', 'work', 'genre:mandopop', 0.95),
    ('om shanti om', 'franchise', 'genre:musical_film', 0.95),
    ('one (original never ends)', 'album', 'genre:apple_1143', 0.95),
    ('one ok rock', 'franchise', 'genre:alternative_rock', 0.95),
    ('one spring night', 'franchise', 'genre:romance_film', 0.95),
    ('only my railgun', 'anime', 'genre:science_fiction_television_program', 0.95),
    ('osean', 'franchise', 'genre:video_game', 0.95),
    ('outside it''s raining', 'music_work', 'genre:mandopop', 0.95),
    ('outside it''s raining', 'work', 'genre:mandopop', 0.95),
    ('overdrive', 'work', 'genre:k_pop', 0.95),
    ('oz.', 'work', 'genre:anime', 0.95),
    ('ozdust duet', 'work', 'genre:film_score', 0.95),
    ('palace', 'franchise', 'genre:historical_film', 0.95),
    ('palm of the hand', 'music_work', 'genre:world_music', 0.95),
    ('panta.q', 'person', 'genre:anime', 0.95),
    ('park chan-wook', 'person', 'genre:thriller_film', 0.9),
    ('park terrace hotel', 'organization', 'subject:travel', 0.95),
    ('pauline herr', 'person', 'genre:pop', 0.95),
    ('peking opera', 'activity', 'activity:flute', 0.0),
    ('persona', 'franchise', 'genre:visual_novel', 0.95),
    ('persona 5', 'franchise', 'genre:role_playing_game', 0.95),
    ('persona 5 original soundtrack', 'album', 'genre:soundtrack', 0.95),
    ('persona 5 royal: original soundtrack', 'album', 'genre:soundtrack', 0.95),
    ('petrus aber antwortete', 'work', 'genre:christian_metal', 0.8),
    ('ph-1', 'person', 'genre:hip_hop', 0.95),
    ('piano', 'art', 'genre:piano', 0.95),
    ('ping pong', 'franchise', 'genre:sports_video_game', 0.95),
    ('ping pong (original soundtrack)', 'album', 'genre:soundtrack', 0.95),
    ('piromare', 'music_work', 'genre:anime', 0.95),
    ('plastic love', 'franchise', 'genre:pop', 0.95),
    ('plastic love', 'music_work', 'genre:pop', 0.95),
    ('play', 'franchise', 'genre:comedy_film', 0.95),
    ('please do not lean', 'music_work', 'genre:pop', 0.95),
    ('por una cabeza', 'work', 'genre:latin_pop', 0.95),
    ('princess wendy''s guard', 'work', 'genre:children_s_film', 0.95),
    ('pro//die', 'franchise', 'genre:video_game', 0.95),
    ('pro//die', 'work', 'genre:anime', 0.95),
    ('produce 101 japan', 'franchise', 'genre:pop', 0.95),
    ('produce 48', 'franchise', 'genre:k_pop', 0.95),
    ('produce pandas', 'group', 'genre:mandopop', 0.95),
    ('promare', 'anime', 'genre:animated_film', 0.95),
    ('promare', 'franchise', 'genre:tokusatsu', 0.95),
    ('promare (franchise)', 'franchise', 'genre:tokusatsu', 0.95),
    ('punk version', 'work', 'genre:apple_1006', 0.95),
    ('pure', 'music_work', 'genre:pop', 0.85),
    ('pyo eun-ji', 'person', 'genre:k_pop', 0.95),
    ('qi wei', 'person', 'genre:mandopop', 0.95),
    ('qian gua', 'music_work', 'genre:mandopop', 0.95),
    ('qiang qiang', 'person', 'genre:mandopop', 0.95),
    ('qing feng song wo bu xian xian', 'music_work', 'genre:mandopop', 0.95),
    ('qing niao fei yu', 'person', 'genre:mandopop', 0.95),
    ('rachel kanner', 'person', 'genre:pop', 0.95),
    ('ram wire', 'franchise', 'genre:sh_jo', 0.95),
    ('rami', 'person', 'genre:k_pop', 0.95),
    ('rank of kings', 'franchise', 'genre:children_s_film', 0.95),
    ('raphaël pichon & pygmalion', 'group', 'genre:choral', 0.95),
    ('rather be', 'music_work', 'genre:pop', 0.95),
    ('re:zero - starting life in another world', 'franchise', 'genre:science_fiction_film', 0.95),
    ('readon', 'group', 'genre:mandopop', 0.95),
    ('readon', 'person', 'genre:mandopop', 0.95),
    ('red chamber dream', 'franchise', 'genre:fiction_literature', 0.95),
    ('red dust clear joy: qing he', 'music_work', 'genre:mandopop', 0.95),
    ('red scarf', 'work', 'genre:film_score', 0.95),
    ('red white band', 'group', 'genre:reggaeton', 0.95),
    ('ref:rain', 'music_work', 'genre:pop', 0.95),
    ('reg-girt', 'work', 'genre:tokusatsu', 0.95),
    ('reimport, vol. 2 - civil aviation bureau', 'album', 'genre:pop', 0.95),
    ('renaissance', 'franchise', 'movement:renaissance', 0.95),
    ('requiem in d minor, k. 626', 'music_work', 'genre:classical', 0.95),
    ('requiem in d minor, k. 626', 'work', 'genre:classical_music', 0.95),
    ('requiem in d minor, k. 626: vii. agnus dei', 'music_work', 'genre:classical_music', 0.95),
    ('rescene', 'group', 'genre:k_pop', 0.95),
    ('reset', 'work', 'genre:video_game', 0.95),
    ('resister', 'music_work', 'genre:pop', 0.85),
    ('resister', 'work', 'genre:science_fiction_film', 0.95),
    ('resurrection', 'music_work', 'genre:orchestral', 0.95),
    ('rise of the wind', 'album', 'genre:action_role_playing_game', 0.95),
    ('rock', 'activity', 'genre:rock', 0.95),
    ('rockwell', 'person', 'genre:pop', 0.95),
    ('rococo', 'work', 'movement:baroque', 0.95),
    ('rolling stone 40', 'franchise', 'genre:rock', 0.95),
    ('ronny svendsen', 'person', 'genre:world', 0.95),
    ('rrna', 'work', 'subject:biology', 0.95),
    ('ru hua jiang nan', 'music_work', 'genre:mandopop', 0.95),
    ('ru hua jiang nan (jiangnan 100 scenes songjiang prefecture theme)', 'album', 'genre:mandopop', 0.95),
    ('ruby rider', 'music_work', 'genre:anime', 0.95),
    ('rumor', 'work', 'genre:pop', 0.95),
    ('run on', 'franchise', 'genre:romance_film', 0.95),
    ('run to you', 'music_work', 'genre:film_score', 0.95),
    ('run with the wind', 'group', 'genre:anime', 0.95),
    ('runaway', 'music_work', 'genre:pop', 0.95),
    ('running up that hill (epic orchestra)', 'music_work', 'genre:orchestral', 0.95),
    ('rv 297', 'work', 'genre:concerto', 0.95),
    ('rwby', 'franchise', 'genre:science_fiction_television_program', 0.95),
    ('ryan jhun', 'person', 'genre:pop', 0.95),
    ('ryu jeong-han', 'person', 'genre:k_pop', 0.95),
    ('sabrina carpenter', 'franchise', 'genre:pop', 0.95),
    ('sadie killer', 'person', 'genre:anime', 0.95),
    ('saito neko', 'person', 'genre:j_pop', 0.95),
    ('sakamiyu shosai', 'work', 'genre:monogatari', 0.95),
    ('sam', 'person', 'genre:pop', 0.95),
    ('samantabhadra', 'work', 'genre:sutra', 0.95),
    ('sammi cheng', 'person', 'genre:mandopop', 0.95),
    ('samuel sanders & itzhak perlman', 'group', 'genre:classical_music', 0.95),
    ('sanctus', 'music_work', 'genre:choral', 0.95),
    ('sanctus', 'work', 'genre:choral', 0.95),
    ('sand of the instrument', 'work', 'genre:thriller_film', 0.95),
    ('sarah christian, jano lisboa, maximilian hornung, jan-erik gustafsson, wen xiao zheng & johannes strake', 'group', 'genre:classical_music', 0.95),
    ('sarah christian, wen xiao zheng, johannes strake, jano lisboa, jan-erik gustafsson & maximilian hornung', 'group', 'genre:art_song', 0.95),
    ('savage', 'franchise', 'genre:pop', 0.95),
    ('savage tour 2019', 'franchise', 'genre:j_pop', 0.95),
    ('savage tour 2019', 'tour', 'genre:j_pop', 0.95),
    ('sawano hiroyuki', 'person', 'genre:anime', 0.95),
    ('sawanohiroyuki[nzk]:mizuki', 'group', 'genre:j_pop', 0.95),
    ('sbs gayo daejeon', 'event', 'genre:k_pop', 0.95),
    ('sbs inkigayo', 'event', 'genre:k_pop', 0.95),
    ('sbs inkigayo', 'organization', 'genre:k_pop', 0.95),
    ('scent of a woman', 'work', 'genre:gangster_film', 0.95),
    ('scent of a woman: tango (por una cabeza)', 'music_work', 'genre:film_score', 0.95),
    ('scherzo no. 2 in b-flat minor, op. 31', 'music_work', 'genre:classical_music', 0.95),
    ('schumann, bach & brahms: music for violin & piano', 'album', 'genre:classical_music', 0.95),
    ('second hand rose', 'group', 'genre:pop', 0.95),
    ('sequentia. confutatis', 'work', 'genre:classical_music', 0.95),
    ('sequentia. dies irae', 'work', 'movement:baroque_music', 0.85),
    ('sequentia. recordare', 'work', 'genre:chant', 0.95),
    ('sequentia. tuba mirum', 'music_work', 'genre:choral', 0.95),
    ('sequentia. tuba mirum', 'work', 'genre:choral', 0.95),
    ('serendipity', 'music_work', 'genre:k_pop', 0.95),
    ('seufzer, tranen, kummer, not', 'work', 'genre:art_song', 0.95),
    ('seven flowers', 'group', 'genre:mandopop', 0.95),
    ('seven flowers group', 'group', 'genre:mandopop', 0.95),
    ('sex drugs internet', 'album', 'genre:pop', 0.95),
    ('shan gu', 'work', 'genre:chinese_rock', 0.95),
    ('shan wai', 'music_work', 'genre:mandopop', 0.95),
    ('shan yi chun', 'person', 'genre:mandopop', 0.95),
    ('shan yichun', 'person', 'genre:mandopop', 0.95),
    ('she''s somebody''s daughter', 'music_work', 'genre:pop', 0.95),
    ('she''s somebody''s daughter', 'work', 'genre:pop', 0.95),
    ('shengzhang', 'music_work', 'genre:mandopop', 0.95),
    ('shepherd', 'work', 'genre:mandopop', 0.95),
    ('shibuya', 'place', 'subject:travel', 0.95),
    ('shigenaga ryosuke', 'person', 'genre:anime', 0.95),
    ('shiina rin', 'person', 'genre:j_pop', 0.95),
    ('shiina ringo', 'franchise', 'genre:j_pop', 0.95),
    ('shiina ringo', 'group', 'genre:j_pop', 0.95),
    ('shiina ringo', 'person', 'genre:j_pop', 0.95),
    ('shin sakiura', 'person', 'genre:j_pop', 0.95),
    ('shining girls', 'franchise', 'genre:thriller_film', 0.95),
    ('shiro', 'person', 'genre:j_pop', 0.95),
    ('shohey uemura', 'person', 'genre:pop', 0.95),
    ('short song row', 'work', 'genre:mandopop', 0.95),
    ('shousha', 'franchise', 'genre:monogatari', 0.95),
    ('shoushen ji', 'work', 'genre:legend', 0.95),
    ('shuang sheng', 'person', 'genre:mandopop', 0.95),
    ('shui neng gei wo ai (acoustic)', 'music_work', 'genre:mandopop', 0.95),
    ('sim eun-ji', 'person', 'genre:k_pop', 0.95),
    ('simon petrus aber folgete jesu nach', 'work', 'genre:christian_metal', 0.1),
    ('sixteen', 'work', 'genre:anime', 0.95),
    ('skyward', 'franchise', 'genre:science_fiction_film', 0.9),
    ('sleepless nights', 'album', 'genre:j_pop', 0.95),
    ('slim boys', 'franchise', 'genre:pop', 0.95),
    ('slim girls', 'franchise', 'genre:pop', 0.95),
    ('sm entertainment', 'organization', 'genre:k_pop', 0.95),
    ('snrna', 'work', 'subject:biology', 0.95),
    ('so close to what', 'album', 'genre:pop', 0.95),
    ('somebody''s watching me', 'music_work', 'genre:pop', 0.95),
    ('sonata for violin solo no. 1 in g minor, bwv 1001: i. adagio', 'work', 'genre:sonata', 0.95),
    ('sonata for violin solo no. 1 in g minor, bwv 1001: ii. fuga. allegro', 'music_work', 'genre:sonata', 0.95),
    ('song nian yu', 'person', 'genre:mandopop', 0.95),
    ('songbook, vol. 4 - roses', 'album', 'genre:pop', 0.95),
    ('songs about jane', 'album', 'genre:alternative_rock', 0.95),
    ('soul power', 'franchise', 'genre:apple_1143', 0.95),
    ('soul power', 'work', 'genre:apple_1143', 0.95),
    ('souvenir de florence, op. 70', 'music_work', 'genre:classical_music', 0.95),
    ('spirit: stallion of the cimarron', 'work', 'genre:western_film', 0.95),
    ('spirit: stallion of the cimarron (music from the original motion picture)', 'album', 'genre:soundtrack', 0.95),
    ('splatoon', 'franchise', 'genre:video_game', 0.95),
    ('splatoon', 'game', 'genre:video_game', 0.95),
    ('splatoon 3', 'franchise', 'genre:video_game', 0.95),
    ('st john passion', 'franchise', 'genre:oratorio', 0.95),
    ('st john passion, bwv 245', 'franchise', 'genre:baroque', 0.95),
    ('st. matthew passion', 'franchise', 'genre:oratorio', 0.95),
    ('st. matthew''s passion', 'franchise', 'genre:oratorio', 0.95),
    ('star (little prince)', 'music_work', 'genre:anime', 0.95),
    ('starfall (honkai impact 3rd ost - impressions)', 'album', 'genre:anime', 0.95),
    ('statquest', 'franchise', 'subject:computer_science', 0.95),
    ('statquest', 'work', 'subject:computer_science', 0.95),
    ('stay', 'music_work', 'genre:pop', 0.95),
    ('stay with me (feat. hikari)', 'album', 'genre:j_pop', 0.95),
    ('stefanie sun', 'person', 'genre:mandopop', 0.95),
    ('stephen oremus', 'person', 'genre:orchestral', 0.95),
    ('steven universe', 'franchise', 'genre:science_fiction_television_program', 0.95),
    ('steven universe (original soundtrack)', 'album', 'genre:soundtrack', 0.95),
    ('steven universe, vol. 2 (original soundtrack)', 'album', 'genre:soundtrack', 0.95),
    ('still loving you', 'music_work', 'genre:mandopop', 0.95),
    ('strawberry banana club', 'group', 'genre:pop', 0.95),
    ('stre:0ings', 'work', 'genre:tokusatsu', 0.95),
    ('studio choom', 'organization', 'genre:hip_hop', 0.95),
    ('suda kanna', 'person', 'genre:pop', 0.95),
    ('suffa', 'person', 'genre:mandopop', 0.95),
    ('sugar honey ice tea', 'person', 'genre:k_pop', 0.95),
    ('sun xuanyu', 'person', 'genre:mandopop', 0.95),
    ('sunken boat', 'group', 'subject:travel', 0.8),
    ('super! i do!', 'album', 'genre:pop', 0.95),
    ('supernatural', 'franchise', 'genre:horror_film', 0.95),
    ('sword art online', 'franchise', 'genre:science_fiction_television_program', 0.95),
    ('sword of dreams', 'work', 'genre:mandopop', 0.95),
    ('symphony no. 5 in c minor, op. 67', 'music_work', 'genre:symphony', 0.95),
    ('symphony no. 5 in c minor, op. 67; symphony no. 7 in a major, op. 92', 'work', 'genre:symphonic_metal', 0.9),
    ('symphony no. 6', 'work', 'genre:symphonic_metal', 0.8),
    ('taiwan', 'culture', 'subject:travel', 0.8),
    ('take 31', 'work', 'genre:pop', 0.95),
    ('take me as i am', 'music_work', 'genre:pop', 0.95),
    ('take me as i am', 'work', 'genre:pop', 0.95),
    ('talking-the power of soul power', 'franchise', 'genre:apple_1143', 0.95),
    ('talking-the power of soul power - live', 'work', 'genre:apple_1143', 0.95),
    ('tango', 'work', 'genre:latin_pop', 0.95),
    ('tangoz', 'person', 'genre:hip_hop', 0.95),
    ('taped rai', 'album', 'genre:ra', 0.95),
    ('tareefan', 'work', 'genre:romance_film', 0.95),
    ('tchaikovsky', 'person', 'genre:classical', 0.95),
    ('tears in ocean', 'album', 'genre:alternative_rock', 0.95),
    ('ted lo', 'person', 'genre:mandopop', 0.95),
    ('tempo di bourrée', 'work', 'genre:baroque', 0.95),
    ('teng fu-ju', 'person', 'genre:mandopop', 0.95),
    ('teng fu-ju afü', 'group', 'genre:mandopop', 0.95),
    ('teng fu-ru', 'person', 'genre:mandopop', 0.95),
    ('tenryu-ji temple', 'place', 'subject:travel', 0.8),
    ('teresa teng', 'person', 'genre:mandopop', 0.95),
    ('teri baaton mein aisa uljha jiya', 'franchise', 'genre:romance_film', 0.95),
    ('the 6th mini album', 'album', 'genre:k_pop', 0.95),
    ('the aviary', 'album', 'genre:electronic', 0.95),
    ('the bell telephone hour recordings, vol. 3: works by kreisler, haydn & others (live) [remastered 2023]', 'album', 'genre:classical_music', 0.95),
    ('the big bang theory', 'franchise', 'genre:teen_drama_television', 0.95),
    ('the book', 'franchise', 'genre:gamebook', 0.95),
    ('the call of heroes season 4', 'album', 'genre:pop', 0.85),
    ('the civil wars', 'group', 'genre:folk', 0.95),
    ('the crossing', 'album', 'genre:world', 0.95),
    ('the ex-fiancé 3: goodbye ex-fiancé', 'franchise', 'genre:romance_film', 0.95),
    ('the ex-fiancé series', 'franchise', 'genre:romance_film', 0.95),
    ('the fantastic four: first steps', 'work', 'genre:superhero_film', 0.95),
    ('the first take', 'event', 'genre:pop', 0.95),
    ('the first take', 'franchise', 'genre:pop', 0.95),
    ('the girls', 'franchise', 'genre:anime', 0.95),
    ('the giver', 'work', 'genre:teen_film', 0.85),
    ('the great artist', 'work', 'genre:mandopop', 0.95),
    ('the greatest showman', 'franchise', 'genre:musical_film', 0.95),
    ('the hunger games', 'franchise', 'genre:teen_film', 0.95),
    ('the hunger games: songs from district 12 and beyond', 'album', 'genre:soundtrack', 0.95),
    ('the idol', 'franchise', 'genre:pop', 0.95),
    ('the idol episode 4 (music from the hbo original series)', 'album', 'genre:pop', 0.95),
    ('the kreisler album', 'album', 'genre:classical_music', 0.95),
    ('the legend of condor heroes', 'franchise', 'genre:chinese_television_drama', 0.95),
    ('the line-up', 'album', 'genre:cantopop', 0.95),
    ('the loneliest girl', 'music_work', 'genre:anime', 0.95),
    ('the longest day in chang''an', 'franchise', 'genre:historical_film', 0.95),
    ('the moment', 'album', 'genre:mandopop', 0.95),
    ('the monsters', 'group', 'genre:pop', 0.95),
    ('the palazzo', 'organization', 'subject:travel', 0.95),
    ('the planets', 'franchise', 'genre:classical_music', 0.95),
    ('the prosecutor of the ninth department', 'work', 'genre:legal_drama', 0.95),
    ('the protégé', 'album', 'genre:apple_100051', 0.95),
    ('the sheekey science show', 'work', 'subject:science', 0.95),
    ('the venetian resort', 'organization', 'subject:travel', 0.95),
    ('the very best of shostakovich', 'album', 'genre:classical_music', 0.95),
    ('the voice of china', 'franchise', 'genre:mandopop', 0.95),
    ('the working dead', 'work', 'genre:science_fiction_television_program', 0.95),
    ('there''s nothing more we can do', 'work', 'genre:adventure_film', 0.95),
    ('thinking part.1', 'album', 'genre:pop', 0.95),
    ('those who told me not to smoke are dead', 'work', 'genre:protest_song', 0.95),
    ('tian dao', 'music_work', 'genre:anime', 0.95),
    ('tian di you dao', 'music_work', 'genre:mandopop', 0.95),
    ('tian mi', 'person', 'genre:mandopop', 0.95),
    ('till we meet again', 'franchise', 'genre:film_score', 0.95),
    ('to love in the 21st century', 'album', 'genre:pop', 0.95),
    ('tobey maguire as spider-man', 'person', 'genre:superhero_film', 0.95),
    ('toko miura', 'person', 'genre:anime', 0.95),
    ('tokyo', 'culture', 'subject:travel', 0.8),
    ('tokyo', 'place', 'subject:travel', 0.95),
    ('tokyo daylight', 'music_work', 'genre:anime', 0.95),
    ('tokyo ghoul', 'franchise', 'genre:horror_film', 0.95),
    ('tonight sleeping on the street', 'music_work', 'genre:mandopop', 0.95),
    ('tonight sleeping on the street', 'work', 'genre:mandopop', 0.95),
    ('total life forever', 'album', 'genre:apple_1004', 0.95),
    ('trna', 'work', 'subject:biology', 0.95),
    ('trust me', 'work', 'genre:pop', 0.95),
    ('twenty-three', 'album', 'genre:k_pop', 0.95),
    ('twilight', 'franchise', 'genre:teen_film', 0.95),
    ('twilight (franchise)', 'franchise', 'genre:teen_film', 0.95),
    ('twilight realm', 'franchise', 'genre:fantasy_film', 0.95),
    ('twins', 'group', 'genre:pop', 0.95),
    ('tzzzzz', 'person', 'genre:anime', 0.95),
    ('uag', 'franchise', 'genre:pop', 0.95),
    ('ueda akinari', 'person', 'genre:monogatari', 0.95),
    ('ugly beauty', 'album', 'genre:mandopop', 0.95),
    ('und neiget das haupt und verschied', 'work', 'genre:art_song', 0.95),
    ('urlicht', 'music_work', 'genre:classical_music', 0.95),
    ('uta no prince-sama', 'franchise', 'genre:anime', 0.95),
    ('various artists', 'group', 'genre:world', 0.95),
    ('veere di wedding', 'franchise', 'genre:comedy_film', 0.95),
    ('verbal jint', 'person', 'genre:k_pop', 0.95),
    ('vh', 'group', 'genre:pop', 0.85),
    ('vhs diary', 'work', 'genre:documentary_film', 0.95),
    ('violin concerto in c minor, op. 4 no. 10, rv 196', 'work', 'genre:concerto', 0.95),
    ('violin concerto in d major, op. 35', 'franchise', 'genre:concerto', 0.95),
    ('violin concerto in d major, op. 35', 'music_work', 'genre:classical_music', 0.95),
    ('violin concerto in d major, op. 4 no. 11, rv 204: ii. largo', 'work', 'genre:concerto', 0.95),
    ('violin concerto in d minor, op. 4 no. 8, rv 249: iv. allegro', 'work', 'genre:concerto', 0.95),
    ('violin concerto in g major, op. 4 no. 12, rv 298', 'work', 'genre:baroque', 0.95),
    ('violin concerto: ii. aria - hoquet - chorale', 'work', 'genre:classical_music', 0.95),
    ('violin concerto: iv. passacaglia', 'work', 'genre:classical_music', 0.95),
    ('violin partita no. 1 in b minor, bwv 1002: i. allemanda', 'work', 'genre:classical', 0.95),
    ('violin partita no. 2 in d minor, bwv 1004', 'music_work', 'genre:baroque', 0.95),
    ('violin partita no. 2 in d minor, bwv 1004: ii. courante', 'music_work', 'genre:baroque', 0.95),
    ('violin partita no. 2 in d minor, bwv 1004: iii. sarabande', 'work', 'genre:baroque', 0.95),
    ('violin partita no. 2 in d minor, bwv 1004: v. chaconne', 'work', 'genre:baroque', 0.95),
    ('violin partita no. 3 in e major, bwv 1006', 'music_work', 'genre:baroque', 0.95),
    ('violin partita no. 3 in e major, bwv 1006: iv. menuett i', 'music_work', 'genre:baroque', 0.95),
    ('violin partita no. 3 in e major, bwv 1006: iv. menuett i', 'work', 'genre:classical', 0.95),
    ('violin partita no. 3 in e major, bwv 1006: vii. gigue', 'music_work', 'genre:gigue', 0.95),
    ('violin sonata no. 1 in g minor, bwv 1001', 'work', 'genre:sonata', 0.95),
    ('violin sonata no. 2 in a minor, bwv 1003', 'work', 'genre:sonata', 0.95),
    ('violin sonata no. 3 in c major, bwv 1005', 'work', 'genre:sonata', 0.95),
    ('vishal-shekhar', 'group', 'genre:apple_1185', 0.95),
    ('visions of gideon', 'work', 'genre:soundtrack', 0.95),
    ('vitals', 'person', 'genre:pop', 0.95),
    ('voices', 'work', 'genre:vocal', 0.95),
    ('w40th st', 'place', 'subject:travel', 0.9),
    ('wakin chau', 'person', 'genre:mandopop', 0.95),
    ('wan saiwen', 'person', 'genre:mandopop', 0.95),
    ('wan ye wei yu wen hai tang', 'music_work', 'genre:mandopop', 0.95),
    ('wang heye', 'person', 'genre:mandopop', 0.95),
    ('wang linkai', 'person', 'genre:mandopop', 0.95),
    ('wang linyang', 'person', 'genre:pop_punk', 0.95),
    ('wang lixin', 'person', 'genre:mandopop', 0.95),
    ('wang shasha', 'person', 'genre:mandopop', 0.95),
    ('wang sisi', 'person', 'genre:historical_film', 0.95),
    ('wang xiaokun', 'person', 'genre:mandopop', 0.95),
    ('wang xiaowen', 'person', 'genre:mandopop', 0.95),
    ('wang yino', 'person', 'genre:mandopop', 0.95),
    ('want to go where', 'work', 'subject:travel', 0.9),
    ('warner music taiwan', 'organization', 'genre:mandopop', 0.95),
    ('watching movies with you', 'work', 'genre:romance_film', 0.95),
    ('we hate all kinds of violence... - the 1st album', 'album', 'genre:pop', 0.95),
    ('weathering with you', 'franchise', 'genre:romance_film', 0.95),
    ('weathering with you -complete version-', 'album', 'genre:anime', 0.95),
    ('wei liang wu qu', 'music_work', 'genre:mandopop', 0.95),
    ('what if i love you', 'album', 'genre:pop', 0.95),
    ('what if i love you', 'music_work', 'genre:pop', 0.95),
    ('when the sun goes down', 'album', 'genre:pop', 0.95),
    ('when the wind rises', 'album', 'genre:romance_film', 0.95),
    ('where only you and i are', 'work', 'genre:mandopop', 0.95),
    ('where winds meet', 'franchise', 'genre:video_game', 0.95),
    ('where winds meet', 'game', 'genre:action_role_playing_game', 0.95),
    ('white sheep', 'music_work', 'genre:mandopop', 0.95),
    ('who is my groom', 'music_work', 'genre:mandopop', 0.95),
    ('wicked movie cast & ariana grande', 'group', 'genre:musical_film', 0.95),
    ('wicked movie cast & shiz university choir', 'group', 'genre:choral', 0.95),
    ('wicked: the soundtrack', 'album', 'genre:soundtrack', 0.95),
    ('will-o''-the-wisp, babe', 'work', 'genre:children_s_film', 0.95),
    ('wind rising', 'album', 'genre:soundtrack', 0.95),
    ('wing chun', 'work', 'activity:martial_arts', 0.95),
    ('winter whiplash', 'work', 'genre:pop', 0.85),
    ('wo de ren jian yan huo', 'franchise', 'genre:chinese_television_drama', 0.95),
    ('wo pei', 'music_work', 'genre:mandopop', 0.95),
    ('won', 'person', 'genre:k_pop', 0.95),
    ('woni', 'group', 'genre:k_pop', 0.95),
    ('worldbigflameup', 'work', 'genre:tokusatsu', 0.95),
    ('wu jue', 'franchise', 'genre:mandopop', 0.95),
    ('wu niang', 'music_work', 'genre:mandopop', 0.95),
    ('wu xian', 'person', 'genre:mandopop', 0.95),
    ('xi qiang version', 'music_work', 'genre:mandopop', 0.95),
    ('xian di gui lai', 'franchise', 'genre:action_film', 0.85),
    ('xian wai zhi yin', 'music_work', 'genre:mandopop', 0.95),
    ('xiang ni shi feng qi', 'music_work', 'genre:mandopop', 0.95),
    ('xiao ling', 'person', 'genre:mandopop', 0.95),
    ('xiao yiqing', 'person', 'genre:mandopop', 0.95),
    ('xiaoyao le qinghe', 'music_work', 'genre:mandopop', 0.95),
    ('xin di', 'person', 'genre:mandopop', 0.95),
    ('xing ge music', 'organization', 'genre:mandopop', 0.95),
    ('xiu hua zhen', 'music_work', 'genre:mandopop', 0.95),
    ('xu liang', 'person', 'genre:mandopop', 0.95),
    ('xu song', 'person', 'genre:mandopop', 0.95),
    ('xuan ni', 'music_work', 'genre:mandopop', 0.95),
    ('xueshu', 'work', 'genre:wisdom_literature', 0.85),
    ('yama', 'person', 'genre:anime', 0.95),
    ('yan yu ping sheng bu xian xian yu', 'music_work', 'genre:mandopop', 0.95),
    ('yang yo-seob', 'person', 'genre:k_pop', 0.95),
    ('yi dian dian xi huan', 'music_work', 'genre:mandopop', 0.95),
    ('yi pi (pet rebirth edition)', 'album', 'genre:mandopop', 0.95),
    ('yi se fang an', 'work', 'genre:crime_film', 0.95),
    ('yin lin', 'person', 'genre:mandopop', 0.95),
    ('yoo jung-han', 'person', 'genre:k_pop', 0.95),
    ('you are my destiny', 'work', 'genre:mandopop', 0.95),
    ('you can''t be cruel', 'work', 'genre:apple_1143', 0.95),
    ('you sheng zhi nian', 'music_work', 'genre:mandopop', 0.95),
    ('you''re my destiny', 'work', 'genre:mandopop', 0.95),
    ('young sheldon', 'franchise', 'genre:teen_drama_television', 0.95),
    ('youngcaptain', 'person', 'genre:pop_punk', 0.95),
    ('youth soul', 'franchise', 'genre:apple_1143', 0.95),
    ('you殘忍可愛的傲慢', 'work', 'genre:mandopop', 0.95),
    ('yu jiayun', 'person', 'genre:mandopop', 0.95),
    ('yu zhen', 'person', 'genre:mandopop', 0.95),
    ('yu zhen', 'work', 'genre:mandopop', 0.95),
    ('yue lao', 'franchise', 'genre:romance_film', 0.95),
    ('yue lao', 'work', 'genre:romance_film', 0.95),
    ('yue lao (2021 film)', 'franchise', 'genre:romance_film', 0.95),
    ('yue lao (film)', 'franchise', 'genre:romance_film', 0.95),
    ('zach callison', 'person', 'genre:pop', 0.95),
    ('zerfliesse, mein herze, in fluten der zähren', 'work', 'genre:art_song', 0.95),
    ('zero:attitude', 'work', 'genre:hip_hop', 0.95),
    ('zhang qiang', 'person', 'genre:mandopop', 0.95),
    ('zhang siyun', 'person', 'genre:mandopop', 0.95),
    ('zhang yi', 'person', 'genre:legal_drama', 0.95),
    ('zhong qi', 'person', 'genre:mandopop', 0.95),
    ('zhu yu', 'work', 'genre:mandopop', 0.95),
    ('zi cheng yi pai', 'music_work', 'genre:mandopop', 0.95),
    ('zkaaai', 'person', 'genre:mandopop', 0.95),
    ('zou no senaka', 'work', 'genre:animated_film', 0.95),
    ('zou ru', 'person', 'genre:mandopop', 0.95),
    ('zui xue', 'person', 'genre:mandopop', 0.95),
    ('λshes ~returns~', 'music_work', 'genre:soundtrack', 0.95),
    ('不如回家喝自来水 (rock version)', 'music_work', 'genre:rock', 0.95),
    ('世界晚安 good night world (chinese version)', 'work', 'genre:mandopop', 0.95),
    ('亲手sus爱情', 'music_work', 'genre:pop', 0.95),
    ('伎倆', 'music_work', 'genre:pop', 0.95),
    ('你永远不懂我当时的表情', 'music_work', 'genre:mandopop', 0.95),
    ('你的目光 (the way you felt)', 'album', 'genre:mandopop', 0.95),
    ('别再问我什么是迪斯科', 'music_work', 'genre:disco', 0.95),
    ('唯一', 'music_work', 'genre:mandopop', 0.95),
    ('太阳可以是蓝色吗', 'work', 'subject:astronomy', 0.95),
    ('好不容易', 'music_work', 'genre:mandopop', 0.95),
    ('快乐的扑满 (浅影版)', 'work', 'genre:mandopop', 0.95),
    ('感谢你曾来过', 'music_work', 'genre:mandopop', 0.95),
    ('我們與惡的距離', 'franchise', 'genre:legal_drama', 0.95),
    ('我用什么把你留住', 'music_work', 'genre:mandopop', 0.95),
    ('披星戴月的想你', 'music_work', 'genre:mandopop', 0.95),
    ('昨夜風今宵月', 'music_work', 'genre:mandopop', 0.95),
    ('有一天', 'work', 'genre:mandopop', 0.95),
    ('福禄寿', 'group', 'genre:mandopop', 0.95),
    ('良人', 'work', 'genre:mandopop', 0.95),
    ('華燈初上', 'franchise', 'genre:chinese_television_drama', 0.95),
    ('蓄谋的雨季(你蓄谋已久的离开)', 'music_work', 'genre:mandopop', 0.95),
    ('許光漢', 'person', 'genre:mandopop', 0.95),
    ('让她降落', 'music_work', 'genre:mandopop', 0.95),
    ('越來越不懂', 'work', 'genre:mandopop', 0.95),
    ('踮起腳尖愛', 'music_work', 'genre:pop', 0.95),
    ('迟来的情话', 'music_work', 'genre:mandopop', 0.95),
    ('迟来的情话 (0.8x)', 'album', 'genre:mandopop', 0.95),
    ('這世間我唯獨愛你', 'music_work', 'genre:mandopop', 0.95),
    ('那时雨', 'music_work', 'genre:mandopop', 0.95),
    ('釋懷版', 'album', 'genre:mandopop', 0.95),
    ('閉上眼睛一下下', 'music_work', 'genre:pop', 0.95),
    ('驚鴻一面', 'music_work', 'genre:mandopop', 0.95)
  ;
  select string_agg(distinct r.parent_key, ', ') into missing
    from _replacement r
   where not exists (select 1 from ontology.concepts c
                      where c.concept_key = r.parent_key
                        and c.retired_at is null);
  if missing is not null then
    raise notice '0351: headings not held here, skipped: %', missing;
  end if;

  update semantic_private.presumed_terms t
     set proposed_parent_concept_id = c.id,
         proposed_parent_confidence_unvalidated = r.confidence,
         proposed_parent_source = 'placement_pass'
    from _replacement r
    join ontology.concepts c
      on c.concept_key = r.parent_key and c.retired_at is null
   where t.normalized_label = r.normalized_label
     and t.family = r.family
     and coalesce(t.proposed_parent_source, 'placement_pass') = 'placement_pass';
  get diagnostics n = row_count;
  raise notice '0351: % of % re-placements landed', n,
    (select count(*) from _replacement);
  if n = 0 then
    raise exception
      '0351: re-placements were emitted and none matched a term';
  end if;
end;
$$;

