-- 0383 — per-hub placements land: one per hub, many across hubs.
--
-- The owner's rule of 2026-08-25, populated from the four-stage cascade
-- (ris_v20): rung-2, anchor inheritance, within-hub re-place, and the
-- cross-hub second ask that runs wherever a term's anchor lives in a hub the
-- term held no placement in. 369 placements across
-- 0-term multi-hub cases; 370 primary updates with the
-- same lane-guarded semantics as 0351/0352. Measured before emission:
-- holdout misassignment 3.0% under any-placement scoring, anchor
-- incongruence 2.2%.

do $$
declare
  n integer;
  missing text;
begin
  create temporary table _primary
    (normalized_label text, family text, parent_key text, confidence numeric)
    on commit drop;
  insert into _primary values
    ('100 greatest classical songs', 'album', 'genre:classical', 0.95),
    ('1874', 'work', 'genre:mandopop', 0.95),
    ('2025-03-16', 'event', 'genre:k_pop', 0.95),
    ('24 preludes, op. 28', 'franchise', 'genre:piano', 0.95),
    ('24 preludes, op. 28', 'work', 'genre:piano', 0.95),
    ('24 preludes, op. 28: no. 4 in e minor', 'work', 'genre:piano', 0.95),
    ('3. adagio molto e cantabile', 'work', 'genre:orchestral', 0.95),
    ('absolute first album', 'album', 'genre:k_pop', 0.95),
    ('adagio cantabile', 'work', 'genre:piano', 0.95),
    ('adagio sostenuto', 'work', 'genre:piano', 0.95),
    ('aespa', 'franchise', 'genre:k_pop', 0.95),
    ('ai dou', 'person', 'subject:content_creators', 0.95),
    ('aidou', 'person', 'subject:content_creators', 0.95),
    ('allegretto', 'music_work', 'genre:classical', 0.95),
    ('allegretto', 'work', 'genre:piano', 0.95),
    ('allegro', 'work', 'genre:orchestral', 0.95),
    ('allegro maestoso', 'work', 'genre:orchestral', 0.95),
    ('amanda', 'person', 'subject:content_creators', 0.95),
    ('andante [adagio]', 'work', 'genre:baroque', 0.95),
    ('animajinx', 'group', 'subject:content_creators', 0.95),
    ('anime', 'franchise', 'genre:anime', 0.95),
    ('antifragile', 'work', 'genre:k_pop', 0.95),
    ('apple music edition', 'work', 'genre:k_pop', 0.95),
    ('ash', 'music_work', 'genre:k_pop', 0.95),
    ('ash', 'work', 'genre:k_pop', 0.95),
    ('asmongold', 'person', 'subject:content_creators', 0.95),
    ('attitude', 'work', 'genre:k_pop', 0.95),
    ('aung da aung', 'work', 'genre:k_pop', 0.95),
    ('ayayaya', 'work', 'genre:k_pop', 0.95),
    ('babymonster', 'franchise', 'genre:k_pop', 0.95),
    ('babymonster ahyeon', 'person', 'genre:k_pop', 0.95),
    ('babymonster choom', 'work', 'genre:k_pop', 0.95),
    ('babymonster world tour 2026-27', 'tour', 'genre:k_pop', 0.95),
    ('bach''s piano sonatas', 'franchise', 'genre:chamber_music', 0.95),
    ('bach: the well-tempered clavier', 'franchise', 'genre:baroque', 0.95),
    ('bad girl', 'work', 'genre:mandopop', 0.95),
    ('bae', 'person', 'genre:k_pop', 0.95),
    ('baoyu', 'music_work', 'genre:mandopop', 0.95),
    ('baroque duet', 'work', 'genre:baroque', 0.95),
    ('be alright', 'work', 'genre:k_pop', 0.95),
    ('beatpella house', 'franchise', 'genre:k_pop', 0.95),
    ('beethoven sonatas', 'franchise', 'genre:piano', 0.95),
    ('beethoven symphonies', 'franchise', 'genre:orchestral', 0.95),
    ('beethoven: pathétique & moonlight sonatas', 'album', 'genre:piano', 0.95),
    ('beethoven: symphonies nos. 5 & 7', 'album', 'genre:classical', 0.95),
    ('berlin philharmonic & claudio abbado', 'group', 'genre:orchestral', 0.95),
    ('bernstein: mahler', 'album', 'genre:classical', 0.95),
    ('blue valentine', 'work', 'genre:k_pop', 0.95),
    ('boompala', 'work', 'genre:k_pop', 0.95),
    ('born fire', 'music_work', 'genre:k_pop', 0.95),
    ('born fire', 'work', 'genre:k_pop', 0.95),
    ('bwv 244', 'work', 'genre:baroque', 0.95),
    ('caprice viennois, op. 2', 'work', 'genre:violin', 0.95),
    ('chaewon', 'person', 'genre:k_pop', 0.95),
    ('cherish (my love)', 'music_work', 'genre:k_pop', 0.95),
    ('chiyeon', 'person', 'genre:k_pop', 0.95),
    ('choco poodle', 'work', 'genre:k_pop', 0.95),
    ('choi ye-na', 'person', 'subject:content_creators', 0.95),
    ('choi yena', 'person', 'subject:content_creators', 0.95),
    ('choices', 'work', 'genre:k_pop', 0.95),
    ('choom', 'activity', 'genre:k_pop', 0.95),
    ('choom', 'work', 'genre:k_pop', 0.95),
    ('choral', 'work', 'genre:choral', 0.95),
    ('chuu', 'person', 'genre:k_pop', 0.95),
    ('concerto for clarinet and orchestra in a major, k. 622', 'work', 'genre:romantic', 0.95),
    ('concerto in one movement for violin and orchestra transcribed from the 1st movement of the concerto no.1 in d major by niccolò paganini', 'music_work', 'genre:orchestral', 0.95),
    ('concerto no. 4 in f minor', 'work', 'genre:baroque', 0.95),
    ('crazy', 'music_work', 'genre:k_pop', 0.95),
    ('crazy', 'work', 'genre:k_pop', 0.95),
    ('dahlia', 'work', 'genre:k_pop', 0.95),
    ('dance', 'activity', 'genre:dance', 0.95),
    ('dance of the blessed spirits', 'work', 'genre:violin', 0.95),
    ('dang qianxinyi', 'person', 'subject:content_creators', 0.95),
    ('deja vu', 'music_work', 'genre:k_pop', 0.95),
    ('deng jiudiao', 'franchise', 'subject:content_creators', 0.95),
    ('deutsche kammerphilharmonie bremen', 'organization', 'genre:chamber_music', 0.95),
    ('different', 'work', 'genre:k_pop', 0.95),
    ('dingo attack', 'work', 'genre:k_pop', 0.95),
    ('dirty work', 'work', 'genre:k_pop', 0.95),
    ('dmitry shostakovich', 'person', 'genre:classical', 0.95),
    ('double concerto', 'work', 'genre:orchestral', 0.95),
    ('double concerto for violin and cello in a minor, op. 102', 'music_work', 'genre:orchestral', 0.95),
    ('double concerto for violin and cello in a minor, op. 102', 'work', 'genre:classical', 0.95),
    ('easy crazy hot', 'franchise', 'genre:k_pop', 0.95),
    ('egmont', 'work', 'genre:orchestral', 0.95),
    ('either way', 'work', 'genre:k_pop', 0.95),
    ('essentials', 'work', 'genre:classical', 0.95),
    ('eun chae', 'person', 'subject:content_creators', 0.95),
    ('evangelista', 'work', 'genre:classical', 0.95),
    ('eyes on me', 'work', 'genre:k_pop', 0.95),
    ('falling u', 'music_work', 'genre:k_pop', 0.95),
    ('fan hua meng', 'work', 'genre:mandopop', 0.95),
    ('farewell, neverland', 'work', 'genre:k_pop', 0.95),
    ('fearless', 'album', 'genre:k_pop', 0.95),
    ('fearless', 'work', 'genre:k_pop', 0.95),
    ('feng chui cao dong', 'work', 'genre:mandopop', 0.95),
    ('flute concerto in d major, rv 429', 'work', 'genre:baroque', 0.95),
    ('flute concertos', 'work', 'genre:baroque', 0.95),
    ('fu changpeng', 'person', 'subject:content_creators', 0.95),
    ('giacomo puccini', 'person', 'genre:classical', 0.95),
    ('girls', 'work', 'genre:k_pop', 0.95),
    ('girls (aespa)', 'franchise', 'genre:k_pop', 0.95),
    ('girls (franchise)', 'franchise', 'genre:k_pop', 0.95),
    ('girls - the 2nd mini album (apple music edition)', 'franchise', 'genre:k_pop', 0.95),
    ('giselle', 'person', 'genre:k_pop', 0.95),
    ('guanguan', 'person', 'subject:content_creators', 0.95),
    ('hair like snow', 'work', 'genre:mandopop', 0.95),
    ('hands up', 'work', 'genre:k_pop', 0.95),
    ('heo yoon-jin', 'person', 'genre:k_pop', 0.95),
    ('hilary hahn plays bach: violin sonatas nos. 1 & 2; partita no. 1', 'album', 'genre:baroque', 0.95),
    ('hitomi', 'person', 'subject:content_creators', 0.95),
    ('hong eun-chae', 'person', 'genre:k_pop', 0.95),
    ('hot', 'music_work', 'genre:k_pop', 0.95),
    ('hot', 'work', 'genre:k_pop', 0.95),
    ('hot sauce', 'work', 'genre:k_pop', 0.95),
    ('hua tian cuo', 'work', 'genre:mandopop', 0.95),
    ('hui bu hui shi yue guang', 'work', 'genre:mandopop', 0.95),
    ('i burn', 'album', 'genre:k_pop', 0.95),
    ('i burn', 'album', 'genre:k_pop', 0.95),
    ('i don''t like classical music, but i really like this!', 'album', 'genre:classical', 0.95),
    ('i''ll like you', 'album', 'genre:k_pop', 0.95),
    ('i-dle', 'franchise', 'genre:k_pop', 0.95),
    ('i. andante - allegro - tempo i', 'work', 'genre:piano', 0.95),
    ('iconic by mistake', 'music_work', 'genre:k_pop', 0.95),
    ('iii. allegro', 'work', 'genre:baroque', 0.95),
    ('iii. presto', 'music_work', 'genre:classical', 0.95),
    ('illit', 'franchise', 'genre:k_pop', 0.95),
    ('illusion', 'work', 'genre:k_pop', 0.95),
    ('inkigayo', 'event', 'genre:k_pop', 0.95),
    ('introduction & rondo capriccioso in a minor, op. 28', 'music_work', 'genre:classical', 0.95),
    ('invu', 'franchise', 'genre:k_pop', 0.95),
    ('isa', 'person', 'genre:k_pop', 0.95),
    ('it''s me', 'work', 'genre:k_pop', 0.95),
    ('ive', 'franchise', 'genre:k_pop', 0.95),
    ('iz*one', 'franchise', 'genre:k_pop', 0.95),
    ('j.s. bach', 'person', 'genre:baroque', 0.95),
    ('j.s. bach: matthäus-passion, bwv 244', 'album', 'genre:baroque', 0.95),
    ('j.s. bach: matthäus-passion, bwv 244', 'person', 'genre:baroque', 0.95),
    ('j.s. bach: matthäus-passion, bwv 244', 'work', 'genre:baroque', 0.95),
    ('jang won-young', 'person', 'genre:k_pop', 0.95),
    ('jazz suite no. 2: vi. waltz 2', 'work', 'genre:classical', 0.95),
    ('jeewon', 'franchise', 'subject:content_creators', 0.95),
    ('jeffrey tate & berlin philharmonic', 'group', 'genre:classical', 0.95),
    ('jellorio', 'franchise', 'subject:content_creators', 0.95),
    ('jeobok winter', 'person', 'subject:content_creators', 0.95),
    ('ji won', 'person', 'subject:content_creators', 0.95),
    ('ji yu', 'person', 'genre:k_pop', 0.95),
    ('jin', 'person', 'genre:k_pop', 0.95),
    ('jo yu-ri', 'person', 'genre:k_pop', 0.95),
    ('johannes-passion, bwv 245', 'work', 'genre:baroque', 0.95),
    ('josh starmer', 'person', 'subject:content_creators', 0.95),
    ('julie', 'person', 'genre:k_pop', 0.95),
    ('jung ahyeon', 'person', 'genre:k_pop', 0.95),
    ('jupiter (the planets)', 'work', 'genre:classical', 0.95),
    ('k-pop', 'culture', 'genre:k_pop', 0.95),
    ('k-pop', 'franchise', 'genre:k_pop', 0.95),
    ('k-pop boy band collection.1', 'album', 'genre:k_pop', 0.95),
    ('kawaii', 'work', 'genre:k_pop', 0.95),
    ('keyboard concerto no. 1 in d minor, bwv 1052', 'work', 'genre:baroque', 0.95),
    ('kim chae-won', 'person', 'genre:k_pop', 0.95),
    ('kim minju', 'person', 'genre:k_pop', 0.95),
    ('kim winter', 'person', 'genre:k_pop', 0.95),
    ('kiss goodbye', 'work', 'genre:mandopop', 0.95),
    ('kiss n tell', 'album', 'genre:k_pop', 0.95),
    ('kiss n tell', 'work', 'genre:k_pop', 0.95),
    ('kreisler', 'person', 'genre:violin', 0.95),
    ('kreisler plays kreisler', 'album', 'genre:violin', 0.95),
    ('können tränen meiner wangen', 'work', 'genre:baroque', 0.95),
    ('la vie en rose', 'music_work', 'genre:k_pop', 0.95),
    ('le sserafim', 'franchise', 'genre:k_pop', 0.95),
    ('let romance be the master', 'work', 'genre:mandopop', 0.95),
    ('life is hot because of you', 'work', 'genre:mandopop', 0.95),
    ('like that', 'work', 'genre:k_pop', 0.95),
    ('london philharmonic orchestra & itzhak perlman', 'group', 'genre:orchestral', 0.95),
    ('lonely boy', 'music_work', 'genre:k_pop', 0.95),
    ('love dive', 'music_work', 'genre:k_pop', 0.95),
    ('love story', 'music_work', 'genre:k_pop', 0.95),
    ('love, shoot, love gun', 'franchise', 'subject:content_creators', 0.95),
    ('luka', 'person', 'genre:k_pop', 0.95),
    ('mahler', 'franchise', 'genre:orchestral', 0.95),
    ('mahler symphonies', 'franchise', 'genre:orchestral', 0.95),
    ('mahler: symphonien 1–10', 'album', 'genre:orchestral', 0.95),
    ('mahler: symphony no. 5', 'album', 'genre:orchestral', 0.95),
    ('mahler: symphony no. 5', 'work', 'genre:classical', 0.95),
    ('mahler: symphony no. 6', 'album', 'genre:classical', 0.95),
    ('mahler: symphony no. 6', 'work', 'genre:orchestral', 0.95),
    ('malbeokji', 'person', 'genre:k_pop', 0.95),
    ('mamihlapinatapai', 'album', 'genre:k_pop', 0.95),
    ('man re', 'music_work', 'genre:mandopop', 0.95),
    ('mandopop', 'culture', 'genre:mandopop', 0.95),
    ('matthäus-passion', 'work', 'genre:baroque', 0.95),
    ('matthäus-passion, bwv 244', 'work', 'genre:baroque', 0.95),
    ('mbc 2025-03-29', 'event', 'genre:k_pop', 0.95),
    ('memory cotton', 'work', 'genre:mandopop', 0.95),
    ('minisode 3: tomorrow', 'album', 'genre:k_pop', 0.95),
    ('minji', 'person', 'genre:k_pop', 0.95),
    ('minyoung', 'person', 'genre:k_pop', 0.95),
    ('mise-en-scène', 'work', 'genre:k_pop', 0.95),
    ('moonlight sunrise', 'work', 'genre:k_pop', 0.95),
    ('mozart', 'franchise', 'genre:romantic', 0.95),
    ('mozart: requiem', 'album', 'genre:choral', 0.95),
    ('music bank', 'event', 'genre:k_pop', 0.95),
    ('neville marriner', 'person', 'genre:classical', 0.95),
    ('ni ting de dao', 'work', 'genre:mandopop', 0.95),
    ('ningning', 'person', 'genre:k_pop', 0.95),
    ('nmixx', 'franchise', 'genre:k_pop', 0.95),
    ('no turning back', 'album', 'genre:mandopop', 0.95),
    ('no turning back', 'work', 'genre:mandopop', 0.95),
    ('nocturnes, op. 48', 'franchise', 'genre:classical', 0.95),
    ('nocturnes, op. 48: no. 1 in c minor', 'music_work', 'genre:classical', 0.95),
    ('november''s chopin', 'album', 'genre:mandopop', 0.95),
    ('nr.35', 'work', 'genre:baroque', 0.95),
    ('nr.38', 'work', 'genre:choral', 0.95),
    ('nr.65', 'work', 'genre:choral', 0.95),
    ('nun ist der herr zur ruh gebracht', 'work', 'genre:baroque', 0.95),
    ('nv er xin ru shui', 'work', 'genre:mandopop', 0.95),
    ('o sole mio', 'music_work', 'genre:k_pop', 0.95),
    ('o.o', 'work', 'genre:k_pop', 0.95),
    ('orfeo ed euridice', 'work', 'genre:violin', 0.95),
    ('organ sonata no. 4, bwv 528', 'work', 'genre:baroque', 0.95),
    ('our song', 'work', 'genre:mandopop', 0.95),
    ('overdrive', 'work', 'genre:k_pop', 0.95),
    ('pai gu jiao zhu', 'person', 'subject:content_creators', 0.95),
    ('panorama', 'work', 'genre:k_pop', 0.95),
    ('pathétique & moonlight sonatas', 'work', 'genre:piano', 0.95),
    ('peer gynt', 'franchise', 'genre:classical', 0.95),
    ('peer gynt suite no. 1, op. 46: i. morning mood', 'work', 'genre:classical', 0.95),
    ('perfect night', 'work', 'genre:k_pop', 0.95),
    ('petrus aber antwortete', 'work', 'genre:choral', 0.95),
    ('petrus aber sass draussen im palast', 'work', 'genre:choral', 0.95),
    ('pharita', 'work', 'genre:k_pop', 0.95),
    ('piano concerto no. 2 in c minor, op. 18', 'work', 'genre:classical', 0.95),
    ('piano sonata no. 13 in e-flat major, op. 27 no. 1', 'work', 'genre:baroque', 0.95),
    ('piano sonata no. 13 in e-flat major, op. 27 no. 1: ii. allegro molto e vivace', 'work', 'genre:piano', 0.95),
    ('piano sonata no. 13 in e-flat major, op. 27 no. 1: iii. adagio con espressione', 'work', 'genre:piano', 0.95),
    ('piano sonata no. 14 in c-sharp minor, op. 27 no. 2', 'music_work', 'genre:classical', 0.95),
    ('piano sonata no. 14 in c-sharp minor, op. 27 no. 2', 'work', 'genre:piano', 0.95),
    ('piano sonata no. 8 in c minor, op. 13', 'franchise', 'genre:piano', 0.95),
    ('piano sonata no. 8 in c minor, op. 13', 'work', 'genre:classical', 0.95),
    ('polonaise in a-flat major, op. 53', 'work', 'genre:piano', 0.95),
    ('praeludium and allegro', 'work', 'genre:classical', 0.95),
    ('presto', 'work', 'genre:piano', 0.95),
    ('qianying a', 'person', 'subject:content_creators', 0.95),
    ('quanhua shini', 'person', 'subject:content_creators', 0.95),
    ('really like you', 'music_work', 'genre:k_pop', 0.95),
    ('rei', 'person', 'genre:k_pop', 0.95),
    ('requiem aeternam', 'work', 'genre:choral', 0.95),
    ('requiem in d minor, k. 626', 'music_work', 'genre:classical', 0.95),
    ('requiem in d minor, k. 626', 'work', 'genre:choral', 0.95),
    ('requiem in d minor, k. 626: iiic. sequentia. rex tremendae', 'work', 'genre:choral', 0.95),
    ('requiem in d minor, k. 626: ivb. offertorium. hostias', 'music_work', 'genre:choral', 0.95),
    ('requiem in d minor, k. 626: vii. agnus dei', 'music_work', 'genre:choral', 0.95),
    ('resurrection', 'work', 'genre:orchestral', 0.95),
    ('rora', 'person', 'genre:k_pop', 0.95),
    ('rv 297', 'work', 'genre:baroque', 0.95),
    ('sarasate', 'work', 'genre:violin', 0.95),
    ('savage', 'album', 'genre:k_pop', 0.95),
    ('savage', 'franchise', 'genre:k_pop', 0.95),
    ('saymyname', 'organization', 'subject:content_creators', 0.95),
    ('sbs gayo daejeon', 'event', 'genre:k_pop', 0.95),
    ('sbs inkigayo', 'event', 'genre:k_pop', 0.95),
    ('seconda parte: nr.52. aria', 'work', 'genre:baroque', 0.95),
    ('seconda parte: nr.67. recitativo', 'work', 'genre:baroque', 0.95),
    ('secret story of the swan', 'work', 'genre:k_pop', 0.95),
    ('sheesh', 'work', 'genre:k_pop', 0.95),
    ('show! music core', 'event', 'genre:k_pop', 0.95),
    ('shuhua', 'person', 'genre:k_pop', 0.95),
    ('simon rattle', 'person', 'genre:classical', 0.95),
    ('smart', 'work', 'genre:k_pop', 0.95),
    ('sojuwoon', 'person', 'subject:content_creators', 0.95),
    ('solo', 'work', 'genre:k_pop', 0.95),
    ('sonata for violin solo no. 1 in g minor, bwv 1001: i. adagio', 'work', 'genre:baroque', 0.95),
    ('sonatas and partitas for solo violin', 'work', 'genre:baroque', 0.95),
    ('souvenir de florence', 'work', 'genre:classical', 0.95),
    ('spring day', 'work', 'genre:k_pop', 0.95),
    ('st john passion, bwv 245', 'franchise', 'genre:baroque', 0.95),
    ('stage mix', 'work', 'genre:k_pop', 0.95),
    ('starling', 'person', 'subject:content_creators', 0.95),
    ('starling8', 'person', 'subject:content_creators', 0.95),
    ('statquest', 'franchise', 'subject:content_creators', 0.95),
    ('su bai shui xing la', 'person', 'subject:content_creators', 0.95),
    ('sugar rush ride', 'work', 'genre:k_pop', 0.95),
    ('suite: chou fun feng', 'work', 'genre:mandopop', 0.95),
    ('sullyoon', 'person', 'genre:k_pop', 0.95),
    ('symphony no. 1 in d major', 'work', 'genre:orchestral', 0.95),
    ('symphony no. 2 in c minor', 'work', 'genre:orchestral', 0.95),
    ('symphony no. 3 in d minor, erste abteilung: i. kräftig. entschieden', 'work', 'genre:orchestral', 0.95),
    ('symphony no. 3 in d minor, zweite abteilung: iii. comodo. scherzando. ohne hast', 'work', 'genre:classical', 0.95),
    ('symphony no. 3 in d minor, zweite abteilung: iv. sehr langsam. misterioso. durchaus ppp', 'work', 'genre:classical', 0.95),
    ('symphony no. 3 in d minor, zweite abteilung: v. lustig im tempo und keck im ausdruck', 'work', 'genre:orchestral', 0.95),
    ('symphony no. 3 in d minor, zweite abteilung: vi. langsam. ruhevoll. empfunden', 'work', 'genre:classical', 0.95),
    ('symphony no. 5', 'work', 'genre:orchestral', 0.95),
    ('symphony no. 5 in c minor, op. 67', 'music_work', 'genre:orchestral', 0.95),
    ('symphony no. 5 in c-sharp minor', 'music_work', 'genre:orchestral', 0.95),
    ('symphony no. 5 in c-sharp minor: iii. scherzo', 'work', 'genre:orchestral', 0.95),
    ('symphony no. 5 in c-sharp minor: iv. adagietto', 'work', 'genre:orchestral', 0.95),
    ('symphony no. 6', 'work', 'genre:orchestral', 0.95),
    ('symphony no. 6 in a minor', 'work', 'genre:orchestral', 0.95),
    ('symphony no. 9 in d minor, op. 125', 'work', 'genre:orchestral', 0.95),
    ('tchaikovsky (violin concerto & souvenir de florence)', 'album', 'genre:classical', 0.95),
    ('tell me', 'music_work', 'genre:k_pop', 0.95),
    ('the 2nd mini album', 'work', 'genre:k_pop', 0.95),
    ('the awakening', 'franchise', 'genre:k_pop', 0.95),
    ('the four seasons', 'franchise', 'genre:baroque', 0.95),
    ('the four seasons', 'work', 'genre:baroque', 0.95),
    ('the four seasons, concerto no. 4 in f minor, rv 297', 'work', 'genre:baroque', 0.95),
    ('the nutcracker', 'franchise', 'genre:orchestral', 0.95),
    ('the perlman sound', 'album', 'genre:orchestral', 0.95),
    ('the planets', 'franchise', 'genre:classical', 0.95),
    ('the potion seller', 'person', 'subject:content_creators', 0.95),
    ('the very best of shostakovich', 'album', 'genre:classical', 0.95),
    ('the well-tempered clavier', 'franchise', 'genre:piano', 0.95),
    ('toxic', 'music_work', 'genre:k_pop', 0.95),
    ('turandot', 'work', 'genre:classical', 0.95),
    ('txt', 'franchise', 'genre:k_pop', 0.95),
    ('urlicht', 'work', 'genre:orchestral', 0.95),
    ('violeta', 'work', 'genre:k_pop', 0.95),
    ('violin', 'art', 'genre:violin', 0.95),
    ('violin caprices', 'franchise', 'genre:violin', 0.95),
    ('violin concerto in a major, rv 347', 'work', 'genre:baroque', 0.95),
    ('violin concerto in c major, op. 4 no. 7, rv 185', 'work', 'genre:baroque', 0.95),
    ('violin concerto in c minor, op. 4 no. 10, rv 196', 'work', 'genre:baroque', 0.95),
    ('violin concerto in d major, op. 35', 'work', 'genre:orchestral', 0.95),
    ('violin concerto in d major, op. 35: iii. finale. allegro vivacissimo', 'work', 'genre:orchestral', 0.95),
    ('violin concerto in d major, op. 4 no. 11, rv 204', 'work', 'genre:baroque', 0.95),
    ('violin concerto in d major, op. 4 no. 11, rv 204: ii. largo', 'work', 'genre:baroque', 0.95),
    ('violin concerto in d major, op. 4 no. 11, rv 204: iii. allegro assai', 'work', 'genre:baroque', 0.95),
    ('violin concerto in d major, op. 77', 'music_work', 'genre:orchestral', 0.95),
    ('violin concerto in d major, op. 77', 'work', 'genre:orchestral', 0.95),
    ('violin concerto in d minor, op. 4 no. 8, rv 249', 'work', 'genre:baroque', 0.95),
    ('violin concerto in d minor, op. 4 no. 8, rv 249: iv. allegro', 'work', 'genre:baroque', 0.95),
    ('violin concerto in d minor, op. 47', 'work', 'genre:orchestral', 0.95),
    ('violin concerto in f major, op. 4 no. 9, rv 284', 'work', 'genre:baroque', 0.95),
    ('violin concerto in g major, op. 4 no. 12, rv 298', 'work', 'genre:baroque', 0.95),
    ('violin concerto no. 1 in a minor, bwv 1041', 'work', 'genre:baroque', 0.95),
    ('violin concerto no. 1 in b-flat major, k. 207: iii. presto', 'work', 'genre:classical', 0.95),
    ('violin concerto no. 5', 'work', 'genre:violin', 0.95),
    ('violin concerto no. 5 in f major, op. 91: v. appassionato (cadenza by adès)', 'work', 'genre:orchestral', 0.95),
    ('violin concerto: i. praeludium', 'work', 'genre:orchestral', 0.95),
    ('violin concerto: iv. passacaglia', 'work', 'genre:violin', 0.95),
    ('violin concertos & violin romances', 'album', 'genre:violin', 0.95),
    ('violin sonata no. 1 in g minor, bwv 1001', 'work', 'genre:chamber_music', 0.95),
    ('violin sonata no. 2 in a minor, bwv 1003', 'work', 'genre:chamber_music', 0.95),
    ('violin sonata no. 3 in c major, bwv 1005', 'work', 'genre:baroque', 0.95),
    ('violin sonatas nos. 1 & 2', 'work', 'genre:chamber_music', 0.95),
    ('violin sonatas nos. 1 & 2; partita no. 1', 'work', 'genre:baroque', 0.95),
    ('visualsounds1', 'person', 'subject:content_creators', 0.95),
    ('visualsounds1 asmr', 'organization', 'subject:content_creators', 0.95),
    ('vivaldi: the four seasons', 'album', 'genre:baroque', 0.95),
    ('waltz of the flowers', 'music_work', 'genre:orchestral', 0.95),
    ('wannabe', 'franchise', 'genre:k_pop', 0.95),
    ('we go up', 'work', 'genre:k_pop', 0.95),
    ('white sheep', 'work', 'genre:mandopop', 0.95),
    ('who is my groom', 'work', 'genre:mandopop', 0.95),
    ('winter', 'work', 'genre:baroque', 0.95),
    ('wo lian ai le', 'work', 'genre:mandopop', 0.95),
    ('wonder girls', 'group', 'genre:k_pop', 0.95),
    ('xiao yu', 'work', 'genre:mandopop', 0.95),
    ('xoxz', 'work', 'genre:k_pop', 0.95),
    ('xu chenglong', 'person', 'subject:content_creators', 0.95),
    ('yishan', 'person', 'subject:content_creators', 0.95),
    ('you & i', 'work', 'genre:k_pop', 0.95),
    ('yuanlai aiqing bushi xihuan', 'music_work', 'genre:mandopop', 0.95),
    ('yue lai yue bu dong', 'work', 'genre:mandopop', 0.95),
    ('yuqi', 'person', 'genre:k_pop', 0.95),
    ('yuttchaco', 'person', 'subject:content_creators', 0.95),
    ('zero:attitude', 'work', 'genre:k_pop', 0.95),
    ('zigeunerweisen, op. 20', 'work', 'genre:orchestral', 0.95),
    ('你不知道的事', 'work', 'genre:mandopop', 0.95),
    ('춤 (choom)', 'album', 'genre:k_pop', 0.95)
  ;
  select string_agg(distinct p.parent_key, ', ') into missing
    from _primary p
   where not exists (select 1 from ontology.concepts c
                      where c.concept_key = p.parent_key
                        and c.retired_at is null);
  if missing is not null then
    raise notice '0383: primary headings not held here, skipped: %', missing;
  end if;

  update semantic_private.presumed_terms t
     set proposed_parent_concept_id = c.id,
         proposed_parent_confidence_unvalidated = p.confidence,
         proposed_parent_source = 'placement_pass'
    from _primary p
    join ontology.concepts c
      on c.concept_key = p.parent_key and c.retired_at is null
   where t.normalized_label = p.normalized_label
     and t.family = p.family
     and coalesce(t.proposed_parent_source, 'placement_pass') = 'placement_pass';
  get diagnostics n = row_count;
  raise notice '0383: % primary placements landed', n;

  create temporary table _placement
    (normalized_label text, family text, parent_key text, hub_key text,
     confidence numeric, source text)
    on commit drop;
  insert into _placement values
    ('100 greatest classical songs', 'album', 'genre:classical', 'hub:music', 0.95, 'placement_pass'),
    ('1874', 'work', 'genre:mandopop', 'hub:music', 0.95, 'inherited'),
    ('2025-03-16', 'event', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('24 preludes, op. 28', 'franchise', 'genre:piano', 'hub:music', 0.95, 'placement_pass'),
    ('24 preludes, op. 28', 'work', 'genre:piano', 'hub:music', 0.95, 'placement_pass'),
    ('24 preludes, op. 28: no. 4 in e minor', 'work', 'genre:piano', 'hub:music', 0.95, 'inherited'),
    ('3. adagio molto e cantabile', 'work', 'genre:orchestral', 'hub:music', 0.95, 'inherited'),
    ('absolute first album', 'album', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('adagio cantabile', 'work', 'genre:piano', 'hub:music', 0.95, 'placement_pass'),
    ('adagio sostenuto', 'work', 'genre:piano', 'hub:music', 0.95, 'placement_pass'),
    ('aespa', 'franchise', 'genre:k_pop', 'hub:music', 0.95, 'placement_pass'),
    ('ai dou', 'person', 'subject:content_creators', 'subject:content_creators', 0.95, 'placement_pass'),
    ('aidou', 'person', 'subject:content_creators', 'subject:content_creators', 0.95, 'placement_pass'),
    ('allegretto', 'music_work', 'genre:classical', 'hub:music', 0.95, 'inherited'),
    ('allegretto', 'work', 'genre:piano', 'hub:music', 0.95, 'placement_pass'),
    ('allegro', 'work', 'genre:orchestral', 'hub:music', 0.95, 'placement_pass'),
    ('allegro maestoso', 'work', 'genre:orchestral', 'hub:music', 0.95, 'inherited'),
    ('amanda', 'person', 'subject:content_creators', 'subject:content_creators', 0.95, 'placement_pass'),
    ('andante [adagio]', 'work', 'genre:baroque', 'hub:music', 0.95, 'inherited'),
    ('animajinx', 'group', 'subject:content_creators', 'subject:content_creators', 0.95, 'placement_pass'),
    ('anime', 'franchise', 'genre:anime', 'hub:music', 0.95, 'placement_pass'),
    ('antifragile', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('apple music edition', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('ash', 'music_work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('ash', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('asmongold', 'person', 'subject:content_creators', 'subject:content_creators', 0.95, 'placement_pass'),
    ('attitude', 'work', 'genre:k_pop', 'hub:music', 0.95, 'placement_pass'),
    ('aung da aung', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('ayayaya', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('babymonster', 'franchise', 'genre:k_pop', 'hub:music', 0.95, 'placement_pass'),
    ('babymonster ahyeon', 'person', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('babymonster choom', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('babymonster world tour 2026-27', 'tour', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('bach''s piano sonatas', 'franchise', 'genre:chamber_music', 'hub:music', 0.95, 'placement_pass'),
    ('bach: the well-tempered clavier', 'franchise', 'genre:baroque', 'hub:music', 0.95, 'placement_pass'),
    ('bad girl', 'work', 'genre:mandopop', 'hub:music', 0.95, 'placement_pass'),
    ('bae', 'person', 'genre:k_pop', 'hub:music', 0.95, 'placement_pass'),
    ('baoyu', 'music_work', 'genre:mandopop', 'hub:music', 0.95, 'inherited'),
    ('baroque duet', 'work', 'genre:baroque', 'hub:music', 0.95, 'placement_pass'),
    ('be alright', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('beatpella house', 'franchise', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('beethoven sonatas', 'franchise', 'genre:piano', 'hub:music', 0.95, 'placement_pass'),
    ('beethoven symphonies', 'franchise', 'genre:orchestral', 'hub:music', 0.95, 'placement_pass'),
    ('beethoven: pathétique & moonlight sonatas', 'album', 'genre:piano', 'hub:music', 0.95, 'placement_pass'),
    ('beethoven: symphonies nos. 5 & 7', 'album', 'genre:classical', 'hub:music', 0.95, 'placement_pass'),
    ('berlin philharmonic & claudio abbado', 'group', 'genre:orchestral', 'hub:music', 0.95, 'placement_pass'),
    ('bernstein: mahler', 'album', 'genre:classical', 'hub:music', 0.95, 'placement_pass'),
    ('blue valentine', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('boompala', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('born fire', 'music_work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('born fire', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('bwv 244', 'work', 'genre:baroque', 'hub:music', 0.95, 'inherited'),
    ('caprice viennois, op. 2', 'work', 'genre:violin', 'hub:music', 0.95, 'inherited'),
    ('chaewon', 'person', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('cherish (my love)', 'music_work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('chiyeon', 'person', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('choco poodle', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('choi ye-na', 'person', 'subject:content_creators', 'subject:content_creators', 0.95, 'placement_pass'),
    ('choi yena', 'person', 'subject:content_creators', 'subject:content_creators', 0.95, 'placement_pass'),
    ('choices', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('choom', 'activity', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('choom', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('choral', 'work', 'genre:choral', 'hub:music', 0.95, 'placement_pass'),
    ('chuu', 'person', 'genre:k_pop', 'hub:music', 0.95, 'placement_pass'),
    ('concerto for clarinet and orchestra in a major, k. 622', 'work', 'genre:romantic', 'hub:music', 0.95, 'inherited'),
    ('concerto in one movement for violin and orchestra transcribed from the 1st movement of the concerto no.1 in d major by niccolò paganini', 'music_work', 'genre:orchestral', 'hub:music', 0.95, 'placement_pass'),
    ('concerto no. 4 in f minor', 'work', 'genre:baroque', 'hub:music', 0.95, 'placement_pass'),
    ('crazy', 'music_work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('crazy', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('dahlia', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('dance', 'activity', 'genre:dance', 'hub:music', 0.95, 'placement_pass'),
    ('dance of the blessed spirits', 'work', 'genre:violin', 'hub:music', 0.95, 'inherited'),
    ('dang qianxinyi', 'person', 'subject:content_creators', 'subject:content_creators', 0.95, 'placement_pass'),
    ('deja vu', 'music_work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('deng jiudiao', 'franchise', 'subject:content_creators', 'subject:content_creators', 0.95, 'placement_pass'),
    ('deutsche kammerphilharmonie bremen', 'organization', 'genre:chamber_music', 'hub:music', 0.95, 'placement_pass'),
    ('different', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('dingo attack', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('dirty work', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('dmitry shostakovich', 'person', 'genre:classical', 'hub:music', 0.95, 'placement_pass'),
    ('double concerto', 'work', 'genre:orchestral', 'hub:music', 0.95, 'placement_pass'),
    ('double concerto for violin and cello in a minor, op. 102', 'music_work', 'genre:orchestral', 'hub:music', 0.95, 'placement_pass'),
    ('double concerto for violin and cello in a minor, op. 102', 'work', 'genre:classical', 'hub:music', 0.95, 'placement_pass'),
    ('easy crazy hot', 'franchise', 'genre:k_pop', 'hub:music', 0.95, 'placement_pass'),
    ('egmont', 'work', 'genre:orchestral', 'hub:music', 0.95, 'placement_pass'),
    ('either way', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('essentials', 'work', 'genre:classical', 'hub:music', 0.95, 'placement_pass'),
    ('eun chae', 'person', 'subject:content_creators', 'subject:content_creators', 0.95, 'placement_pass'),
    ('evangelista', 'work', 'genre:classical', 'hub:music', 0.95, 'inherited'),
    ('eyes on me', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('falling u', 'music_work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('fan hua meng', 'work', 'genre:mandopop', 'hub:music', 0.95, 'inherited'),
    ('farewell, neverland', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('fearless', 'album', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('fearless', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('feng chui cao dong', 'work', 'genre:mandopop', 'hub:music', 0.95, 'inherited'),
    ('flute concerto in d major, rv 429', 'work', 'genre:baroque', 'hub:music', 0.95, 'placement_pass'),
    ('flute concertos', 'work', 'genre:baroque', 'hub:music', 0.95, 'placement_pass'),
    ('fu changpeng', 'person', 'subject:content_creators', 'subject:content_creators', 0.95, 'placement_pass'),
    ('giacomo puccini', 'person', 'genre:classical', 'hub:music', 0.95, 'placement_pass'),
    ('girls', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('girls (aespa)', 'franchise', 'genre:k_pop', 'hub:music', 0.95, 'placement_pass'),
    ('girls (franchise)', 'franchise', 'genre:k_pop', 'hub:music', 0.95, 'placement_pass'),
    ('girls - the 2nd mini album (apple music edition)', 'franchise', 'genre:k_pop', 'hub:music', 0.95, 'placement_pass'),
    ('giselle', 'person', 'genre:k_pop', 'hub:music', 0.95, 'placement_pass'),
    ('guanguan', 'person', 'subject:content_creators', 'subject:content_creators', 0.95, 'placement_pass'),
    ('hair like snow', 'work', 'genre:mandopop', 'hub:music', 0.95, 'inherited'),
    ('hands up', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('heo yoon-jin', 'person', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('hilary hahn plays bach: violin sonatas nos. 1 & 2; partita no. 1', 'album', 'genre:baroque', 'hub:music', 0.95, 'placement_pass'),
    ('hitomi', 'person', 'subject:content_creators', 'subject:content_creators', 0.95, 'placement_pass'),
    ('hong eun-chae', 'person', 'genre:k_pop', 'hub:music', 0.95, 'placement_pass'),
    ('hot', 'music_work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('hot', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('hot sauce', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('hua tian cuo', 'work', 'genre:mandopop', 'hub:music', 0.95, 'inherited'),
    ('hui bu hui shi yue guang', 'work', 'genre:mandopop', 'hub:music', 0.95, 'inherited'),
    ('i burn', 'album', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('i don''t like classical music, but i really like this!', 'album', 'genre:classical', 'hub:music', 0.95, 'placement_pass'),
    ('i''ll like you', 'album', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('i-dle', 'franchise', 'genre:k_pop', 'hub:music', 0.95, 'placement_pass'),
    ('i. andante - allegro - tempo i', 'work', 'genre:piano', 'hub:music', 0.95, 'placement_pass'),
    ('iconic by mistake', 'music_work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('iii. allegro', 'work', 'genre:baroque', 'hub:music', 0.95, 'inherited'),
    ('iii. presto', 'music_work', 'genre:classical', 'hub:music', 0.95, 'inherited'),
    ('illit', 'franchise', 'genre:k_pop', 'hub:music', 0.95, 'placement_pass'),
    ('illusion', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('inkigayo', 'event', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('introduction & rondo capriccioso in a minor, op. 28', 'music_work', 'genre:classical', 'hub:music', 0.95, 'placement_pass'),
    ('invu', 'franchise', 'genre:k_pop', 'hub:music', 0.95, 'placement_pass'),
    ('isa', 'person', 'genre:k_pop', 'hub:music', 0.95, 'placement_pass'),
    ('it''s me', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('ive', 'franchise', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('iz*one', 'franchise', 'genre:k_pop', 'hub:music', 0.95, 'placement_pass'),
    ('j.s. bach', 'person', 'genre:baroque', 'hub:music', 0.95, 'placement_pass'),
    ('j.s. bach: matthäus-passion, bwv 244', 'album', 'genre:baroque', 'hub:music', 0.95, 'inherited'),
    ('j.s. bach: matthäus-passion, bwv 244', 'person', 'genre:baroque', 'hub:music', 0.95, 'placement_pass'),
    ('j.s. bach: matthäus-passion, bwv 244', 'work', 'genre:baroque', 'hub:music', 0.95, 'placement_pass'),
    ('jang won-young', 'person', 'genre:k_pop', 'hub:music', 0.95, 'placement_pass'),
    ('jazz suite no. 2: vi. waltz 2', 'work', 'genre:classical', 'hub:music', 0.95, 'inherited'),
    ('jeewon', 'franchise', 'subject:content_creators', 'subject:content_creators', 0.95, 'placement_pass'),
    ('jeffrey tate & berlin philharmonic', 'group', 'genre:classical', 'hub:music', 0.95, 'placement_pass'),
    ('jellorio', 'franchise', 'subject:content_creators', 'subject:content_creators', 0.95, 'placement_pass'),
    ('jeobok winter', 'person', 'subject:content_creators', 'subject:content_creators', 0.95, 'placement_pass'),
    ('ji won', 'person', 'subject:content_creators', 'subject:content_creators', 0.95, 'placement_pass'),
    ('ji yu', 'person', 'genre:k_pop', 'hub:music', 0.95, 'placement_pass'),
    ('jin', 'person', 'genre:k_pop', 'hub:music', 0.95, 'placement_pass'),
    ('jo yu-ri', 'person', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('johannes-passion, bwv 245', 'work', 'genre:baroque', 'hub:music', 0.95, 'inherited'),
    ('josh starmer', 'person', 'subject:content_creators', 'subject:content_creators', 0.95, 'placement_pass'),
    ('julie', 'person', 'genre:k_pop', 'hub:music', 0.95, 'placement_pass'),
    ('jung ahyeon', 'person', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('jupiter (the planets)', 'work', 'genre:classical', 'hub:music', 0.95, 'inherited'),
    ('k-pop', 'culture', 'genre:k_pop', 'hub:music', 0.95, 'placement_pass'),
    ('k-pop', 'franchise', 'genre:k_pop', 'hub:music', 0.95, 'placement_pass'),
    ('k-pop boy band collection.1', 'album', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('kawaii', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('keyboard concerto no. 1 in d minor, bwv 1052', 'work', 'genre:baroque', 'hub:music', 0.95, 'placement_pass'),
    ('kim chae-won', 'person', 'genre:k_pop', 'hub:music', 0.95, 'placement_pass'),
    ('kim minju', 'person', 'genre:k_pop', 'hub:music', 0.95, 'placement_pass'),
    ('kim winter', 'person', 'genre:k_pop', 'hub:music', 0.95, 'placement_pass'),
    ('kiss goodbye', 'work', 'genre:mandopop', 'hub:music', 0.95, 'inherited'),
    ('kiss n tell', 'album', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('kiss n tell', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('kreisler', 'person', 'genre:violin', 'hub:music', 0.95, 'placement_pass'),
    ('kreisler plays kreisler', 'album', 'genre:violin', 'hub:music', 0.95, 'placement_pass'),
    ('können tränen meiner wangen', 'work', 'genre:baroque', 'hub:music', 0.95, 'inherited'),
    ('la vie en rose', 'music_work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('le sserafim', 'franchise', 'genre:k_pop', 'hub:music', 0.95, 'placement_pass'),
    ('let romance be the master', 'work', 'genre:mandopop', 'hub:music', 0.95, 'inherited'),
    ('life is hot because of you', 'work', 'genre:mandopop', 'hub:music', 0.95, 'inherited'),
    ('like that', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('london philharmonic orchestra & itzhak perlman', 'group', 'genre:orchestral', 'hub:music', 0.95, 'placement_pass'),
    ('lonely boy', 'music_work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('love dive', 'music_work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('love story', 'music_work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('love, shoot, love gun', 'franchise', 'subject:content_creators', 'subject:content_creators', 0.95, 'placement_pass'),
    ('luka', 'person', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('mahler', 'franchise', 'genre:orchestral', 'hub:music', 0.95, 'placement_pass'),
    ('mahler symphonies', 'franchise', 'genre:orchestral', 'hub:music', 0.95, 'placement_pass'),
    ('mahler: symphonien 1–10', 'album', 'genre:orchestral', 'hub:music', 0.95, 'inherited'),
    ('mahler: symphony no. 5', 'album', 'genre:orchestral', 'hub:music', 0.95, 'inherited'),
    ('mahler: symphony no. 5', 'work', 'genre:classical', 'hub:music', 0.95, 'placement_pass'),
    ('mahler: symphony no. 6', 'album', 'genre:classical', 'hub:music', 0.95, 'placement_pass'),
    ('mahler: symphony no. 6', 'work', 'genre:orchestral', 'hub:music', 0.95, 'inherited'),
    ('malbeokji', 'person', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('mamihlapinatapai', 'album', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('man re', 'music_work', 'genre:mandopop', 'hub:music', 0.95, 'inherited'),
    ('mandopop', 'culture', 'genre:mandopop', 'hub:music', 0.95, 'placement_pass'),
    ('matthäus-passion', 'work', 'genre:baroque', 'hub:music', 0.95, 'inherited'),
    ('matthäus-passion, bwv 244', 'work', 'genre:baroque', 'hub:music', 0.95, 'inherited'),
    ('mbc 2025-03-29', 'event', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('memory cotton', 'work', 'genre:mandopop', 'hub:music', 0.95, 'inherited'),
    ('minisode 3: tomorrow', 'album', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('minji', 'person', 'genre:k_pop', 'hub:music', 0.95, 'placement_pass'),
    ('minyoung', 'person', 'genre:k_pop', 'hub:music', 0.95, 'placement_pass'),
    ('mise-en-scène', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('moonlight sunrise', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('mozart', 'franchise', 'genre:romantic', 'hub:music', 0.95, 'placement_pass'),
    ('mozart: requiem', 'album', 'genre:choral', 'hub:music', 0.95, 'placement_pass'),
    ('music bank', 'event', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('neville marriner', 'person', 'genre:classical', 'hub:music', 0.95, 'placement_pass'),
    ('ni ting de dao', 'work', 'genre:mandopop', 'hub:music', 0.95, 'placement_pass'),
    ('ningning', 'person', 'genre:k_pop', 'hub:music', 0.95, 'placement_pass'),
    ('nmixx', 'franchise', 'genre:k_pop', 'hub:music', 0.95, 'placement_pass'),
    ('no turning back', 'album', 'genre:mandopop', 'hub:music', 0.95, 'inherited'),
    ('no turning back', 'work', 'genre:mandopop', 'hub:music', 0.95, 'inherited'),
    ('nocturnes, op. 48', 'franchise', 'genre:classical', 'hub:music', 0.95, 'placement_pass'),
    ('nocturnes, op. 48: no. 1 in c minor', 'music_work', 'genre:classical', 'hub:music', 0.95, 'placement_pass'),
    ('november''s chopin', 'album', 'genre:mandopop', 'hub:music', 0.95, 'placement_pass'),
    ('nr.35', 'work', 'genre:baroque', 'hub:music', 0.95, 'placement_pass'),
    ('nr.38', 'work', 'genre:choral', 'hub:music', 0.95, 'placement_pass'),
    ('nr.65', 'work', 'genre:choral', 'hub:music', 0.95, 'placement_pass'),
    ('nun ist der herr zur ruh gebracht', 'work', 'genre:baroque', 'hub:music', 0.95, 'inherited'),
    ('nv er xin ru shui', 'work', 'genre:mandopop', 'hub:music', 0.95, 'inherited'),
    ('o sole mio', 'music_work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('o.o', 'work', 'genre:k_pop', 'hub:music', 0.95, 'placement_pass'),
    ('orfeo ed euridice', 'work', 'genre:violin', 'hub:music', 0.95, 'inherited'),
    ('organ sonata no. 4, bwv 528', 'work', 'genre:baroque', 'hub:music', 0.95, 'placement_pass'),
    ('our song', 'work', 'genre:mandopop', 'hub:music', 0.95, 'inherited'),
    ('overdrive', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('pai gu jiao zhu', 'person', 'subject:content_creators', 'subject:content_creators', 0.95, 'placement_pass'),
    ('panorama', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('pathétique & moonlight sonatas', 'work', 'genre:piano', 'hub:music', 0.95, 'placement_pass'),
    ('peer gynt', 'franchise', 'genre:classical', 'hub:music', 0.95, 'inherited'),
    ('peer gynt suite no. 1, op. 46: i. morning mood', 'work', 'genre:classical', 'hub:music', 0.95, 'inherited'),
    ('perfect night', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('petrus aber antwortete', 'work', 'genre:choral', 'hub:music', 0.95, 'placement_pass'),
    ('petrus aber sass draussen im palast', 'work', 'genre:choral', 'hub:music', 0.95, 'inherited'),
    ('pharita', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('piano concerto no. 2 in c minor, op. 18', 'work', 'genre:classical', 'hub:music', 0.95, 'placement_pass'),
    ('piano sonata no. 13 in e-flat major, op. 27 no. 1', 'work', 'genre:baroque', 'hub:music', 0.95, 'inherited'),
    ('piano sonata no. 13 in e-flat major, op. 27 no. 1: ii. allegro molto e vivace', 'work', 'genre:piano', 'hub:music', 0.95, 'inherited'),
    ('piano sonata no. 13 in e-flat major, op. 27 no. 1: iii. adagio con espressione', 'work', 'genre:piano', 'hub:music', 0.95, 'placement_pass'),
    ('piano sonata no. 14 in c-sharp minor, op. 27 no. 2', 'music_work', 'genre:classical', 'hub:music', 0.95, 'placement_pass'),
    ('piano sonata no. 14 in c-sharp minor, op. 27 no. 2', 'work', 'genre:piano', 'hub:music', 0.95, 'inherited'),
    ('piano sonata no. 8 in c minor, op. 13', 'franchise', 'genre:piano', 'hub:music', 0.95, 'inherited'),
    ('piano sonata no. 8 in c minor, op. 13', 'work', 'genre:classical', 'hub:music', 0.95, 'placement_pass'),
    ('polonaise in a-flat major, op. 53', 'work', 'genre:piano', 'hub:music', 0.95, 'placement_pass'),
    ('praeludium and allegro', 'work', 'genre:classical', 'hub:music', 0.95, 'placement_pass'),
    ('presto', 'work', 'genre:piano', 'hub:music', 0.95, 'placement_pass'),
    ('qianying a', 'person', 'subject:content_creators', 'subject:content_creators', 0.95, 'placement_pass'),
    ('quanhua shini', 'person', 'subject:content_creators', 'subject:content_creators', 0.95, 'placement_pass'),
    ('really like you', 'music_work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('rei', 'person', 'genre:k_pop', 'hub:music', 0.95, 'placement_pass'),
    ('requiem aeternam', 'work', 'genre:choral', 'hub:music', 0.95, 'inherited'),
    ('requiem in d minor, k. 626', 'music_work', 'genre:classical', 'hub:music', 0.95, 'placement_pass'),
    ('requiem in d minor, k. 626', 'work', 'genre:choral', 'hub:music', 0.95, 'placement_pass'),
    ('requiem in d minor, k. 626: iiic. sequentia. rex tremendae', 'work', 'genre:choral', 'hub:music', 0.95, 'inherited'),
    ('requiem in d minor, k. 626: ivb. offertorium. hostias', 'music_work', 'genre:choral', 'hub:music', 0.95, 'inherited'),
    ('requiem in d minor, k. 626: vii. agnus dei', 'music_work', 'genre:choral', 'hub:music', 0.95, 'inherited'),
    ('resurrection', 'work', 'genre:orchestral', 'hub:music', 0.95, 'inherited'),
    ('rora', 'person', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('rv 297', 'work', 'genre:baroque', 'hub:music', 0.95, 'inherited'),
    ('sarasate', 'work', 'genre:violin', 'hub:music', 0.95, 'placement_pass'),
    ('savage', 'album', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('savage', 'franchise', 'genre:k_pop', 'hub:music', 0.95, 'placement_pass'),
    ('saymyname', 'organization', 'subject:content_creators', 'subject:content_creators', 0.95, 'placement_pass'),
    ('sbs gayo daejeon', 'event', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('sbs inkigayo', 'event', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('seconda parte: nr.52. aria', 'work', 'genre:baroque', 'hub:music', 0.95, 'placement_pass'),
    ('seconda parte: nr.67. recitativo', 'work', 'genre:baroque', 'hub:music', 0.95, 'placement_pass'),
    ('secret story of the swan', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('sheesh', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('show! music core', 'event', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('shuhua', 'person', 'genre:k_pop', 'hub:music', 0.95, 'placement_pass'),
    ('simon rattle', 'person', 'genre:classical', 'hub:music', 0.95, 'placement_pass'),
    ('smart', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('sojuwoon', 'person', 'subject:content_creators', 'subject:content_creators', 0.95, 'placement_pass'),
    ('solo', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('sonata for violin solo no. 1 in g minor, bwv 1001: i. adagio', 'work', 'genre:baroque', 'hub:music', 0.95, 'placement_pass'),
    ('sonatas and partitas for solo violin', 'work', 'genre:baroque', 'hub:music', 0.95, 'placement_pass'),
    ('souvenir de florence', 'work', 'genre:classical', 'hub:music', 0.95, 'placement_pass'),
    ('spring day', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('st john passion, bwv 245', 'franchise', 'genre:baroque', 'hub:music', 0.95, 'placement_pass'),
    ('stage mix', 'work', 'genre:k_pop', 'hub:music', 0.95, 'placement_pass'),
    ('starling', 'person', 'subject:content_creators', 'subject:content_creators', 0.95, 'placement_pass'),
    ('starling8', 'person', 'subject:content_creators', 'subject:content_creators', 0.95, 'placement_pass'),
    ('statquest', 'franchise', 'subject:content_creators', 'subject:content_creators', 0.95, 'placement_pass'),
    ('su bai shui xing la', 'person', 'subject:content_creators', 'subject:content_creators', 0.95, 'placement_pass'),
    ('sugar rush ride', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('suite: chou fun feng', 'work', 'genre:mandopop', 'hub:music', 0.95, 'placement_pass'),
    ('sullyoon', 'person', 'genre:k_pop', 'hub:music', 0.95, 'placement_pass'),
    ('symphony no. 1 in d major', 'work', 'genre:orchestral', 'hub:music', 0.95, 'placement_pass'),
    ('symphony no. 2 in c minor', 'work', 'genre:orchestral', 'hub:music', 0.95, 'placement_pass'),
    ('symphony no. 3 in d minor, erste abteilung: i. kräftig. entschieden', 'work', 'genre:orchestral', 'hub:music', 0.95, 'placement_pass'),
    ('symphony no. 3 in d minor, zweite abteilung: iii. comodo. scherzando. ohne hast', 'work', 'genre:classical', 'hub:music', 0.95, 'placement_pass'),
    ('symphony no. 3 in d minor, zweite abteilung: iv. sehr langsam. misterioso. durchaus ppp', 'work', 'genre:classical', 'hub:music', 0.95, 'placement_pass'),
    ('symphony no. 3 in d minor, zweite abteilung: v. lustig im tempo und keck im ausdruck', 'work', 'genre:orchestral', 'hub:music', 0.95, 'inherited'),
    ('symphony no. 3 in d minor, zweite abteilung: vi. langsam. ruhevoll. empfunden', 'work', 'genre:classical', 'hub:music', 0.95, 'placement_pass'),
    ('symphony no. 5', 'work', 'genre:orchestral', 'hub:music', 0.95, 'placement_pass'),
    ('symphony no. 5 in c minor, op. 67', 'music_work', 'genre:orchestral', 'hub:music', 0.95, 'placement_pass'),
    ('symphony no. 5 in c-sharp minor', 'music_work', 'genre:orchestral', 'hub:music', 0.95, 'placement_pass'),
    ('symphony no. 5 in c-sharp minor: iii. scherzo', 'work', 'genre:orchestral', 'hub:music', 0.95, 'placement_pass'),
    ('symphony no. 5 in c-sharp minor: iv. adagietto', 'work', 'genre:orchestral', 'hub:music', 0.95, 'inherited'),
    ('symphony no. 6', 'work', 'genre:orchestral', 'hub:music', 0.95, 'inherited'),
    ('symphony no. 6 in a minor', 'work', 'genre:orchestral', 'hub:music', 0.95, 'placement_pass'),
    ('symphony no. 9 in d minor, op. 125', 'work', 'genre:orchestral', 'hub:music', 0.95, 'placement_pass'),
    ('tchaikovsky (violin concerto & souvenir de florence)', 'album', 'genre:classical', 'hub:music', 0.95, 'placement_pass'),
    ('tell me', 'music_work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('the 2nd mini album', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('the awakening', 'franchise', 'genre:k_pop', 'hub:music', 0.95, 'placement_pass'),
    ('the four seasons', 'franchise', 'genre:baroque', 'hub:music', 0.95, 'placement_pass'),
    ('the four seasons', 'work', 'genre:baroque', 'hub:music', 0.95, 'placement_pass'),
    ('the four seasons, concerto no. 4 in f minor, rv 297', 'work', 'genre:baroque', 'hub:music', 0.95, 'placement_pass'),
    ('the nutcracker', 'franchise', 'genre:orchestral', 'hub:music', 0.95, 'placement_pass'),
    ('the perlman sound', 'album', 'genre:orchestral', 'hub:music', 0.95, 'inherited'),
    ('the planets', 'franchise', 'genre:classical', 'hub:music', 0.95, 'placement_pass'),
    ('the potion seller', 'person', 'subject:content_creators', 'subject:content_creators', 0.95, 'placement_pass'),
    ('the very best of shostakovich', 'album', 'genre:classical', 'hub:music', 0.95, 'inherited'),
    ('the well-tempered clavier', 'franchise', 'genre:piano', 'hub:music', 0.95, 'placement_pass'),
    ('toxic', 'music_work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('turandot', 'work', 'genre:classical', 'hub:music', 0.95, 'placement_pass'),
    ('txt', 'franchise', 'genre:k_pop', 'hub:music', 0.95, 'placement_pass'),
    ('urlicht', 'work', 'genre:orchestral', 'hub:music', 0.95, 'inherited'),
    ('violeta', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('violin', 'art', 'genre:violin', 'hub:music', 0.95, 'placement_pass'),
    ('violin caprices', 'franchise', 'genre:violin', 'hub:music', 0.95, 'placement_pass'),
    ('violin concerto in a major, rv 347', 'work', 'genre:baroque', 'hub:music', 0.95, 'placement_pass'),
    ('violin concerto in c major, op. 4 no. 7, rv 185', 'work', 'genre:baroque', 'hub:music', 0.95, 'placement_pass'),
    ('violin concerto in c minor, op. 4 no. 10, rv 196', 'work', 'genre:baroque', 'hub:music', 0.95, 'placement_pass'),
    ('violin concerto in d major, op. 35', 'work', 'genre:orchestral', 'hub:music', 0.95, 'placement_pass'),
    ('violin concerto in d major, op. 35: iii. finale. allegro vivacissimo', 'work', 'genre:orchestral', 'hub:music', 0.95, 'inherited'),
    ('violin concerto in d major, op. 4 no. 11, rv 204', 'work', 'genre:baroque', 'hub:music', 0.95, 'placement_pass'),
    ('violin concerto in d major, op. 4 no. 11, rv 204: ii. largo', 'work', 'genre:baroque', 'hub:music', 0.95, 'placement_pass'),
    ('violin concerto in d major, op. 4 no. 11, rv 204: iii. allegro assai', 'work', 'genre:baroque', 'hub:music', 0.95, 'placement_pass'),
    ('violin concerto in d major, op. 77', 'music_work', 'genre:orchestral', 'hub:music', 0.95, 'placement_pass'),
    ('violin concerto in d major, op. 77', 'work', 'genre:orchestral', 'hub:music', 0.95, 'placement_pass'),
    ('violin concerto in d minor, op. 4 no. 8, rv 249', 'work', 'genre:baroque', 'hub:music', 0.95, 'placement_pass'),
    ('violin concerto in d minor, op. 4 no. 8, rv 249: iv. allegro', 'work', 'genre:baroque', 'hub:music', 0.95, 'placement_pass'),
    ('violin concerto in d minor, op. 47', 'work', 'genre:orchestral', 'hub:music', 0.95, 'placement_pass'),
    ('violin concerto in f major, op. 4 no. 9, rv 284', 'work', 'genre:baroque', 'hub:music', 0.95, 'placement_pass'),
    ('violin concerto in g major, op. 4 no. 12, rv 298', 'work', 'genre:baroque', 'hub:music', 0.95, 'placement_pass'),
    ('violin concerto no. 1 in a minor, bwv 1041', 'work', 'genre:baroque', 'hub:music', 0.95, 'placement_pass'),
    ('violin concerto no. 1 in b-flat major, k. 207: iii. presto', 'work', 'genre:classical', 'hub:music', 0.95, 'placement_pass'),
    ('violin concerto no. 5', 'work', 'genre:violin', 'hub:music', 0.95, 'placement_pass'),
    ('violin concerto no. 5 in f major, op. 91: v. appassionato (cadenza by adès)', 'work', 'genre:orchestral', 'hub:music', 0.95, 'placement_pass'),
    ('violin concerto: i. praeludium', 'work', 'genre:orchestral', 'hub:music', 0.95, 'placement_pass'),
    ('violin concerto: iv. passacaglia', 'work', 'genre:violin', 'hub:music', 0.95, 'placement_pass'),
    ('violin concertos & violin romances', 'album', 'genre:violin', 'hub:music', 0.95, 'placement_pass'),
    ('violin sonata no. 1 in g minor, bwv 1001', 'work', 'genre:chamber_music', 'hub:music', 0.95, 'placement_pass'),
    ('violin sonata no. 2 in a minor, bwv 1003', 'work', 'genre:chamber_music', 'hub:music', 0.95, 'placement_pass'),
    ('violin sonata no. 3 in c major, bwv 1005', 'work', 'genre:baroque', 'hub:music', 0.95, 'placement_pass'),
    ('violin sonatas nos. 1 & 2', 'work', 'genre:chamber_music', 'hub:music', 0.95, 'placement_pass'),
    ('violin sonatas nos. 1 & 2; partita no. 1', 'work', 'genre:baroque', 'hub:music', 0.95, 'placement_pass'),
    ('visualsounds1', 'person', 'subject:content_creators', 'subject:content_creators', 0.95, 'placement_pass'),
    ('visualsounds1 asmr', 'organization', 'subject:content_creators', 'subject:content_creators', 0.95, 'placement_pass'),
    ('vivaldi: the four seasons', 'album', 'genre:baroque', 'hub:music', 0.95, 'placement_pass'),
    ('waltz of the flowers', 'music_work', 'genre:orchestral', 'hub:music', 0.95, 'placement_pass'),
    ('wannabe', 'franchise', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('we go up', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('white sheep', 'work', 'genre:mandopop', 'hub:music', 0.95, 'placement_pass'),
    ('who is my groom', 'work', 'genre:mandopop', 'hub:music', 0.95, 'placement_pass'),
    ('winter', 'work', 'genre:baroque', 'hub:music', 0.95, 'placement_pass'),
    ('wo lian ai le', 'work', 'genre:mandopop', 'hub:music', 0.95, 'placement_pass'),
    ('wonder girls', 'group', 'genre:k_pop', 'hub:music', 0.95, 'placement_pass'),
    ('xiao yu', 'work', 'genre:mandopop', 'hub:music', 0.95, 'inherited'),
    ('xoxz', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('xu chenglong', 'person', 'subject:content_creators', 'subject:content_creators', 0.95, 'placement_pass'),
    ('yishan', 'person', 'subject:content_creators', 'subject:content_creators', 0.95, 'placement_pass'),
    ('you & i', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('yuanlai aiqing bushi xihuan', 'music_work', 'genre:mandopop', 'hub:music', 0.95, 'inherited'),
    ('yue lai yue bu dong', 'work', 'genre:mandopop', 'hub:music', 0.95, 'inherited'),
    ('yuqi', 'person', 'genre:k_pop', 'hub:music', 0.95, 'placement_pass'),
    ('yuttchaco', 'person', 'subject:content_creators', 'subject:content_creators', 0.95, 'placement_pass'),
    ('zero:attitude', 'work', 'genre:k_pop', 'hub:music', 0.95, 'inherited'),
    ('zigeunerweisen, op. 20', 'work', 'genre:orchestral', 'hub:music', 0.95, 'placement_pass'),
    ('你不知道的事', 'work', 'genre:mandopop', 'hub:music', 0.95, 'inherited'),
    ('춤 (choom)', 'album', 'genre:k_pop', 'hub:music', 0.95, 'inherited')
  ;
  insert into semantic_private.presumed_term_placements
    (normalized_label, family, parent_concept_id, hub_key,
     confidence, source, corpus)
  select p.normalized_label, p.family, c.id, p.hub_key,
         p.confidence, p.source, 'ris_v20'
    from _placement p
    join ontology.concepts c
      on c.concept_key = p.parent_key and c.retired_at is null
  on conflict (normalized_label, family, hub_key) do update
    set parent_concept_id = excluded.parent_concept_id,
        confidence = excluded.confidence,
        source = excluded.source,
        corpus = excluded.corpus;
  get diagnostics n = row_count;
  raise notice '0383: % per-hub placements landed', n;
  if n = 0 then
    raise exception
      '0383: placements were emitted and none matched a concept';
  end if;
end;
$$;

